// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod orts {
    pub mod plugin {
        /// Physics primitives exchanged between host and guest.
        ///
        /// All vector / quaternion / state types use the orts project
        /// conventions: km and km/s for orbital state, rad and rad/s for
        /// attitude, A·m² for magnetic moment, Hamilton quaternions with
        /// scalar-first layout, ECI-based vectors unless a component name
        /// says otherwise.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            /// 3-component real vector.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Vec3 {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for Vec3 {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Vec3")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// Hamilton quaternion, scalar-first `(w, x, y, z)`.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Quat {
                pub w: f64,
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for Quat {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Quat")
                        .field("w", &self.w)
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// Orbital state in the Earth-centred inertial (ECI) frame.
            /// Position in km, velocity in km/s.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct OrbitalState {
                pub position: Vec3,
                pub velocity: Vec3,
            }
            impl ::core::fmt::Debug for OrbitalState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("OrbitalState")
                        .field("position", &self.position)
                        .field("velocity", &self.velocity)
                        .finish()
                }
            }
            /// Rigid-body attitude: orientation (body→inertial) plus angular
            /// velocity expressed in the body frame \[rad/s\].
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct AttitudeState {
                pub orientation: Quat,
                pub angular_velocity: Vec3,
            }
            impl ::core::fmt::Debug for AttitudeState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AttitudeState")
                        .field("orientation", &self.orientation)
                        .field("angular-velocity", &self.angular_velocity)
                        .finish()
                }
            }
            /// Complete spacecraft state handed to a plugin controller at
            /// every sample tick. Matches the host-side
            /// `orts::SpacecraftState` layout.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct SpacecraftState {
                pub orbit: OrbitalState,
                pub attitude: AttitudeState,
                /// Spacecraft mass \[kg\].
                pub mass: f64,
            }
            impl ::core::fmt::Debug for SpacecraftState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("SpacecraftState")
                        .field("orbit", &self.orbit)
                        .field("attitude", &self.attitude)
                        .field("mass", &self.mass)
                        .finish()
                }
            }
            /// Astronomical epoch, serialised as a raw Julian Date (JD) so
            /// it maps bit-for-bit to `kaname::epoch::Epoch { jd }`.
            ///
            /// **Timescale note**: Phase P1 of `kaname::Epoch` does not
            /// strictly distinguish UTC / TAI / TT. The `J2000_JD` constant
            /// is the TT J2000 (`2451545.0`), but `from_gregorian(...)`
            /// folds UTC components onto that timeline without leap-second
            /// bookkeeping. Guests that need "seconds since J2000" should
            /// compute `(julian-date - 2451545.0) * 86400.0` on their side
            /// and treat the result as a pragmatic TT-ish second count.
            /// Phase P2 may tighten the host-side timescale definition; the
            /// WIT `julian-date` field name is neutral enough to survive
            /// that change without renaming.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Epoch {
                pub julian_date: f64,
            }
            impl ::core::fmt::Debug for Epoch {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Epoch")
                        .field("julian-date", &self.julian_date)
                        .finish()
                }
            }
            /// Environment snapshot evaluated once at the tick instant and
            /// passed to the guest.
            ///
            /// **Phase P1-b1**: shipped empty on purpose. Phase P1-b3 will
            /// populate it with pre-computed fields that guests care about
            /// (magnetic field in the body frame, sun direction in ECI,
            /// atmospheric density, ...). Adding fields to this record is
            /// **ABI-breaking under Canonical ABI**: guests built against
            /// v0.1.0 MUST be recompiled when the record layout grows. We
            /// accept this because Phase P1 ships host and guest lockstep;
            /// once third-party guests exist we will freeze the layout and
            /// add fields via a new wit version.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct EnvSnapshot {
                /// Placeholder to satisfy the Component Model rule that records
                /// must have at least one field (wit-bindgen 0.41+ enforces
                /// this). Phase P3 will replace this with meaningful
                /// pre-computed environment fields (magnetic field, sun
                /// direction, atmospheric density).
                pub reserved: bool,
            }
            impl ::core::fmt::Debug for EnvSnapshot {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("EnvSnapshot")
                        .field("reserved", &self.reserved)
                        .finish()
                }
            }
            /// Per-tick observation handed to `controller.update`. This is
            /// the WIT counterpart of the host-side
            /// `orts::plugin::Observation<'a>` struct.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Observation {
                /// Simulation time \[s\], measured from the controller's
                /// reference t=0 (not wall clock).
                pub t: f64,
                pub spacecraft: SpacecraftState,
                /// Absolute epoch, if the simulation is bound to a
                /// wall-clock timebase.
                pub epoch: Option<Epoch>,
                pub env: EnvSnapshot,
            }
            impl ::core::fmt::Debug for Observation {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Observation")
                        .field("t", &self.t)
                        .field("spacecraft", &self.spacecraft)
                        .field("epoch", &self.epoch)
                        .field("env", &self.env)
                        .finish()
                }
            }
            /// Logical actuator command returned by the controller.
            ///
            /// Phase P1 only carries the `magnetic-moment` variant so that
            /// the first guest (B-dot) can do a full end-to-end run. Later
            /// phases append `reaction-wheel`, `throttle`, and
            /// `impulsive-dv` variants; adding variants is non-breaking
            /// because callers (Rust host) consume the value through a
            /// `#[non_exhaustive]` enum that can always fall through.
            ///
            /// Renaming, removing, or reordering existing variants is
            /// **breaking** and must ship under `wit/v2/`.
            #[derive(Clone, Copy)]
            pub enum Command {
                /// Commanded magnetic dipole moment in the body frame
                /// \[A·m²\].
                MagneticMoment(Vec3),
            }
            impl ::core::fmt::Debug for Command {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Command::MagneticMoment(e) => {
                            f.debug_tuple("Command::MagneticMoment").field(e).finish()
                        }
                    }
                }
            }
        }
        /// Host-side services imported by the guest.
        ///
        /// These functions are the only legal way for a guest to reach back
        /// into host state during an `update` call. Every function is
        /// expected to be cheap and side-effect-free (`log` aside) because
        /// the host may call a controller multiple times per second across
        /// many satellites.
        ///
        /// The interface name is `host-env` rather than plain `env` to
        /// avoid visual collision with the `env-snapshot` record under
        /// `interface types`.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host_env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type Vec3 = super::super::super::orts::plugin::types::Vec3;
            pub type Epoch = super::super::super::orts::plugin::types::Epoch;
            /// Logging severity levels, matching the `tracing` crate levels
            /// used throughout orts. `warn` and `error` guest messages are
            /// always routed to the host's current `tracing` subscriber;
            /// lower levels are filtered according to the subscriber's
            /// configuration.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum LogLevel {
                Trace,
                Debug,
                Info,
                Warn,
                Error,
            }
            impl ::core::fmt::Debug for LogLevel {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogLevel::Trace => f.debug_tuple("LogLevel::Trace").finish(),
                        LogLevel::Debug => f.debug_tuple("LogLevel::Debug").finish(),
                        LogLevel::Info => f.debug_tuple("LogLevel::Info").finish(),
                        LogLevel::Warn => f.debug_tuple("LogLevel::Warn").finish(),
                        LogLevel::Error => f.debug_tuple("LogLevel::Error").finish(),
                    }
                }
            }
            impl LogLevel {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> LogLevel {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => LogLevel::Trace,
                        1 => LogLevel::Debug,
                        2 => LogLevel::Info,
                        3 => LogLevel::Warn,
                        4 => LogLevel::Error,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Emit a log record from the guest.
            pub fn log(level: LogLevel, message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "orts:plugin/host-env@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import1(_: i32, _: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(level.clone() as i32, ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Evaluate the geomagnetic field at a given ECI position and
            /// epoch. Returns the field vector in ECI coordinates \[T\].
            ///
            /// Phase P1 wires this to the host's default magnetic model
            /// (`tobari::magnetic::TiltedDipole`). Phase D-5 upgrades this
            /// to IGRF spherical harmonics.
            pub fn magnetic_field_eci(position_eci_km: Vec3, e: Epoch) -> Vec3 {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 24]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 24]);
                    let super::super::super::orts::plugin::types::Vec3 {
                        x: x0,
                        y: y0,
                        z: z0,
                    } = position_eci_km;
                    let super::super::super::orts::plugin::types::Epoch {
                        julian_date: julian_date1,
                    } = e;
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "orts:plugin/host-env@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "magnetic-field-eci"]
                        fn wit_import3(_: f64, _: f64, _: f64, _: f64, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: f64,
                        _: f64,
                        _: f64,
                        _: f64,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(
                            _rt::as_f64(x0),
                            _rt::as_f64(y0),
                            _rt::as_f64(z0),
                            _rt::as_f64(julian_date1),
                            ptr2,
                        )
                    };
                    let l4 = *ptr2.add(0).cast::<f64>();
                    let l5 = *ptr2.add(8).cast::<f64>();
                    let l6 = *ptr2.add(16).cast::<f64>();
                    let result7 = super::super::super::orts::plugin::types::Vec3 {
                        x: l4,
                        y: l5,
                        z: l6,
                    };
                    result7
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod orts {
        pub mod plugin {
            /// Guest-side entry points exported to the host.
            ///
            /// A plugin implements this interface once; the host then creates
            /// one `wasmtime::component::Instance` per satellite and drives it
            /// through `initial-command` + repeated `update` calls at the
            /// controller's sample period.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod controller {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Observation = super::super::super::super::orts::plugin::types::Observation;
                pub type Command = super::super::super::super::orts::plugin::types::Command;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sample_period_s_cabi<T: Guest>() -> f64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::sample_period_s();
                    _rt::as_f64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::init(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_initial_command_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::initial_command();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    use super::super::super::super::orts::plugin::types::Command as V3;
                    match result0 {
                        V3::MagneticMoment(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::orts::plugin::types::Vec3 {
                                x: x2,
                                y: y2,
                                z: z2,
                            } = e;
                            *ptr1.add(8).cast::<f64>() = _rt::as_f64(x2);
                            *ptr1.add(16).cast::<f64>() = _rt::as_f64(y2);
                            *ptr1.add(24).cast::<f64>() = _rt::as_f64(z2);
                        }
                    }
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_update_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let l0 = *arg0.add(0).cast::<f64>();
                    let l1 = *arg0.add(8).cast::<f64>();
                    let l2 = *arg0.add(16).cast::<f64>();
                    let l3 = *arg0.add(24).cast::<f64>();
                    let l4 = *arg0.add(32).cast::<f64>();
                    let l5 = *arg0.add(40).cast::<f64>();
                    let l6 = *arg0.add(48).cast::<f64>();
                    let l7 = *arg0.add(56).cast::<f64>();
                    let l8 = *arg0.add(64).cast::<f64>();
                    let l9 = *arg0.add(72).cast::<f64>();
                    let l10 = *arg0.add(80).cast::<f64>();
                    let l11 = *arg0.add(88).cast::<f64>();
                    let l12 = *arg0.add(96).cast::<f64>();
                    let l13 = *arg0.add(104).cast::<f64>();
                    let l14 = *arg0.add(112).cast::<f64>();
                    let l15 = i32::from(*arg0.add(120).cast::<u8>());
                    let l17 = i32::from(*arg0.add(136).cast::<u8>());
                    let result18 = T::update(super::super::super::super::orts::plugin::types::Observation {
                        t: l0,
                        spacecraft: super::super::super::super::orts::plugin::types::SpacecraftState {
                            orbit: super::super::super::super::orts::plugin::types::OrbitalState {
                                position: super::super::super::super::orts::plugin::types::Vec3 {
                                    x: l1,
                                    y: l2,
                                    z: l3,
                                },
                                velocity: super::super::super::super::orts::plugin::types::Vec3 {
                                    x: l4,
                                    y: l5,
                                    z: l6,
                                },
                            },
                            attitude: super::super::super::super::orts::plugin::types::AttitudeState {
                                orientation: super::super::super::super::orts::plugin::types::Quat {
                                    w: l7,
                                    x: l8,
                                    y: l9,
                                    z: l10,
                                },
                                angular_velocity: super::super::super::super::orts::plugin::types::Vec3 {
                                    x: l11,
                                    y: l12,
                                    z: l13,
                                },
                            },
                            mass: l14,
                        },
                        epoch: match l15 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l16 = *arg0.add(128).cast::<f64>();
                                    super::super::super::super::orts::plugin::types::Epoch {
                                        julian_date: l16,
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        env: super::super::super::super::orts::plugin::types::EnvSnapshot {
                            reserved: _rt::bool_lift(l17 as u8),
                        },
                    });
                    _rt::cabi_dealloc(arg0, 144, 8);
                    let ptr19 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result18 {
                        Ok(e) => {
                            *ptr19.add(0).cast::<u8>() = (0i32) as u8;
                            use super::super::super::super::orts::plugin::types::Command as V21;
                            match e {
                                V21::MagneticMoment(e) => {
                                    *ptr19.add(8).cast::<u8>() = (0i32) as u8;
                                    let super::super::super::super::orts::plugin::types::Vec3 {
                                        x: x20,
                                        y: y20,
                                        z: z20,
                                    } = e;
                                    *ptr19.add(16).cast::<f64>() = _rt::as_f64(x20);
                                    *ptr19.add(24).cast::<f64>() = _rt::as_f64(y20);
                                    *ptr19.add(32).cast::<f64>() = _rt::as_f64(z20);
                                }
                            }
                        }
                        Err(e) => {
                            *ptr19.add(0).cast::<u8>() = (1i32) as u8;
                            let vec22 = (e.into_bytes()).into_boxed_slice();
                            let ptr22 = vec22.as_ptr().cast::<u8>();
                            let len22 = vec22.len();
                            ::core::mem::forget(vec22);
                            *ptr19
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len22;
                            *ptr19.add(8).cast::<*mut u8>() = ptr22.cast_mut();
                        }
                    };
                    ptr19
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_update<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_current_mode_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::current_mode();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Some(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        None => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_current_mode<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Fixed sample period \[s\] at which the host should call
                    /// `update`. Queried once at instantiation.
                    fn sample_period_s() -> f64;
                    /// Optional one-time initialisation called by the host with a
                    /// backend-specific configuration blob. Phase P1 hosts default
                    /// to JSON encoding of the backend-specific parameters but do
                    /// not enforce it; guests that want TOML / YAML / plain-string
                    /// config can interpret the blob however they like.
                    fn init(config: _rt::String) -> Result<(), _rt::String>;
                    /// Command to apply during the very first zero-order-hold
                    /// segment, before any `update` call has happened. Normally a
                    /// safe zero / identity command.
                    fn initial_command() -> Command;
                    /// Advance the controller by one sample tick and return the
                    /// command to apply for the next zero-order-hold segment.
                    ///
                    /// The error channel uses a plain `string` for Phase P1 to
                    /// match the host's `PluginError::Runtime(String)` fallback.
                    /// Phase P2 may upgrade this to a structured
                    /// `variant plugin-error { ... }`, which is ABI-breaking and
                    /// would ship under `wit/v2/`.
                    fn update(obs: Observation) -> Result<Command, _rt::String>;
                    /// Human-readable name of the controller's currently active
                    /// mode (detumble / nadir / burn / ...). Returns `none` if the
                    /// controller does not model discrete modes, which is distinct
                    /// from returning `some("")`.
                    fn current_mode() -> Option<_rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_orts_plugin_controller_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "orts:plugin/controller@0.1.0#sample-period-s")] unsafe extern
                        "C" fn export_sample_period_s() -> f64 { unsafe {
                        $($path_to_types)*:: _export_sample_period_s_cabi::<$ty > () } }
                        #[unsafe (export_name = "orts:plugin/controller@0.1.0#init")]
                        unsafe extern "C" fn export_init(arg0 : * mut u8, arg1 : usize,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_init_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name
                        = "cabi_post_orts:plugin/controller@0.1.0#init")] unsafe extern
                        "C" fn _post_return_init(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "orts:plugin/controller@0.1.0#initial-command")] unsafe extern
                        "C" fn export_initial_command() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_initial_command_cabi::<$ty > () } }
                        #[unsafe (export_name = "orts:plugin/controller@0.1.0#update")]
                        unsafe extern "C" fn export_update(arg0 : * mut u8,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_update_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cabi_post_orts:plugin/controller@0.1.0#update")] unsafe extern
                        "C" fn _post_return_update(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_update::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "orts:plugin/controller@0.1.0#current-mode")] unsafe extern "C"
                        fn export_current_mode() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_current_mode_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_orts:plugin/controller@0.1.0#current-mode")] unsafe
                        extern "C" fn _post_return_current_mode(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_current_mode::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_orts_plugin_controller_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 40]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 40],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::orts::plugin::controller::__export_orts_plugin_controller_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::orts::plugin::controller);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:orts:plugin@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 965] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc8\x06\x01A\x02\x01\
A\x0a\x01B\x13\x01r\x03\x01xu\x01yu\x01zu\x04\0\x04vec3\x03\0\0\x01r\x04\x01wu\x01\
xu\x01yu\x01zu\x04\0\x04quat\x03\0\x02\x01r\x02\x08position\x01\x08velocity\x01\x04\
\0\x0dorbital-state\x03\0\x04\x01r\x02\x0borientation\x03\x10angular-velocity\x01\
\x04\0\x0eattitude-state\x03\0\x06\x01r\x03\x05orbit\x05\x08attitude\x07\x04mass\
u\x04\0\x10spacecraft-state\x03\0\x08\x01r\x01\x0bjulian-dateu\x04\0\x05epoch\x03\
\0\x0a\x01r\x01\x08reserved\x7f\x04\0\x0cenv-snapshot\x03\0\x0c\x01k\x0b\x01r\x04\
\x01tu\x0aspacecraft\x09\x05epoch\x0e\x03env\x0d\x04\0\x0bobservation\x03\0\x0f\x01\
q\x01\x0fmagnetic-moment\x01\x01\0\x04\0\x07command\x03\0\x11\x03\0\x17orts:plug\
in/types@0.1.0\x05\0\x02\x03\0\0\x04vec3\x02\x03\0\0\x05epoch\x01B\x0a\x02\x03\x02\
\x01\x01\x04\0\x04vec3\x03\0\0\x02\x03\x02\x01\x02\x04\0\x05epoch\x03\0\x02\x01m\
\x05\x05trace\x05debug\x04info\x04warn\x05error\x04\0\x09log-level\x03\0\x04\x01\
@\x02\x05level\x05\x07messages\x01\0\x04\0\x03log\x01\x06\x01@\x02\x0fposition-e\
ci-km\x01\x01e\x03\0\x01\x04\0\x12magnetic-field-eci\x01\x07\x03\0\x1aorts:plugi\
n/host-env@0.1.0\x05\x03\x02\x03\0\0\x0bobservation\x02\x03\0\0\x07command\x01B\x11\
\x02\x03\x02\x01\x04\x04\0\x0bobservation\x03\0\0\x02\x03\x02\x01\x05\x04\0\x07c\
ommand\x03\0\x02\x01@\0\0u\x04\0\x0fsample-period-s\x01\x04\x01j\0\x01s\x01@\x01\
\x06configs\0\x05\x04\0\x04init\x01\x06\x01@\0\0\x03\x04\0\x0finitial-command\x01\
\x07\x01j\x01\x03\x01s\x01@\x01\x03obs\x01\0\x08\x04\0\x06update\x01\x09\x01ks\x01\
@\0\0\x0a\x04\0\x0ccurrent-mode\x01\x0b\x04\0\x1corts:plugin/controller@0.1.0\x05\
\x06\x04\0\x18orts:plugin/plugin@0.1.0\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rus\
t\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
