//! `WasmController`: a `PluginController` backed by a WebAssembly
//! Component guest.
//!
//! This is the central glue of Phase P1. A `WasmController` owns a
//! `wasmtime::Store<HostState>` and a `Plugin` handle obtained from
//! `PluginPre::instantiate`. It implements `PluginController` by
//! forwarding every `update` call to the guest's
//! `controller.update(observation) -> result<command, string>` export
//! via the type-safe bindings generated by `wasmtime::component::bindgen!`.
//!
//! ## Lifecycle
//!
//! ```text
//! WasmEngine::new()           → Engine (shared, Arc)
//! Component::new(&engine, ..) → Component (shared, Arc)
//! Linker + Plugin::add_to_linker → PluginPre (shared, Arc)
//! PluginPre::instantiate(store)  → Plugin + Guest (per satellite)
//! guest.call_update(&mut store, obs) → Result<Command, String>
//! ```
//!
//! Phase P1-b2 provides the `WasmController` struct and its
//! `PluginController` impl. End-to-end execution requires a compiled
//! WASM Component guest, which arrives in Phase P1-c.

use std::sync::Arc;

use wasmtime::Store;
use wasmtime::component::Component;

use super::bindings::{Plugin, PluginPre};
use super::convert;
use super::engine::WasmEngine;
use super::host_state::HostState;

use crate::plugin::controller::PluginController;
use crate::plugin::observation::Observation;
use crate::plugin::{Command, PluginError};

/// A `PluginController` backed by a WebAssembly Component guest.
///
/// Each satellite simulation creates one `WasmController`. The
/// `PluginPre` (which encodes a pre-linked Component + Linker cache)
/// is shared across satellites via `Arc` so that instantiation is
/// cheap (~5 µs per instance).
pub struct WasmController {
    store: Store<HostState>,
    plugin: Plugin,
    /// Cached sample period, queried once at construction.
    sample_period: f64,
    /// Cached controller name.
    name: String,
}

impl WasmController {
    /// Instantiate a WASM guest controller for one satellite.
    ///
    /// `pre` is the pre-linked component obtained from
    /// [`Self::prepare`]. `label` is a human-readable satellite
    /// identifier used for log routing.
    pub fn new(pre: &PluginPre<HostState>, label: impl Into<String>) -> Result<Self, PluginError> {
        let label = label.into();
        let engine = pre.engine();
        let host_state = HostState::new(&label);
        let mut store = Store::new(engine, host_state);
        let plugin = pre
            .instantiate(&mut store)
            .map_err(|e| PluginError::Init(format!("instantiate failed for '{label}': {e}")))?;

        let guest = plugin.orts_plugin_controller();
        let sample_period = guest
            .call_sample_period_s(&mut store)
            .map_err(|e| PluginError::Init(format!("sample-period-s call failed: {e}")))?;

        Ok(Self {
            store,
            plugin,
            sample_period,
            name: format!("wasm:{label}"),
        })
    }

    /// Pre-link a Component against the host-env imports so that
    /// [`Self::new`] only needs to instantiate (fast path).
    ///
    /// This is called once per unique `.wasm` / `.cwasm` artefact
    /// and the resulting `PluginPre` is shared across all satellites
    /// that use the same controller binary.
    pub fn prepare(
        engine: &Arc<WasmEngine>,
        component: &Component,
    ) -> Result<PluginPre<HostState>, PluginError> {
        let mut linker = wasmtime::component::Linker::new(engine.inner());
        // Register WASI CLI imports (Rust std-based guests require
        // wasi:cli/environment, wasi:cli/exit, etc. even if the
        // controller itself never does I/O).
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| PluginError::Init(format!("WASI add_to_linker failed: {e}")))?;
        Plugin::add_to_linker::<HostState, HostState>(&mut linker, |state| state)
            .map_err(|e| PluginError::Init(format!("add_to_linker failed: {e}")))?;
        let instance_pre = linker
            .instantiate_pre(component)
            .map_err(|e| PluginError::Init(format!("instantiate_pre failed: {e}")))?;
        PluginPre::new(instance_pre)
            .map_err(|e| PluginError::Init(format!("PluginPre::new failed: {e}")))
    }
}

impl PluginController for WasmController {
    fn name(&self) -> &str {
        &self.name
    }

    fn sample_period(&self) -> f64 {
        self.sample_period
    }

    fn initial_command(&self) -> Command {
        // API note: `call_initial_command` needs `&mut Store`, but
        // `PluginController::initial_command` is `&self`. Phase P1-c
        // will call the guest in `new()` and cache the result here.
        // Until then, return a safe default (zero magnetic moment).
        Command::MagneticMoment(nalgebra::Vector3::zeros())
    }

    fn update(&mut self, obs: &Observation<'_>) -> Result<Command, PluginError> {
        let wit_obs = convert::observation_to_wit(obs);
        let guest = self.plugin.orts_plugin_controller();
        let result = guest
            .call_update(&mut self.store, wit_obs)
            .map_err(|e| PluginError::Runtime(format!("guest update trapped: {e}")))?;
        match result {
            Ok(wit_cmd) => convert::command_from_wit(wit_cmd),
            Err(guest_err) => Err(PluginError::Runtime(guest_err)),
        }
    }
}
