#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Generate the IAU-1980 nutation series table for arika.

Fetches the 106-term IAU 1980 nutation series from ERFA's `nut80.c`
(liberfa/erfa, BSD-3) — the same machine-readable copy of the IAU 1980
Theory of Nutation that ERFA evaluates — and emits it as a Rust table at
`arika/src/earth/fk5/nutation_table.rs`. Generating from ERFA's own
table guarantees arika's `nut80` matches ERFA to machine precision.

The underlying coefficients are the IAU 1980 nutation standard (Wahr;
IAU Resolution); ERFA's file is a convenient parseable source. The
generated table carries an attribution header.

Usage (from the repository root):

    uv run arika/tools/generate_iau1980_nutation.py
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

SOURCES = [
    "https://raw.githubusercontent.com/liberfa/erfa/master/src/nut80.c",
]

OUT = Path("arika/src/earth/fk5/nutation_table.rs")

# Each data row: { nl, nlp, nf, nd, nom, sp, spt, ce, cet }
ROW = re.compile(
    r"\{\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),"
    r"\s*(-?\d+\.\d+),\s*(-?\d+\.\d+),\s*(-?\d+\.\d+),\s*(-?\d+\.\d+)\s*\}"
)


def fetch() -> str:
    last = None
    for url in SOURCES:
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                return r.read().decode("utf-8")
        except Exception as e:  # noqa: BLE001
            last = e
    raise SystemExit(f"failed to fetch nut80.c: {last}")


def main() -> None:
    text = fetch()
    rows = ROW.findall(text)
    if len(rows) != 106:
        raise SystemExit(f"expected 106 nutation terms, parsed {len(rows)}")

    lines = [
        "// @generated by arika/tools/generate_iau1980_nutation.py — do not edit.",
        "//",
        "// IAU 1980 nutation series (106 terms), transcribed from ERFA's nut80.c",
        "// (liberfa/erfa, BSD-3-Clause), itself a copy of the IAU 1980 Theory of",
        "// Nutation. Columns: Delaunay multipliers (l, l', F, D, Ω) and the",
        "// longitude-sine (sp, spt) and obliquity-cosine (ce, cet) coefficients,",
        "// in units of 0.1 mas (and the same per Julian century).",
        "",
        "/// One term of the IAU 1980 nutation series.",
        "#[derive(Clone, Copy)]",
        "pub(crate) struct NutationTerm {",
        "    /// Delaunay-argument multipliers (l, l', F, D, Ω).",
        "    pub mult: [i8; 5],",
        "    /// Longitude sine coefficient and its per-century rate [0.1 mas].",
        "    pub longitude: [f64; 2],",
        "    /// Obliquity cosine coefficient and its per-century rate [0.1 mas].",
        "    pub obliquity: [f64; 2],",
        "}",
        "",
        "#[rustfmt::skip]",
        f"pub(crate) static IAU1980_NUTATION: [NutationTerm; {len(rows)}] = [",
    ]
    for nl, nlp, nf, nd, nom, sp, spt, ce, cet in rows:
        lines.append(
            f"    NutationTerm {{ mult: [{nl}, {nlp}, {nf}, {nd}, {nom}], "
            f"longitude: [{sp}, {spt}], obliquity: [{ce}, {cet}] }},"
        )
    lines.append("];")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} terms)")


if __name__ == "__main__":
    main()
