import { describe, expect, it } from "vitest";
import * as THREE from "three";
import { entityPathToBodyId, getBodyRadius } from "./bodies.js";

describe("entityPathToBodyId", () => {
  it("returns null for satellite paths", () => {
    expect(entityPathToBodyId("/world/sat/iss")).toBeNull();
    expect(entityPathToBodyId("/world/sat/apollo11")).toBeNull();
  });

  it("returns body id for known body paths", () => {
    expect(entityPathToBodyId("/world/moon")).toBe("moon");
    expect(entityPathToBodyId("/world/sun")).toBe("sun");
    expect(entityPathToBodyId("/world/mars")).toBe("mars");
    expect(entityPathToBodyId("/world/earth")).toBe("earth");
  });

  it("returns null for unknown body paths", () => {
    expect(entityPathToBodyId("/world/pluto")).toBeNull();
  });
});

describe("getBodyRadius", () => {
  it("returns radius for known bodies", () => {
    expect(getBodyRadius("moon")).toBeCloseTo(1737.4, 0);
    expect(getBodyRadius("earth")).toBeCloseTo(6378.137, 0);
  });

  it("returns null for unknown bodies", () => {
    expect(getBodyRadius("pluto")).toBeNull();
  });
});

/**
 * Verify that the IAU body orientation + pole alignment pipeline
 * correctly maps the Three.js sphere texture center to the expected
 * direction in ECI space.
 *
 * Reference quaternions are generated by kaname's Rust IAU rotation model
 * (kaname/src/rotation.rs `generate_fixture_quaternions` test). This ensures
 * the viewer test is an INDEPENDENT oracle — if the Rust model or the viewer
 * pipeline has a bug, the test will catch the mismatch.
 *
 * Three.js SphereGeometry UV mapping:
 *   U=0.0 (left edge)   → -X direction at equator
 *   U=0.5 (center)      → +X direction at equator
 *   V=0.0 (top)         → +Y (Three.js north pole)
 */
describe("Moon texture orientation pipeline", () => {
  /**
   * Reference IAU orientation quaternions [w, x, y, z] generated by
   * kaname's Rust implementation. These serve as the ground truth.
   */
  const FIXTURES = [
    {
      body: "moon",
      jd: 2440426.4363842593,
      label: "apollo11_end",
      q: [0.863943126223670, 0.179413151322515, -0.095699191605526, 0.460711255027968],
    },
    {
      body: "moon",
      jd: 2440418.064,
      label: "apollo11_start",
      q: [0.871697833793808, 0.181043529464248, 0.092577885778314, -0.445864847305916],
    },
    {
      body: "mars",
      jd: 2451545,
      label: "j2000",
      q: [-0.357517907770105, 0.137136387216053, -0.287180643018793, 0.878010156661259],
    },
    {
      body: "earth",
      jd: 2451545,
      label: "j2000",
      q: [0.766868391457321, -0.0, 0.0, -0.641804386229683],
    },
  ];

  /** Apply the same transform chain as SecondaryBody in Scene.tsx */
  function applyFullPipeline(iauQuat: THREE.Quaternion): THREE.Quaternion {
    const poleAlign = new THREE.Quaternion().setFromEuler(new THREE.Euler(Math.PI / 2, 0, 0));
    return iauQuat.clone().multiply(poleAlign);
  }

  /** Build Three.js quaternion from kaname fixture [w, x, y, z] */
  function fixtureToThreeQuat(q: number[]): THREE.Quaternion {
    return new THREE.Quaternion(q[1], q[2], q[3], q[0]); // THREE uses (x,y,z,w)
  }

  it("Three.js sphere UV seam is at -X direction", () => {
    const geo = new THREE.SphereGeometry(1, 32, 16);
    const uv = geo.getAttribute("uv");
    const pos = geo.getAttribute("position");

    let seam: THREE.Vector3 | null = null;
    for (let i = 0; i < uv.count; i++) {
      const u = uv.getX(i);
      const y = pos.getY(i);
      if (Math.abs(y) < 0.1 && u < 0.02) {
        seam = new THREE.Vector3(pos.getX(i), pos.getY(i), pos.getZ(i));
        break;
      }
    }

    expect(seam).not.toBeNull();
    expect(seam!.x).toBeLessThan(-0.9);
    expect(Math.abs(seam!.z)).toBeLessThan(0.2);
  });

  it("Three.js sphere texture center (U=0.5) is at +X direction", () => {
    const geo = new THREE.SphereGeometry(1, 32, 16);
    const uv = geo.getAttribute("uv");
    const pos = geo.getAttribute("position");

    let center: THREE.Vector3 | null = null;
    for (let i = 0; i < uv.count; i++) {
      const u = uv.getX(i);
      const y = pos.getY(i);
      if (Math.abs(y) < 0.1 && Math.abs(u - 0.5) < 0.02) {
        center = new THREE.Vector3(pos.getX(i), pos.getY(i), pos.getZ(i));
        break;
      }
    }

    expect(center).not.toBeNull();
    expect(center!.x).toBeGreaterThan(0.9);
    expect(Math.abs(center!.z)).toBeLessThan(0.2);
  });

  it("pole alignment maps +Y to +Z and keeps +X unchanged", () => {
    const poleAlign = new THREE.Quaternion().setFromEuler(new THREE.Euler(Math.PI / 2, 0, 0));

    const y = new THREE.Vector3(0, 1, 0).applyQuaternion(poleAlign);
    expect(y.z).toBeCloseTo(1, 5);
    expect(Math.abs(y.x)).toBeLessThan(1e-10);
    expect(Math.abs(y.y)).toBeLessThan(1e-10);

    const x = new THREE.Vector3(1, 0, 0).applyQuaternion(poleAlign);
    expect(x.x).toBeCloseTo(1, 5);
  });

  it("full pipeline: Moon texture center faces Earth at Apollo 11 epoch", () => {
    const fixture = FIXTURES[0]; // apollo11_end
    const iauQuat = fixtureToThreeQuat(fixture.q);
    const combined = applyFullPipeline(iauQuat);

    // Texture center (+X in Three.js local) after full pipeline
    const textureCenter = new THREE.Vector3(1, 0, 0).applyQuaternion(combined);

    // Moon position at Apollo 11 end (from kaname moon_position_eci)
    const moonPos = new THREE.Vector3(-244023, -246348, -137135);
    const earthDir = moonPos.clone().negate().normalize();

    const angle = textureCenter.angleTo(earthDir) * (180 / Math.PI);
    expect(angle).toBeLessThan(15);
  });

  it("full pipeline: Moon texture center faces Earth at Apollo 11 start", () => {
    const fixture = FIXTURES[1]; // apollo11_start
    const iauQuat = fixtureToThreeQuat(fixture.q);
    const combined = applyFullPipeline(iauQuat);

    const textureCenter = new THREE.Vector3(1, 0, 0).applyQuaternion(combined);

    // Moon position at Apollo 11 start (from kaname moon_position_eci)
    const moonPos = new THREE.Vector3(-223218, 298748, 159150);
    const earthDir = moonPos.clone().negate().normalize();

    const angle = textureCenter.angleTo(earthDir) * (180 / Math.PI);
    expect(angle).toBeLessThan(15);
  });

  it("full pipeline: UV seam faces away from Earth", () => {
    const fixture = FIXTURES[0]; // apollo11_end
    const iauQuat = fixtureToThreeQuat(fixture.q);
    const combined = applyFullPipeline(iauQuat);

    const seamDir = new THREE.Vector3(-1, 0, 0).applyQuaternion(combined);

    const moonPos = new THREE.Vector3(-164710, -287813, -158607);
    const earthDir = moonPos.clone().negate().normalize();

    const angle = seamDir.angleTo(earthDir) * (180 / Math.PI);
    expect(angle).toBeGreaterThan(165);
  });

  it("full pipeline: north pole points roughly toward ecliptic normal", () => {
    const fixture = FIXTURES[0]; // apollo11_end
    const iauQuat = fixtureToThreeQuat(fixture.q);
    const combined = applyFullPipeline(iauQuat);

    const pole = new THREE.Vector3(0, 1, 0).applyQuaternion(combined);

    const obliquity = (23.44 * Math.PI) / 180;
    const eclNormal = new THREE.Vector3(0, -Math.sin(obliquity), Math.cos(obliquity));

    const angle = pole.angleTo(eclNormal) * (180 / Math.PI);
    expect(angle).toBeLessThan(10);
  });

  it("fixture quaternions are unit quaternions", () => {
    for (const f of FIXTURES) {
      const q = new THREE.Quaternion(f.q[1], f.q[2], f.q[3], f.q[0]);
      expect(q.length()).toBeCloseTo(1, 10);
    }
  });
});
