//! Anchor arika's TEME→GCRS rotation against Orekit's authoritative TEME frame.
//!
//! The fixture is generated by `arika/tools/generate_teme_orekit_reference.py`
//! (Orekit via orekit-jpype + jdk4py) and embedded at compile time. Orekit
//! implements an independent, authoritative TEME→GCRF transform, so this test
//! anchors the *composition* (the equation-of-equinoxes sign/order that the
//! ERFA component test cannot pin on its own).
//!
//! arika uses the IAU-76/FK5 reduction and neglects the J2000→GCRS frame bias
//! (< 1 mas), so agreement with Orekit's GCRF is expected only to that level —
//! the tolerance reflects it (and is still ~10⁴× tighter than the SGP4 error
//! this serves).

use arika::epoch::{Epoch, Tt};
use arika::frame::{Gcrs, Rotation, Teme, Vec3};
use serde_json::Value;

const FIXTURE_JSON: &str = include_str!("fixtures/teme_orekit_reference.json");

const J2000_JD: f64 = 2451545.0;
const JULIAN_CENTURY_DAYS: f64 = 36525.0;

/// Tolerance (km) for the TEME→GCRS vector vs Orekit. The ERFA-composed
/// reduction agrees with Orekit to ~0.8 m (the J2000→GCRS frame bias plus
/// model differences); 2 m leaves headroom while still catching a sign/order
/// error (which would be tens of metres or more).
const VECTOR_TOL_KM: f64 = 2e-3;

#[test]
fn teme_gcrs_transform_matches_orekit() {
    let fixture: Value = serde_json::from_str(FIXTURE_JSON).expect("valid fixture JSON");
    let teme_vec = fixture["teme_vec"].as_array().unwrap();
    let teme = Vec3::<Teme>::new(
        teme_vec[0].as_f64().unwrap(),
        teme_vec[1].as_f64().unwrap(),
        teme_vec[2].as_f64().unwrap(),
    );

    for sample in fixture["samples"].as_array().expect("samples array") {
        let t = sample["t"].as_f64().unwrap();
        let jd = J2000_JD + t * JULIAN_CENTURY_DAYS;
        let rot = Rotation::<Teme, Gcrs>::teme_to_gcrs(Epoch::<Tt>::from_jd_tt(jd));
        let got = rot.transform(&teme).into_inner();
        let expected = sample["gcrf_vec"].as_array().unwrap();
        for i in 0..3 {
            assert!(
                (got[i] - expected[i].as_f64().unwrap()).abs() < VECTOR_TOL_KM,
                "TEME→GCRS component {i} at t={t}: {} vs Orekit {}",
                got[i],
                expected[i].as_f64().unwrap()
            );
        }
    }
}
