//! Cross-validate arika's IAU-76/FK5 TEME↔GCRS reduction against ERFA.
//!
//! The fixture is generated by `arika/tools/generate_teme_reference.py`
//! (pyerfa) and embedded at compile time, so CI needs no network or ERFA
//! dependency. It validates the equinox-based components (GMST 1982, equation
//! of the equinoxes, IAU-80 nutation, IAU-80 mean obliquity) to ~1e-11, and the
//! composed `Rotation<Teme, Gcrs>` acting on a vector against ERFA's
//! TEME→J2000.

use arika::earth::fk5;
use arika::epoch::{Epoch, Tt};
use arika::frame::{Gcrs, Rotation, Teme, Vec3};
use serde_json::Value;

const FIXTURE_JSON: &str = include_str!("fixtures/teme_erfa_reference.json");

const J2000_JD: f64 = 2451545.0;
const JULIAN_CENTURY_DAYS: f64 = 36525.0;

/// Scalar component tolerance (rad). arika reproduces ERFA's nut80 / obl80 /
/// eqeq94 to machine precision, so this is dominated by f64 round-off.
const COMPONENT_TOL_RAD: f64 = 1e-11;
/// GMST 1982 tolerance (rad). The large UT1 Julian date (~2.4e6) limits the
/// fractional-second precision, so it is looser than the TT-based components.
const GMST_TOL_RAD: f64 = 1e-9;
/// Composed TEME→J2000 vector tolerance (km). The factory's
/// matrix→quaternion→matrix roundtrip plus the component round-off stays well
/// below a micrometre on the ~7365 km test vector.
const VECTOR_TOL_KM: f64 = 1e-6;

fn f64_at(v: &Value, key: &str) -> f64 {
    v.get(key)
        .and_then(Value::as_f64)
        .unwrap_or_else(|| panic!("missing/non-numeric field {key}"))
}

#[test]
fn teme_gcrs_components_and_transform_match_erfa() {
    let fixture: Value = serde_json::from_str(FIXTURE_JSON).expect("valid fixture JSON");
    let teme_vec = fixture["teme_vec"].as_array().unwrap();
    let teme = Vec3::<Teme>::new(
        teme_vec[0].as_f64().unwrap(),
        teme_vec[1].as_f64().unwrap(),
        teme_vec[2].as_f64().unwrap(),
    );

    for sample in fixture["samples"].as_array().expect("samples array") {
        let t = f64_at(sample, "t");
        let jd = J2000_JD + t * JULIAN_CENTURY_DAYS;

        // ── Scalar components ──
        let (dpsi, deps) = fk5::nutation(t);
        assert!(
            (dpsi - f64_at(&sample["nutation"], "dpsi")).abs() < COMPONENT_TOL_RAD,
            "Δψ at t={t}"
        );
        assert!(
            (deps - f64_at(&sample["nutation"], "deps")).abs() < COMPONENT_TOL_RAD,
            "Δε at t={t}"
        );
        assert!(
            (fk5::mean_obliquity(t) - f64_at(sample, "mean_obliquity")).abs() < COMPONENT_TOL_RAD,
            "ε̄ at t={t}"
        );
        assert!(
            (fk5::equation_of_equinoxes(t) - f64_at(sample, "equation_of_equinoxes")).abs()
                < COMPONENT_TOL_RAD,
            "Eqe at t={t}"
        );
        assert!(
            (fk5::gmst1982(jd) - f64_at(sample, "gmst82")).abs() < GMST_TOL_RAD,
            "GMST82 at t={t}"
        );

        // ── Composed rotation (public factory) vs ERFA TEME→J2000 ──
        let rot = Rotation::<Teme, Gcrs>::teme_to_gcrs(&Epoch::<Tt>::from_jd_tt(jd));

        // On the test vector.
        let got = rot.transform(&teme).into_inner();
        let expected = sample["j2000_vec"].as_array().unwrap();
        for i in 0..3 {
            assert!(
                (got[i] - expected[i].as_f64().unwrap()).abs() < VECTOR_TOL_KM,
                "TEME→J2000 component {i} at t={t}: {} vs {}",
                got[i],
                expected[i].as_f64().unwrap()
            );
        }

        // Full 3×3 matrix: transforming basis vector eⱼ yields column j of the
        // ERFA TEME→J2000 matrix (row-major in the fixture), validating every
        // element — not just one composed direction.
        let m = sample["teme_to_j2000"].as_array().unwrap();
        for j in 0..3 {
            let mut e = Vec3::<Teme>::zeros().into_inner();
            e[j] = 1.0;
            let col = rot.transform(&Vec3::<Teme>::from_raw(e)).into_inner();
            for i in 0..3 {
                let erfa_ij = m[i].as_array().unwrap()[j].as_f64().unwrap();
                assert!(
                    (col[i] - erfa_ij).abs() < 1e-12,
                    "TEME→J2000 matrix [{i}][{j}] at t={t}: {} vs {erfa_ij}",
                    col[i]
                );
            }
        }
    }
}
