// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type PluginMetadata = orts::plugin::types::PluginMetadata;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_metadata_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::metadata(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let orts::plugin::types::PluginMetadata {
                sample_period_s: sample_period_s3,
            } = e;
            *ptr2.add(8).cast::<f64>() = _rt::as_f64(sample_period_s3);
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec4 = (e.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(8 + 1 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(8).cast::<*mut u8>() = ptr4.cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_metadata<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(8).cast::<*mut u8>();
            let l2 = *arg0
                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_current_mode_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::current_mode();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Some(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec2 = (e.into_bytes()).into_boxed_slice();
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            ::core::mem::forget(vec2);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2
                .cast_mut();
        }
        None => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_current_mode<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_run_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::run(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(_) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3
                .cast_mut();
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
pub trait Guest {
    /// メタデータを取得する。config の早期検証を兼ねる。
    /// 不正な config の場合は `Err` を返すこと。
    fn metadata(config: _rt::String) -> Result<PluginMetadata, _rt::String>;
    /// 現在のミッションモード名（detumble / nadir / burn 等）。
    /// モード遷移を持たないコントローラは `none` を返す。
    /// **注意**: `run` が worker thread で store を占有するため、現状
    /// ホストからこの export を並行に呼ぶことはできない。将来対応予定。
    fn current_mode() -> Option<_rt::String>;
    /// ゲストのエントリーポイント。`init` + main loop を一つの関数で。
    /// ホストが `wait-tick` で中断させながら駆動する。
    fn run(config: _rt::String) -> Result<(), _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_plugin_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "metadata")] unsafe extern "C" fn
        export_metadata(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_metadata_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_metadata")] unsafe extern "C" fn
        _post_return_metadata(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_metadata::<$ty > (arg0) } } #[unsafe (export_name =
        "current-mode")] unsafe extern "C" fn export_current_mode() -> * mut u8 { unsafe
        { $($path_to_types)*:: _export_current_mode_cabi::<$ty > () } } #[unsafe
        (export_name = "cabi_post_current-mode")] unsafe extern "C" fn
        _post_return_current_mode(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_current_mode::<$ty > (arg0) } } #[unsafe (export_name = "run")]
        unsafe extern "C" fn export_run(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_run_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_run")] unsafe extern "C" fn _post_return_run(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_run::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_plugin_cabi;
#[repr(align(8))]
struct _RetArea(
    [::core::mem::MaybeUninit<u8>; 8 + 2 * ::core::mem::size_of::<*const u8>()],
);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 8 + 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod orts {
    pub mod plugin {
        /// ホストとゲスト間で交換する物理量プリミティブ。
        ///
        /// 全てのベクトル / クォータニオン / 状態型は orts の規約に従う:
        /// 軌道状態は km / km/s、姿勢は rad / rad/s、磁気モーメントは
        /// A·m²、Hamilton クォータニオン (スカラー先頭)、ECI 基準。
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// 3 成分実数ベクトル（汎用、フレーム未指定）。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Vec3 {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for Vec3 {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Vec3")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// Hamilton クォータニオン、スカラー先頭 `(w, x, y, z)`。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Quat {
                pub w: f64,
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for Quat {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Quat")
                        .field("w", &self.w)
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// ECI 座標系での位置 \[km\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct PositionEciKm {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for PositionEciKm {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PositionEciKm")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// ECI 座標系での速度 \[km/s\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct VelocityEciKms {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for VelocityEciKms {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("VelocityEciKms")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// ECI 座標系での軌道状態。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct OrbitalState {
                pub position: PositionEciKm,
                pub velocity: VelocityEciKms,
            }
            impl ::core::fmt::Debug for OrbitalState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("OrbitalState")
                        .field("position", &self.position)
                        .field("velocity", &self.velocity)
                        .finish()
                }
            }
            /// 剛体姿勢: 姿勢クォータニオン (body→inertial) と
            /// 機体座標系での角速度 \[rad/s\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct AttitudeState {
                pub orientation: Quat,
                pub angular_velocity: Vec3,
            }
            impl ::core::fmt::Debug for AttitudeState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AttitudeState")
                        .field("orientation", &self.orientation)
                        .field("angular-velocity", &self.angular_velocity)
                        .finish()
                }
            }
            /// サンプル tick ごとにプラグインコントローラに渡される宇宙機状態。
            /// ホスト側 `orts::SpacecraftState` と対応。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct SpacecraftState {
                pub orbit: OrbitalState,
                pub attitude: AttitudeState,
                /// 宇宙機質量 \[kg\]。
                pub mass: f64,
            }
            impl ::core::fmt::Debug for SpacecraftState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("SpacecraftState")
                        .field("orbit", &self.orbit)
                        .field("attitude", &self.attitude)
                        .field("mass", &self.mass)
                        .finish()
                }
            }
            /// 天文暦元。Julian Date (JD) として直接シリアライズ。
            /// `arika::epoch::Epoch { jd }` と bit-for-bit 対応。
            ///
            /// **タイムスケール注意**: Phase P1 の `arika::Epoch` は
            /// UTC / TAI / TT を厳密に区別しない。`J2000_JD` 定数は
            /// TT J2000 (`2451545.0`) だが、`from_gregorian(...)` は
            /// うるう秒なしで UTC をそのタイムラインに載せる。
            /// "J2000 からの秒数" が必要なゲストは
            /// `(julian-date - 2451545.0) * 86400.0` を自分で計算すること。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Epoch {
                pub julian_date: f64,
            }
            impl ::core::fmt::Debug for Epoch {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Epoch")
                        .field("julian-date", &self.julian_date)
                        .finish()
                }
            }
            /// tick 時点で評価されたセンサ読み値。
            ///
            /// ホスト側センサモデル (`orts::sensor`) による事前計算結果。
            /// 各フィールドは `option` — 宇宙機にそのセンサがなければ `none`。
            ///
            /// このレコードへのフィールド追加は **Canonical ABI 破壊的変更**。
            /// Phase P1 では host/guest を lockstep で開発するため許容。
            /// サードパーティゲストが出た段階でレイアウトを凍結し、
            /// 新フィールドは新 wit バージョンで追加する。
            /// 機体座標系の磁場 \[T\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct MagneticFieldBody {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for MagneticFieldBody {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("MagneticFieldBody")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// 機体座標系の角速度 \[rad/s\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct AngularVelocityBody {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for AngularVelocityBody {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AngularVelocityBody")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// 姿勢クォータニオン body→inertial (Hamilton scalar-first)。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct AttitudeBodyToInertial {
                pub w: f64,
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for AttitudeBodyToInertial {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AttitudeBodyToInertial")
                        .field("w", &self.w)
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// tick 時点で評価されたセンサ読み値。
            /// フィールド名 = センサ名、型 = 物理量 + 座標系。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Sensors {
                /// 磁力計。任意位置/エポックの磁場が必要なら
                /// `host-env.magnetic-field-eci` を使う。
                pub magnetometer: Option<MagneticFieldBody>,
                /// ジャイロスコープ。
                pub gyroscope: Option<AngularVelocityBody>,
                /// スタートラッカ。
                pub star_tracker: Option<AttitudeBodyToInertial>,
            }
            impl ::core::fmt::Debug for Sensors {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Sensors")
                        .field("magnetometer", &self.magnetometer)
                        .field("gyroscope", &self.gyroscope)
                        .field("star-tracker", &self.star_tracker)
                        .finish()
                }
            }
            /// アクチュエータのテレメトリ（状態フィードバック）。
            ///
            /// RW 角運動量などアクチュエータの現在状態をゲストに提供する。
            /// 各フィールドは `option` — アクチュエータが存在しなければ `none`。
            #[derive(Clone)]
            pub struct ActuatorState {
                /// RW 各ホイールの角運動量 \[N·m·s\]。
                pub rw_momentum: Option<_rt::Vec<f64>>,
            }
            impl ::core::fmt::Debug for ActuatorState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ActuatorState")
                        .field("rw-momentum", &self.rw_momentum)
                        .finish()
                }
            }
            /// `controller.update` に渡される tick ごとの入力。
            /// ホスト側 `orts::plugin::TickInput<'a>` と対応。
            #[derive(Clone)]
            pub struct TickInput {
                /// シミュレーション時刻 \[s\]、コントローラの t=0 からの経過秒。
                pub t: f64,
                /// 宇宙機の真値状態（デバッグ・ログ用）。
                pub spacecraft: SpacecraftState,
                /// 暦元（暦表・磁場モデル等で必要な場合）。
                pub epoch: Option<Epoch>,
                /// センサ読み値。将来ノイズが乗る可能性がある。
                pub sensors: Sensors,
                /// アクチュエータ状態フィードバック。
                pub actuators: ActuatorState,
            }
            impl ::core::fmt::Debug for TickInput {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("TickInput")
                        .field("t", &self.t)
                        .field("spacecraft", &self.spacecraft)
                        .field("epoch", &self.epoch)
                        .field("sensors", &self.sensors)
                        .field("actuators", &self.actuators)
                        .finish()
                }
            }
            /// 機体座標系の磁気ダイポールモーメント指令 \[A·m²\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct CommandedMagneticMoment {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for CommandedMagneticMoment {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CommandedMagneticMoment")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// 機体座標系の RW トルク指令 \[N·m\]。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct CommandedRwTorque {
                pub x: f64,
                pub y: f64,
                pub z: f64,
            }
            impl ::core::fmt::Debug for CommandedRwTorque {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CommandedRwTorque")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .field("z", &self.z)
                        .finish()
                }
            }
            /// コントローラが返す論理アクチュエータ指令。
            ///
            /// Phase P1 は `magnetic-moment` と `rw-torque` を定義。
            /// 後続フェーズで `throttle`, `impulsive-dv` 等を追加。
            /// `None` のフィールドはそのアクチュエータに対するコマンドなし
            /// (前回値が ZOH で保持される)。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Command {
                /// 機体座標系での指令磁気ダイポールモーメント \[A·m²\]。
                pub magnetic_moment: Option<CommandedMagneticMoment>,
                /// RW アセンブリへの指令トルク \[N·m\]、機体座標系。
                /// ホスト側 RW モデルが各ホイール軸への投影を行う。
                pub rw_torque: Option<CommandedRwTorque>,
            }
            impl ::core::fmt::Debug for Command {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Command")
                        .field("magnetic-moment", &self.magnetic_moment)
                        .field("rw-torque", &self.rw_torque)
                        .finish()
                }
            }
            /// プラグインメタデータ（起動時情報）。
            /// ホストが `metadata(config)` で一度だけ問い合わせる。config に依存する
            /// 項目も含むので厳密には静的ではなく「起動時に決まる情報」。
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct PluginMetadata {
                /// 希望サンプル周期 \[s\]。ホストはこれを参考に tick 間隔を決める。
                /// 正の有限値でなければならない。
                pub sample_period_s: f64,
            }
            impl ::core::fmt::Debug for PluginMetadata {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginMetadata")
                        .field("sample-period-s", &self.sample_period_s)
                        .finish()
                }
            }
        }
        /// ゲストがホストに対して呼び出せるサービス（host import）。
        ///
        /// `update` 呼び出し中にゲストがホスト状態にアクセスする唯一の
        /// 合法的な手段。全関数は安価で副作用なし（`log` を除く）であること。
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host_env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type Vec3 = super::super::super::orts::plugin::types::Vec3;
            pub type Epoch = super::super::super::orts::plugin::types::Epoch;
            /// ログレベル。orts 全体で使用する `tracing` crate のレベルと対応。
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum LogLevel {
                Trace,
                Debug,
                Info,
                Warn,
                Error,
            }
            impl ::core::fmt::Debug for LogLevel {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogLevel::Trace => f.debug_tuple("LogLevel::Trace").finish(),
                        LogLevel::Debug => f.debug_tuple("LogLevel::Debug").finish(),
                        LogLevel::Info => f.debug_tuple("LogLevel::Info").finish(),
                        LogLevel::Warn => f.debug_tuple("LogLevel::Warn").finish(),
                        LogLevel::Error => f.debug_tuple("LogLevel::Error").finish(),
                    }
                }
            }
            impl LogLevel {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> LogLevel {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => LogLevel::Trace,
                        1 => LogLevel::Debug,
                        2 => LogLevel::Info,
                        3 => LogLevel::Warn,
                        4 => LogLevel::Error,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// ゲストからログレコードを出力する。
            pub fn log(level: LogLevel, message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "orts:plugin/host-env@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import1(_: i32, _: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(level.clone() as i32, ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// 指定 ECI 位置・エポックでの地磁気ベクトルを ECI 座標系で返す \[T\]。
            ///
            /// 宇宙機の現在位置・姿勢での機体座標系磁場が欲しい場合は
            /// `sensors.magnetometer` を使う方がオーバーヘッドがない。
            /// このインポートは任意位置/エポックの磁場が必要な場合
            /// （予測・計画等）の "escape hatch"。
            ///
            /// Phase P1 では `tobari::magnetic::TiltedDipole` に接続。
            /// Phase D-5 で IGRF 球面調和モデルへ移行予定。
            pub fn magnetic_field_eci(position_eci_km: Vec3, e: Epoch) -> Vec3 {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 24]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 24]);
                    let super::super::super::orts::plugin::types::Vec3 {
                        x: x0,
                        y: y0,
                        z: z0,
                    } = position_eci_km;
                    let super::super::super::orts::plugin::types::Epoch {
                        julian_date: julian_date1,
                    } = e;
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "orts:plugin/host-env@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "magnetic-field-eci"]
                        fn wit_import3(_: f64, _: f64, _: f64, _: f64, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: f64,
                        _: f64,
                        _: f64,
                        _: f64,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(
                            _rt::as_f64(x0),
                            _rt::as_f64(y0),
                            _rt::as_f64(z0),
                            _rt::as_f64(julian_date1),
                            ptr2,
                        )
                    };
                    let l4 = *ptr2.add(0).cast::<f64>();
                    let l5 = *ptr2.add(8).cast::<f64>();
                    let l6 = *ptr2.add(16).cast::<f64>();
                    let result7 = super::super::super::orts::plugin::types::Vec3 {
                        x: l4,
                        y: l5,
                        z: l6,
                    };
                    result7
                }
            }
        }
        /// ホスト-ゲスト間の tick 通信。
        ///
        /// ゲストは `wait-tick` で中断し、ホストが次の tick で再開する。
        /// `send-command` でコマンドをホストに送る。
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod tick_io {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type TickInput = super::super::super::orts::plugin::types::TickInput;
            pub type Command = super::super::super::orts::plugin::types::Command;
            #[allow(unused_unsafe, clippy::all)]
            /// ホストに制御を返し、次の tick まで待つ。
            /// ホスト中断方式: worker thread + blocking channel (サーバ/CLI),
            /// JSPI (ブラウザ)。
            ///
            /// 戻り値が `none` の場合はホストが shutdown を要求していることを示す。
            /// ゲストは `run()` を `Ok(())` で正常終了させること。
            pub fn wait_tick() -> Option<TickInput> {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 256 + 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 256
                            + 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "orts:plugin/tick-io@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "wait-tick"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let result37 = match l2 {
                        0 => None,
                        1 => {
                            let e = {
                                let l3 = *ptr0.add(8).cast::<f64>();
                                let l4 = *ptr0.add(16).cast::<f64>();
                                let l5 = *ptr0.add(24).cast::<f64>();
                                let l6 = *ptr0.add(32).cast::<f64>();
                                let l7 = *ptr0.add(40).cast::<f64>();
                                let l8 = *ptr0.add(48).cast::<f64>();
                                let l9 = *ptr0.add(56).cast::<f64>();
                                let l10 = *ptr0.add(64).cast::<f64>();
                                let l11 = *ptr0.add(72).cast::<f64>();
                                let l12 = *ptr0.add(80).cast::<f64>();
                                let l13 = *ptr0.add(88).cast::<f64>();
                                let l14 = *ptr0.add(96).cast::<f64>();
                                let l15 = *ptr0.add(104).cast::<f64>();
                                let l16 = *ptr0.add(112).cast::<f64>();
                                let l17 = *ptr0.add(120).cast::<f64>();
                                let l18 = i32::from(*ptr0.add(128).cast::<u8>());
                                let l20 = i32::from(*ptr0.add(144).cast::<u8>());
                                let l24 = i32::from(*ptr0.add(176).cast::<u8>());
                                let l28 = i32::from(*ptr0.add(208).cast::<u8>());
                                let l33 = i32::from(*ptr0.add(248).cast::<u8>());
                                super::super::super::orts::plugin::types::TickInput {
                                    t: l3,
                                    spacecraft: super::super::super::orts::plugin::types::SpacecraftState {
                                        orbit: super::super::super::orts::plugin::types::OrbitalState {
                                            position: super::super::super::orts::plugin::types::PositionEciKm {
                                                x: l4,
                                                y: l5,
                                                z: l6,
                                            },
                                            velocity: super::super::super::orts::plugin::types::VelocityEciKms {
                                                x: l7,
                                                y: l8,
                                                z: l9,
                                            },
                                        },
                                        attitude: super::super::super::orts::plugin::types::AttitudeState {
                                            orientation: super::super::super::orts::plugin::types::Quat {
                                                w: l10,
                                                x: l11,
                                                y: l12,
                                                z: l13,
                                            },
                                            angular_velocity: super::super::super::orts::plugin::types::Vec3 {
                                                x: l14,
                                                y: l15,
                                                z: l16,
                                            },
                                        },
                                        mass: l17,
                                    },
                                    epoch: match l18 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l19 = *ptr0.add(136).cast::<f64>();
                                                super::super::super::orts::plugin::types::Epoch {
                                                    julian_date: l19,
                                                }
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    },
                                    sensors: super::super::super::orts::plugin::types::Sensors {
                                        magnetometer: match l20 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l21 = *ptr0.add(152).cast::<f64>();
                                                    let l22 = *ptr0.add(160).cast::<f64>();
                                                    let l23 = *ptr0.add(168).cast::<f64>();
                                                    super::super::super::orts::plugin::types::MagneticFieldBody {
                                                        x: l21,
                                                        y: l22,
                                                        z: l23,
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        gyroscope: match l24 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l25 = *ptr0.add(184).cast::<f64>();
                                                    let l26 = *ptr0.add(192).cast::<f64>();
                                                    let l27 = *ptr0.add(200).cast::<f64>();
                                                    super::super::super::orts::plugin::types::AngularVelocityBody {
                                                        x: l25,
                                                        y: l26,
                                                        z: l27,
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        star_tracker: match l28 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l29 = *ptr0.add(216).cast::<f64>();
                                                    let l30 = *ptr0.add(224).cast::<f64>();
                                                    let l31 = *ptr0.add(232).cast::<f64>();
                                                    let l32 = *ptr0.add(240).cast::<f64>();
                                                    super::super::super::orts::plugin::types::AttitudeBodyToInertial {
                                                        w: l29,
                                                        x: l30,
                                                        y: l31,
                                                        z: l32,
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    },
                                    actuators: super::super::super::orts::plugin::types::ActuatorState {
                                        rw_momentum: match l33 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l34 = *ptr0
                                                        .add(248 + 1 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l35 = *ptr0
                                                        .add(248 + 2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let len36 = l35;
                                                    _rt::Vec::from_raw_parts(l34.cast(), len36, len36)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    },
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result37
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// コマンドをホストに送る。
            /// 1 tick 中に複数回呼んだ場合は最後の値が適用される。
            pub fn send_command(cmd: Command) -> () {
                unsafe {
                    let super::super::super::orts::plugin::types::Command {
                        magnetic_moment: magnetic_moment0,
                        rw_torque: rw_torque0,
                    } = cmd;
                    let (result2_0, result2_1, result2_2, result2_3) = match magnetic_moment0 {
                        Some(e) => {
                            let super::super::super::orts::plugin::types::CommandedMagneticMoment {
                                x: x1,
                                y: y1,
                                z: z1,
                            } = e;
                            (1i32, _rt::as_f64(x1), _rt::as_f64(y1), _rt::as_f64(z1))
                        }
                        None => (0i32, 0.0f64, 0.0f64, 0.0f64),
                    };
                    let (result4_0, result4_1, result4_2, result4_3) = match rw_torque0 {
                        Some(e) => {
                            let super::super::super::orts::plugin::types::CommandedRwTorque {
                                x: x3,
                                y: y3,
                                z: z3,
                            } = e;
                            (1i32, _rt::as_f64(x3), _rt::as_f64(y3), _rt::as_f64(z3))
                        }
                        None => (0i32, 0.0f64, 0.0f64, 0.0f64),
                    };
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "orts:plugin/tick-io@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "send-command"]
                        fn wit_import5(
                            _: i32,
                            _: f64,
                            _: f64,
                            _: f64,
                            _: i32,
                            _: f64,
                            _: f64,
                            _: f64,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import5(
                        _: i32,
                        _: f64,
                        _: f64,
                        _: f64,
                        _: i32,
                        _: f64,
                        _: f64,
                        _: f64,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import5(
                            result2_0,
                            result2_1,
                            result2_2,
                            result2_3,
                            result4_0,
                            result4_1,
                            result4_2,
                            result4_3,
                        )
                    };
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_plugin_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:orts:plugin@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1418] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8d\x0a\x01A\x02\x01\
A\x15\x01B,\x01r\x03\x01xu\x01yu\x01zu\x04\0\x04vec3\x03\0\0\x01r\x04\x01wu\x01x\
u\x01yu\x01zu\x04\0\x04quat\x03\0\x02\x01r\x03\x01xu\x01yu\x01zu\x04\0\x0fpositi\
on-eci-km\x03\0\x04\x01r\x03\x01xu\x01yu\x01zu\x04\0\x10velocity-eci-kms\x03\0\x06\
\x01r\x02\x08position\x05\x08velocity\x07\x04\0\x0dorbital-state\x03\0\x08\x01r\x02\
\x0borientation\x03\x10angular-velocity\x01\x04\0\x0eattitude-state\x03\0\x0a\x01\
r\x03\x05orbit\x09\x08attitude\x0b\x04massu\x04\0\x10spacecraft-state\x03\0\x0c\x01\
r\x01\x0bjulian-dateu\x04\0\x05epoch\x03\0\x0e\x01r\x03\x01xu\x01yu\x01zu\x04\0\x13\
magnetic-field-body\x03\0\x10\x01r\x03\x01xu\x01yu\x01zu\x04\0\x15angular-veloci\
ty-body\x03\0\x12\x01r\x04\x01wu\x01xu\x01yu\x01zu\x04\0\x19attitude-body-to-ine\
rtial\x03\0\x14\x01k\x11\x01k\x13\x01k\x15\x01r\x03\x0cmagnetometer\x16\x09gyros\
cope\x17\x0cstar-tracker\x18\x04\0\x07sensors\x03\0\x19\x01pu\x01k\x1b\x01r\x01\x0b\
rw-momentum\x1c\x04\0\x0eactuator-state\x03\0\x1d\x01k\x0f\x01r\x05\x01tu\x0aspa\
cecraft\x0d\x05epoch\x1f\x07sensors\x1a\x09actuators\x1e\x04\0\x0atick-input\x03\
\0\x20\x01r\x03\x01xu\x01yu\x01zu\x04\0\x19commanded-magnetic-moment\x03\0\"\x01\
r\x03\x01xu\x01yu\x01zu\x04\0\x13commanded-rw-torque\x03\0$\x01k#\x01k%\x01r\x02\
\x0fmagnetic-moment&\x09rw-torque'\x04\0\x07command\x03\0(\x01r\x01\x0fsample-pe\
riod-su\x04\0\x0fplugin-metadata\x03\0*\x03\0\x17orts:plugin/types@0.1.0\x05\0\x02\
\x03\0\0\x0fplugin-metadata\x03\0\x0fplugin-metadata\x03\0\x01\x02\x03\0\0\x04ve\
c3\x02\x03\0\0\x05epoch\x01B\x0a\x02\x03\x02\x01\x03\x04\0\x04vec3\x03\0\0\x02\x03\
\x02\x01\x04\x04\0\x05epoch\x03\0\x02\x01m\x05\x05trace\x05debug\x04info\x04warn\
\x05error\x04\0\x09log-level\x03\0\x04\x01@\x02\x05level\x05\x07messages\x01\0\x04\
\0\x03log\x01\x06\x01@\x02\x0fposition-eci-km\x01\x01e\x03\0\x01\x04\0\x12magnet\
ic-field-eci\x01\x07\x03\0\x1aorts:plugin/host-env@0.1.0\x05\x05\x02\x03\0\0\x0a\
tick-input\x02\x03\0\0\x07command\x01B\x09\x02\x03\x02\x01\x06\x04\0\x0atick-inp\
ut\x03\0\0\x02\x03\x02\x01\x07\x04\0\x07command\x03\0\x02\x01k\x01\x01@\0\0\x04\x04\
\0\x09wait-tick\x01\x05\x01@\x01\x03cmd\x03\x01\0\x04\0\x0csend-command\x01\x06\x03\
\0\x19orts:plugin/tick-io@0.1.0\x05\x08\x01j\x01\x02\x01s\x01@\x01\x06configs\0\x09\
\x04\0\x08metadata\x01\x0a\x01ks\x01@\0\0\x0b\x04\0\x0ccurrent-mode\x01\x0c\x01j\
\0\x01s\x01@\x01\x06configs\0\x0d\x04\0\x03run\x01\x0e\x04\0\x18orts:plugin/plug\
in@0.1.0\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
