//! Oracle tests: validate numerical propagation against Orekit reference.
//!
//! Fixtures generated by `tools/generate_orekit_propagation_fixtures.py` using
//! Orekit's NumericalPropagator (DormandPrince853) with matched force models.
//!
//! **Tier structure**:
//! - Tier 1: Gravity-only (J2, J2+J3+J4) — should agree to cm-level
//! - Tier 2: Gravity + third-body (Sun, Moon) — ephemeris difference dominates
//! - Tier 3: Gravity + SRP — Sun direction error ~0.35°
//! - Tier 4: Gravity + HP drag — geodetic vs spherical altitude difference
//! - Tier 5: Full force model — all differences combined
//!
//! Known difference sources:
//! - **J2 coefficient**: Orekit EGM96 C̄₂₀ → J2 differs by ~3e-9 (negligible)
//! - **Sun position**: Meeus analytical vs DE405 (~0.35°)
//! - **Moon position**: Simplified analytical vs DE405 (~10')
//! - **Altitude model**: Spherical (r - R_earth) vs geodetic (WGS-84)

use kaname::epoch::Epoch;
use nalgebra::Vector3;
use orts_integrator::{DormandPrince, DynamicalSystem, State, Tolerances};
use orts_orbits::constants::{J2_EARTH, J3_EARTH, J4_EARTH, MU_EARTH, R_EARTH};
use orts_orbits::drag::AtmosphericDrag;
use orts_orbits::gravity::{PointMass, ZonalHarmonics};
use orts_orbits::orbital_system::OrbitalSystem;
use orts_orbits::srp::SolarRadiationPressure;
use orts_orbits::third_body::ThirdBodyGravity;
use serde::Deserialize;
use tobari::harris_priester::HarrisPriester;

// ─── Fixture data structures ───

#[derive(Deserialize)]
struct FixtureFile {
    constants: Constants,
    scenarios: Vec<Scenario>,
}

#[derive(Deserialize)]
struct Constants {
    mu_earth_km3_s2: f64,
    r_earth_km: f64,
    j2: f64,
    #[allow(dead_code)]
    j3: f64,
    #[allow(dead_code)]
    j4: f64,
    #[allow(dead_code)]
    mu_sun_km3_s2: f64,
    #[allow(dead_code)]
    mu_moon_km3_s2: f64,
}

#[derive(Deserialize)]
struct Scenario {
    name: String,
    #[allow(dead_code)]
    description: String,
    epoch_utc: String,
    initial_cartesian: InitialCartesian,
    force_model: ForceModelConfig,
    satellite: SatelliteConfig,
    #[allow(dead_code)]
    duration_s: f64,
    trajectory: Vec<TrajectoryPoint>,
    acceleration_at_t0: Option<AccelSnapshot>,
}

#[derive(Deserialize)]
struct InitialCartesian {
    position_km: [f64; 3],
    velocity_km_s: [f64; 3],
}

#[derive(Deserialize)]
struct ForceModelConfig {
    gravity: GravityConfig,
    drag: Option<DragConfig>,
    srp: Option<SrpConfig>,
    third_body_sun: bool,
    third_body_moon: bool,
}

#[derive(Deserialize)]
struct GravityConfig {
    degree: u32,
    #[allow(dead_code)]
    order: u32,
}

#[derive(Deserialize)]
struct DragConfig {
    #[allow(dead_code)]
    model: String,
    n: u32,
}

#[derive(Deserialize)]
struct SrpConfig {
    shadow: bool,
}

#[derive(Deserialize)]
struct SatelliteConfig {
    ballistic_coeff_m2_kg: Option<f64>,
    srp_area_to_mass_m2_kg: Option<f64>,
    srp_cr: Option<f64>,
}

#[derive(Deserialize)]
struct TrajectoryPoint {
    t_seconds: f64,
    position_km: [f64; 3],
    velocity_km_s: [f64; 3],
}

#[derive(Deserialize)]
struct AccelSnapshot {
    total_km_s2: [f64; 3],
}

// ─── Helpers ───

fn load_fixtures() -> FixtureFile {
    let json = include_str!("fixtures/orekit_propagation_reference.json");
    serde_json::from_str(json).expect("Failed to parse Orekit propagation fixture JSON")
}

fn find_scenario<'a>(fixtures: &'a FixtureFile, name: &str) -> &'a Scenario {
    fixtures
        .scenarios
        .iter()
        .find(|s| s.name == name)
        .unwrap_or_else(|| panic!("Scenario '{name}' not found in fixtures"))
}

fn verify_constants(c: &Constants) {
    assert!(
        (c.mu_earth_km3_s2 - MU_EARTH).abs() < 1e-4,
        "μ_Earth mismatch: fixture={}, rust={}",
        c.mu_earth_km3_s2,
        MU_EARTH
    );
    assert!(
        (c.r_earth_km - R_EARTH).abs() < 1e-3,
        "R_Earth mismatch: fixture={}, rust={}",
        c.r_earth_km,
        R_EARTH
    );
    assert!(
        (c.j2 - J2_EARTH).abs() < 1e-8,
        "J2 mismatch: fixture={}, rust={}",
        c.j2,
        J2_EARTH
    );
}

/// Parse ISO 8601 epoch string like "2024-03-20T12:00:00Z" into Epoch.
fn parse_epoch(s: &str) -> Epoch {
    let s = s.trim_end_matches('Z');
    let parts: Vec<&str> = s.split('T').collect();
    let date: Vec<u32> = parts[0].split('-').map(|p| p.parse().unwrap()).collect();
    let time: Vec<&str> = parts[1].split(':').collect();
    let hour: u32 = time[0].parse().unwrap();
    let min: u32 = time[1].parse().unwrap();
    let sec: f64 = time[2].parse().unwrap();
    Epoch::from_gregorian(date[0] as i32, date[1], date[2], hour, min, sec)
}

/// Build OrbitalSystem from fixture scenario configuration.
fn build_system(scenario: &Scenario) -> OrbitalSystem {
    let fm = &scenario.force_model;
    let epoch = parse_epoch(&scenario.epoch_utc);

    // Gravity model
    let gravity: Box<dyn orts_orbits::gravity::GravityField> = match fm.gravity.degree {
        0 => Box::new(PointMass),
        2 => Box::new(ZonalHarmonics {
            r_body: R_EARTH,
            j2: J2_EARTH,
            j3: None,
            j4: None,
        }),
        3 => Box::new(ZonalHarmonics {
            r_body: R_EARTH,
            j2: J2_EARTH,
            j3: Some(J3_EARTH),
            j4: None,
        }),
        d if d >= 4 => Box::new(ZonalHarmonics {
            r_body: R_EARTH,
            j2: J2_EARTH,
            j3: Some(J3_EARTH),
            j4: Some(J4_EARTH),
        }),
        d => panic!("Unsupported gravity degree: {d}"),
    };

    let mut system = OrbitalSystem::new(MU_EARTH, gravity)
        .with_epoch(epoch)
        .with_body_radius(R_EARTH);

    // Third-body perturbations
    if fm.third_body_sun {
        system = system.with_perturbation(Box::new(ThirdBodyGravity::sun()));
    }
    if fm.third_body_moon {
        system = system.with_perturbation(Box::new(ThirdBodyGravity::moon()));
    }

    // SRP
    if let Some(srp_cfg) = &fm.srp {
        let sat = &scenario.satellite;
        let area_to_mass = sat.srp_area_to_mass_m2_kg.unwrap_or(0.02);
        let cr = sat.srp_cr.unwrap_or(1.5);
        let mut srp = SolarRadiationPressure::for_earth(Some(area_to_mass)).with_cr(cr);
        if srp_cfg.shadow {
            srp = srp.with_shadow_body(R_EARTH);
        }
        system = system.with_perturbation(Box::new(srp));
    }

    // Drag
    if let Some(drag_cfg) = &fm.drag {
        let sat = &scenario.satellite;
        let b = sat.ballistic_coeff_m2_kg.unwrap_or(0.01);
        let mut drag = AtmosphericDrag::for_earth(Some(b));
        if drag_cfg.n == 2 {
            drag = drag.with_atmosphere(Box::new(HarrisPriester::new()));
        }
        system = system.with_perturbation(Box::new(drag));
    }

    system
}

/// Comparison result for a scenario.
struct ComparisonResult {
    max_pos_err_km: f64,
    max_vel_err_km_s: f64,
    rms_pos_err_km: f64,
    worst_t: f64,
    n_points: usize,
    accel_err_at_t0: Option<f64>,
}

/// Propagate with DP45 and compare against Orekit trajectory.
fn compare_trajectory(scenario: &Scenario, system: &OrbitalSystem) -> ComparisonResult {
    let ic = &scenario.initial_cartesian;
    let initial = State {
        position: Vector3::new(ic.position_km[0], ic.position_km[1], ic.position_km[2]),
        velocity: Vector3::new(ic.velocity_km_s[0], ic.velocity_km_s[1], ic.velocity_km_s[2]),
    };

    // Tight tolerances to minimize integration error
    let tol = Tolerances {
        atol: 1e-12,
        rtol: 1e-10,
    };

    let dp = DormandPrince;
    let trajectory = &scenario.trajectory;
    let _t_end = trajectory.last().unwrap().t_seconds;

    // Use adaptive stepper, advance to each output time
    let mut stepper = dp.stepper(system, initial.clone(), 0.0, 10.0, tol);

    let mut max_pos_err = 0.0_f64;
    let mut max_vel_err = 0.0_f64;
    let mut sum_pos_err_sq = 0.0_f64;
    let mut worst_t = 0.0_f64;
    let mut n_compared = 0;

    for pt in trajectory.iter().skip(1) {
        // Skip t=0 (initial state is identical)
        let result = stepper.advance_to(
            pt.t_seconds,
            |_, _| {},
            |_, _| std::ops::ControlFlow::<()>::Continue(()),
        );
        match result {
            Ok(_) => {}
            Err(e) => {
                panic!(
                    "Integration error at t={}: {:?}",
                    pt.t_seconds, e
                );
            }
        }

        let our_pos = stepper.state().position;
        let our_vel = stepper.state().velocity;

        let orekit_pos = Vector3::new(pt.position_km[0], pt.position_km[1], pt.position_km[2]);
        let orekit_vel = Vector3::new(
            pt.velocity_km_s[0],
            pt.velocity_km_s[1],
            pt.velocity_km_s[2],
        );

        let pos_err = (our_pos - orekit_pos).magnitude();
        let vel_err = (our_vel - orekit_vel).magnitude();

        sum_pos_err_sq += pos_err * pos_err;
        n_compared += 1;

        if pos_err > max_pos_err {
            max_pos_err = pos_err;
            worst_t = pt.t_seconds;
        }
        if vel_err > max_vel_err {
            max_vel_err = vel_err;
        }
    }

    let rms_pos_err = (sum_pos_err_sq / n_compared as f64).sqrt();

    // Acceleration comparison at t=0
    let accel_err = scenario.acceleration_at_t0.as_ref().map(|accel_snap| {
        let our_deriv = system.derivatives(0.0, &initial);
        let our_accel = our_deriv.acceleration;
        let orekit_accel = Vector3::new(
            accel_snap.total_km_s2[0],
            accel_snap.total_km_s2[1],
            accel_snap.total_km_s2[2],
        );
        (our_accel - orekit_accel).magnitude()
    });

    ComparisonResult {
        max_pos_err_km: max_pos_err,
        max_vel_err_km_s: max_vel_err,
        rms_pos_err_km: rms_pos_err,
        worst_t,
        n_points: n_compared,
        accel_err_at_t0: accel_err,
    }
}

fn run_scenario(name: &str, pos_tol_km: f64) {
    let fixtures = load_fixtures();
    verify_constants(&fixtures.constants);
    let scenario = find_scenario(&fixtures, name);
    let system = build_system(scenario);
    let result = compare_trajectory(scenario, &system);

    let pos_err_m = result.max_pos_err_km * 1000.0;
    let vel_err_m_s = result.max_vel_err_km_s * 1000.0;
    let rms_m = result.rms_pos_err_km * 1000.0;

    eprintln!(
        "{name}: {pts} pts, max_pos={pos_err_m:.3}m (at t={worst_t:.0}s), rms={rms_m:.3}m, max_vel={vel_err_m_s:.6}m/s",
        pts = result.n_points,
        worst_t = result.worst_t,
    );

    if let Some(accel_err) = result.accel_err_at_t0 {
        eprintln!("  accel_err_at_t0 = {accel_err:.6e} km/s²");
    }

    assert!(
        result.max_pos_err_km < pos_tol_km,
        "{name}: max position error {pos_err_m:.3} m exceeds tolerance {tol_m:.1} m",
        tol_m = pos_tol_km * 1000.0,
    );
}

// ─── Tier 1: Gravity-only ───
// Matched constants, J2000 Z-axis; residual from J2 coefficient difference (~3e-9).
// Expected: sub-meter to ~2 m over 10 orbits.

#[test]
fn orekit_j2_iss_3orbits() {
    run_scenario("j2_iss_3orbits", 0.002); // 2 m (measured: 0.6 m)
}

#[test]
fn orekit_j2_sso_10orbits() {
    run_scenario("j2_sso_10orbits", 0.002); // 2 m (measured: 0.6 m)
}

#[test]
fn orekit_j2j3j4_iss_10orbits() {
    run_scenario("j2j3j4_iss_10orbits", 0.005); // 5 m (measured: 2.0 m)
}

#[test]
fn orekit_j2_equatorial_5orbits() {
    run_scenario("j2_equatorial_5orbits", 0.005); // 5 m (measured: 1.7 m)
}

// ─── Tier 2: Gravity + Third-body ───
// Sun: Meeus vs DE405 (~0.35°), Moon: analytical vs DE405 (~10').
// Expected: sub-meter (LEO) to ~100 m (GEO, 3 days).

#[test]
fn orekit_j2_sun_moon_sso_10orbits() {
    run_scenario("j2_sun_moon_sso_10orbits", 0.002); // 2 m (measured: 0.4 m)
}

#[test]
fn orekit_j2_sun_moon_geo_3days() {
    run_scenario("j2_sun_moon_geo_3days", 0.150); // 150 m (measured: 61 m)
}

// ─── Tier 3: Gravity + SRP ───
// Sun direction error ~0.35° affects SRP vector; shadow timing may differ slightly.
// Expected: ~1-2 m over 10 SSO orbits.

#[test]
fn orekit_j2_srp_sso_10orbits() {
    run_scenario("j2_srp_sso_10orbits", 0.005); // 5 m (measured: 1.0 m)
}

// ─── Tier 4: Gravity + HP Drag ───
// Geodetic (Orekit) vs spherical (ours) altitude: up to ~15 km at high lat.
// Equatorial: near-zero alt difference → small drag mismatch.
// ISS 51.6°: ~10-30% density bias at high latitudes → ~1 km along-track.

#[test]
fn orekit_j2_hp_iss_equatorial_5orbits() {
    run_scenario("j2_hp_iss_equatorial_5orbits", 0.020); // 20 m (measured: 7 m)
}

#[test]
fn orekit_j2_hp_iss_10orbits() {
    run_scenario("j2_hp_iss_10orbits", 3.0); // 3 km (measured: 1.3 km)
}

// ─── Tier 5: Full force model ───
// All differences combined. ISS dominated by drag; SSO by drag+SRP.

#[test]
fn orekit_full_iss_10orbits() {
    run_scenario("full_iss_10orbits", 3.0); // 3 km (measured: 1.3 km)
}

#[test]
fn orekit_full_sso_10orbits() {
    run_scenario("full_sso_10orbits", 0.050); // 50 m (measured: 14 m)
}
