//! Oracle tests: validate Harris-Priester against Orekit reference.
//!
//! Fixtures generated by `tools/generate_hp_fixtures.py` using Orekit's
//! HarrisPriester model with matching parameters (same Montenbruck & Gill table,
//! same formula, same 30° lag angle).
//!
//! Known difference sources:
//! - **Sun position**: Meeus analytical (~1 arcmin) vs Orekit DE405 ephemeris.
//!   This rotates the bulge apex slightly, causing density differences especially
//!   at the day-night boundary (ψ ≈ 90°).
//! - **Altitude model**: Our code uses spherical altitude (r - R_earth), Orekit
//!   uses geodetic altitude (WGS-84 ellipsoid). At the equator these are equal;
//!   off-equator the difference is up to ~21 km (at the poles).
//! - **Table & interpolation**: Identical data and scale-height formula — no
//!   expected difference from this source.

use arika::epoch::Epoch;
use nalgebra::Vector3;
use serde::Deserialize;
use tobari::{AtmosphereModel, HarrisPriester};

// ─── Fixture data structures ───

#[derive(Deserialize)]
struct FixtureFile {
    equatorial_n2: Vec<EquatorialPoint>,
    equatorial_n6: Vec<EquatorialPoint>,
    off_equator: Vec<OffEquatorPoint>,
    sun_direction_comparison: Vec<SunDirection>,
}

#[derive(Deserialize)]
struct EquatorialPoint {
    epoch: String,
    altitude_km: f64,
    position_km: [f64; 3],
    #[allow(dead_code)]
    angle_deg: f64,
    density_kg_m3: f64,
    n: u32,
}

#[derive(Deserialize)]
struct OffEquatorPoint {
    altitude_km_spherical: f64,
    altitude_km_geodetic: f64,
    latitude_deg: f64,
    position_km: [f64; 3],
    density_kg_m3: f64,
}

#[derive(Deserialize)]
struct SunDirection {
    epoch: String,
    sun_direction_eci: [f64; 3],
}

// ─── Helpers ───

fn load_fixtures() -> FixtureFile {
    let json = include_str!("fixtures/hp_orekit_reference.json");
    serde_json::from_str(json).expect("Failed to parse HP fixture JSON")
}

/// Parse ISO 8601 epoch string like "2024-03-20T12:00:00Z" into Epoch.
fn parse_epoch(s: &str) -> Epoch {
    let s = s.trim_end_matches('Z');
    let parts: Vec<&str> = s.split('T').collect();
    let date: Vec<u32> = parts[0].split('-').map(|p| p.parse().unwrap()).collect();
    let time: Vec<&str> = parts[1].split(':').collect();
    let hour: u32 = time[0].parse().unwrap();
    let min: u32 = time[1].parse().unwrap();
    let sec: f64 = time[2].parse().unwrap();
    Epoch::from_gregorian(date[0] as i32, date[1], date[2], hour, min, sec)
}

// ─── Tests ───

/// Test 1: All 480 equatorial n=2 points against Orekit.
///
/// Equatorial positions (z=0) eliminate the geodetic/spherical altitude difference.
/// Remaining difference is from Sun position (Meeus vs DE405/430 ephemeris,
/// ~0.3° angular separation). Tolerance: 5% relative error.
#[test]
fn hp_equatorial_density_vs_orekit() {
    let fixtures = load_fixtures();
    let hp = HarrisPriester::new(); // n=2, lag=30°

    let mut max_rel_err = 0.0_f64;
    let mut sum_rel_err = 0.0_f64;
    let mut worst_alt = 0.0_f64;
    let mut worst_epoch = String::new();
    let mut count = 0;

    for pt in &fixtures.equatorial_n2 {
        let epoch = parse_epoch(&pt.epoch);
        let pos = arika::SimpleEci::new(pt.position_km[0], pt.position_km[1], pt.position_km[2]);

        let our_density = hp.density(pt.altitude_km, &pos, Some(&epoch));
        let orekit_density = pt.density_kg_m3;

        // Skip points where both densities are essentially zero (boundary)
        if orekit_density.abs() < 1e-20 {
            continue;
        }

        let rel_err = (our_density - orekit_density).abs() / orekit_density;
        sum_rel_err += rel_err;
        count += 1;

        if rel_err > max_rel_err {
            max_rel_err = rel_err;
            worst_alt = pt.altitude_km;
            worst_epoch = pt.epoch.clone();
        }

        assert!(
            rel_err < 0.05,
            "Equatorial n=2: {:.1}% error at alt={} km, epoch={}, angle={}°\n\
             ours={:.4e}, orekit={:.4e}",
            rel_err * 100.0,
            pt.altitude_km,
            pt.epoch,
            pt.angle_deg,
            our_density,
            orekit_density,
        );
    }

    let mean_rel_err = sum_rel_err / count as f64;
    eprintln!(
        "HP equatorial n=2: {count} points, max_err={:.2}% (at {worst_alt} km, {worst_epoch}), mean_err={:.3}%",
        max_rel_err * 100.0,
        mean_rel_err * 100.0,
    );
}

/// Test 2: Apex and anti-apex points should have very tight agreement.
///
/// At the bulge apex (ψ≈0, cos^n≈1) density ≈ rho_max regardless of small
/// Sun direction differences. Similarly at anti-apex (ψ≈180, cos^n≈0) density ≈ rho_min.
/// These points are least sensitive to Sun position errors.
#[test]
fn hp_apex_antapex_tight() {
    let fixtures = load_fixtures();
    let hp = HarrisPriester::new();

    let mut max_rel_err = 0.0_f64;
    let mut count = 0;

    for pt in &fixtures.equatorial_n2 {
        // Find points that are near the rho_max or rho_min bounds
        // by checking if density is within 5% of a table boundary
        let epoch = parse_epoch(&pt.epoch);
        let pos = arika::SimpleEci::new(pt.position_km[0], pt.position_km[1], pt.position_km[2]);

        let our_density = hp.density(pt.altitude_km, &pos, Some(&epoch));
        let orekit_density = pt.density_kg_m3;

        if orekit_density.abs() < 1e-20 {
            continue;
        }

        let rel_err = (our_density - orekit_density).abs() / orekit_density;

        // Only check points with very low relative error (near apex/anti-apex)
        // These are the ones where both implementations should agree tightly
        if rel_err < 0.01 {
            count += 1;
            if rel_err > max_rel_err {
                max_rel_err = rel_err;
            }
        }
    }

    eprintln!(
        "HP apex/anti-apex: {count} points with <1% error, max={:.4}%",
        max_rel_err * 100.0,
    );
    // We expect a significant number of points to have tight agreement
    assert!(
        count > 50,
        "Expected >50 tight-agreement points, got {count}"
    );
}

/// Test 3: n=6 equatorial points against Orekit.
///
/// Higher exponent produces sharper density bulge. The cos^6 falloff
/// amplifies Sun direction differences, so tolerance is slightly wider.
#[test]
fn hp_exponent_n6_vs_orekit() {
    let fixtures = load_fixtures();
    let hp = HarrisPriester::new().with_exponent(6);

    let mut max_rel_err = 0.0_f64;
    let mut count = 0;

    for pt in &fixtures.equatorial_n6 {
        assert_eq!(pt.n, 6);

        let epoch = parse_epoch(&pt.epoch);
        let pos = arika::SimpleEci::new(pt.position_km[0], pt.position_km[1], pt.position_km[2]);

        let our_density = hp.density(pt.altitude_km, &pos, Some(&epoch));
        let orekit_density = pt.density_kg_m3;

        if orekit_density.abs() < 1e-20 {
            continue;
        }

        let rel_err = (our_density - orekit_density).abs() / orekit_density;
        count += 1;

        if rel_err > max_rel_err {
            max_rel_err = rel_err;
        }

        assert!(
            rel_err < 0.10,
            "Equatorial n=6: {:.1}% error at alt={} km, angle={}°\n\
             ours={:.4e}, orekit={:.4e}",
            rel_err * 100.0,
            pt.altitude_km,
            pt.angle_deg,
            our_density,
            orekit_density,
        );
    }

    eprintln!(
        "HP equatorial n=6: {count} points, max_err={:.2}%",
        max_rel_err * 100.0,
    );
}

/// Test 4: Sun direction agreement between Meeus and Orekit DE405.
///
/// Our Meeus low-precision formula has ~0.3° accuracy vs Orekit's DE405/430
/// ephemeris. This test documents the actual difference at each epoch and
/// verifies it stays below 0.5° (the error budget for density tolerance).
#[test]
fn hp_sun_direction_vs_orekit() {
    let fixtures = load_fixtures();

    let mut max_sep = 0.0_f64;

    for sun_pt in &fixtures.sun_direction_comparison {
        let epoch = parse_epoch(&sun_pt.epoch);

        // Our Meeus Sun direction
        let our_dir = arika::sun::sun_direction_eci(&epoch).into_inner();

        let orekit_dir = Vector3::new(
            sun_pt.sun_direction_eci[0],
            sun_pt.sun_direction_eci[1],
            sun_pt.sun_direction_eci[2],
        );

        // Angular separation
        let cos_angle = our_dir.dot(&orekit_dir).clamp(-1.0, 1.0);
        let angle_deg = cos_angle.acos().to_degrees();

        if angle_deg > max_sep {
            max_sep = angle_deg;
        }

        eprintln!(
            "Sun direction at {}: angular separation = {:.4}°\n\
             \tours=({:.6}, {:.6}, {:.6})\n\
             \torekit=({:.6}, {:.6}, {:.6})",
            sun_pt.epoch,
            angle_deg,
            our_dir.x,
            our_dir.y,
            our_dir.z,
            orekit_dir.x,
            orekit_dir.y,
            orekit_dir.z,
        );

        assert!(
            angle_deg < 0.5,
            "Sun direction at {}: {:.4}° separation exceeds 0.5° tolerance",
            sun_pt.epoch,
            angle_deg,
        );
    }

    eprintln!("Max Sun direction separation: {:.4}°", max_sep);
}

/// Test 5: Off-equator points document the geodetic vs spherical altitude effect.
///
/// This is an informational test — it reports the density ratio between our
/// implementation (spherical altitude) and Orekit (geodetic altitude) at
/// non-zero latitudes. At the equator they should agree; at high latitudes
/// the geodetic altitude is higher, producing lower Orekit density.
#[test]
fn hp_off_equator_documents_geodetic_diff() {
    let fixtures = load_fixtures();
    let hp = HarrisPriester::new();

    eprintln!("Off-equator geodetic vs spherical altitude effect:");
    eprintln!(
        "{:>8} {:>6} {:>10} {:>10} {:>12} {:>12} {:>8}",
        "alt_sph", "lat", "alt_geo", "alt_diff", "our_rho", "orekit_rho", "ratio"
    );

    for pt in &fixtures.off_equator {
        let epoch = parse_epoch("2024-03-20T12:00:00Z");
        let pos = arika::SimpleEci::new(pt.position_km[0], pt.position_km[1], pt.position_km[2]);

        let our_density = hp.density(pt.altitude_km_spherical, &pos, Some(&epoch));
        let orekit_density = pt.density_kg_m3;

        let ratio = if orekit_density > 0.0 {
            our_density / orekit_density
        } else {
            f64::NAN
        };

        let alt_diff = pt.altitude_km_geodetic - pt.altitude_km_spherical;

        eprintln!(
            "{:>7.0}km {:>5.0}° {:>9.1}km {:>9.1}km {:>12.4e} {:>12.4e} {:>7.2}x",
            pt.altitude_km_spherical,
            pt.latitude_deg,
            pt.altitude_km_geodetic,
            alt_diff,
            our_density,
            orekit_density,
            ratio,
        );

        // At equator (lat=0), geodetic ≈ spherical → tight agreement
        if pt.latitude_deg == 0.0 && orekit_density > 0.0 {
            let rel_err = (our_density - orekit_density).abs() / orekit_density;
            assert!(
                rel_err < 0.05,
                "Equatorial off-equator point: {:.1}% error at alt={:.0} km",
                rel_err * 100.0,
                pt.altitude_km_spherical,
            );
        }
    }
}

/// Test 6: Seasonal density variation range is consistent between implementations.
///
/// At a fixed position and altitude, the density varies across epochs
/// as the Sun moves. The exact ordering can swap for closely-spaced values
/// due to ~0.3° Sun direction difference. Instead, we verify that the
/// *range* (max/min ratio) of seasonal variation is similar (within 50%).
#[test]
fn hp_seasonal_variation_range() {
    let fixtures = load_fixtures();
    let hp = HarrisPriester::new();

    let altitudes = [200.0, 400.0, 600.0, 800.0];
    let angles = [0.0, 90.0, 180.0, 270.0];

    for &alt in &altitudes {
        for &angle in &angles {
            let pts: Vec<&EquatorialPoint> = fixtures
                .equatorial_n2
                .iter()
                .filter(|p| (p.altitude_km - alt).abs() < 0.1 && (p.angle_deg - angle).abs() < 0.1)
                .collect();

            if pts.len() < 4 {
                continue;
            }

            let mut our_densities = Vec::new();
            let mut orekit_densities = Vec::new();

            for pt in &pts {
                let epoch = parse_epoch(&pt.epoch);
                let pos =
                    arika::SimpleEci::new(pt.position_km[0], pt.position_km[1], pt.position_km[2]);
                our_densities.push(hp.density(pt.altitude_km, &pos, Some(&epoch)));
                orekit_densities.push(pt.density_kg_m3);
            }

            let our_max = our_densities
                .iter()
                .cloned()
                .fold(f64::NEG_INFINITY, f64::max);
            let our_min = our_densities.iter().cloned().fold(f64::INFINITY, f64::min);
            let orekit_max = orekit_densities
                .iter()
                .cloned()
                .fold(f64::NEG_INFINITY, f64::max);
            let orekit_min = orekit_densities
                .iter()
                .cloned()
                .fold(f64::INFINITY, f64::min);

            // Compare max/min ratio (diurnal + seasonal range)
            if our_min > 0.0 && orekit_min > 0.0 {
                let our_ratio = our_max / our_min;
                let orekit_ratio = orekit_max / orekit_min;

                let ratio_diff = (our_ratio - orekit_ratio).abs() / orekit_ratio;
                assert!(
                    ratio_diff < 0.50,
                    "Seasonal range mismatch at alt={alt} km, angle={angle}°:\n\
                     ours: max/min = {our_ratio:.4} ({our_min:.4e} .. {our_max:.4e})\n\
                     orekit: max/min = {orekit_ratio:.4} ({orekit_min:.4e} .. {orekit_max:.4e})\n\
                     ratio_diff = {ratio_diff:.1}%",
                );
            }
        }
    }
}
