//! Oracle tests: validate `tobari::magnetic::Igrf` against ppigrf.
//!
//! ppigrf is published by IAGA Working Group V-MOD, the body that produces the
//! IGRF coefficients themselves, so it is an independent implementation of the
//! same model rather than a restatement of our own logic. That is what makes it
//! usable to pin the parts of the spherical-harmonic evaluation that a
//! self-consistency check cannot: the absolute scale of the Schmidt
//! semi-normalized Legendre functions, and the sign of each field component.
//!
//! Both implementations share the published IGRF-14 Gauss coefficients and
//! linear interpolation between the 5-year main-field epochs.
//!
//! Known difference sources:
//! - **Coefficient provenance**: ppigrf ships its own copy of the coefficient
//!   file; ours is generated by `tobari/build.rs`. A future IGRF generation
//!   landing in one before the other changes the expansion differently per
//!   latitude, longitude, altitude and component, so it shows up as a
//!   systematic but spatially varying disagreement rather than one offset.
//! - **Geodetic-to-geocentric conversion**: both take geodetic latitude and
//!   height, but the internal conversion to spherical coordinates uses each
//!   implementation's own WGS-84 constants, so a fractional-arcsecond
//!   difference in colatitude is possible.
//!
//! Not covered: the exact geographic poles. ppigrf divides by `sin(theta)`
//! without a limit branch and returns NaN there, so it cannot be a reference at
//! those points — `evaluate_sh`'s `sin_theta <= 1e-10` branch is pinned instead
//! by `b_phi_pole_branch_is_continuous` in the crate's own tests. The fixture
//! reaches 89.99 deg, where both implementations use the ordinary
//! `P^m_n / sin(theta)` path and that ratio is already large.
//!
//! Fixtures generated by `tools/generate_igrf_fixtures.py`.

use std::collections::BTreeMap;

use arika::earth::geodetic::Geodetic;
use arika::epoch::Epoch;
use serde::Deserialize;
use tobari::magnetic::{Igrf, MagneticFieldInput, MagneticFieldModel};

#[derive(Deserialize)]
struct FixtureFile {
    points: Vec<Point>,
}

#[derive(Deserialize)]
struct Point {
    label: String,
    epoch: String,
    longitude_deg: f64,
    latitude_deg: f64,
    height_km: f64,
    b_east_nt: f64,
    b_north_nt: f64,
    b_up_nt: f64,
}

fn load() -> FixtureFile {
    let raw = include_str!("fixtures/igrf_ppigrf_reference.json");
    serde_json::from_str(raw).expect("fixture parses")
}

/// Rotate an ECEF vector into the local geodetic east/north/up frame, so the
/// comparison happens in the same basis the reference reports.
fn ecef_to_enu(b_ecef: [f64; 3], lat_deg: f64, lon_deg: f64) -> (f64, f64, f64) {
    let (lat, lon) = (lat_deg.to_radians(), lon_deg.to_radians());
    let (sl, cl) = (lat.sin(), lat.cos());
    let (so, co) = (lon.sin(), lon.cos());
    let [x, y, z] = b_ecef;
    let east = -so * x + co * y;
    let north = -sl * co * x - sl * so * y + cl * z;
    let up = cl * co * x + cl * so * y + sl * z;
    (east, north, up)
}

fn evaluate(p: &Point) -> (f64, f64, f64) {
    let epoch = Epoch::from_iso8601(&p.epoch).expect("fixture epoch parses");
    let geodetic = Geodetic {
        latitude: p.latitude_deg.to_radians(),
        longitude: p.longitude_deg.to_radians(),
        altitude: p.height_km,
    };
    let input = MagneticFieldInput {
        geodetic,
        utc: &epoch,
    };
    // tobari returns tesla; the fixture is in nT.
    let b = Igrf::earth().field_ecef(&input);
    let b_nt = [b[0] * 1e9, b[1] * 1e9, b[2] * 1e9];
    ecef_to_enu(b_nt, p.latitude_deg, p.longitude_deg)
}

/// Every component, at every fixture point, agreeing with the reference to
/// within 1% **of the total field magnitude** — that is,
/// `|got - want| / |B| < 0.01`, not `|got - want| / |component|`. Scaling by
/// `|B|` is deliberate: a component that passes near zero at a given point
/// would otherwise demand absurd relative precision there.
///
/// A component-wise check is the point: comparing `|B|` alone would pass with
/// the eastward component inverted, and would pass with the intermediate-order
/// Legendre functions mis-scaled at any point where those orders happen to
/// cancel.
#[test]
fn igrf_components_match_ppigrf() {
    let fixture = load();
    // Pin the intended time-regime coverage. Checking only for non-emptiness
    // would let a regeneration silently drop the interpolation or
    // secular-variation epoch and still pass, weakening the oracle without
    // any test failing.
    let mut per_epoch: BTreeMap<&str, usize> = BTreeMap::new();
    for p in &fixture.points {
        *per_epoch.entry(p.epoch.as_str()).or_default() += 1;
    }
    // BTreeMap keys come out sorted, so the expected list is sorted too.
    assert_eq!(
        per_epoch.keys().copied().collect::<Vec<_>>(),
        [
            // inside an interpolation interval
            "2022-07-01T00:00:00Z",
            // exact main-field epoch
            "2025-01-01T00:00:00Z",
            // secular-variation extrapolation range
            "2027-04-15T00:00:00Z",
        ],
        "fixture must cover an exact epoch, an interpolation interval, and the \
         secular-variation range"
    );
    for (epoch, count) in &per_epoch {
        assert_eq!(
            *count, 17,
            "epoch {epoch} has {count} points, expected all 17 query locations"
        );
    }

    let mut worst = (0.0_f64, String::new());
    for p in &fixture.points {
        let (east, north, up) = evaluate(p);
        let scale = (p.b_east_nt.powi(2) + p.b_north_nt.powi(2) + p.b_up_nt.powi(2)).sqrt();
        for (name, got, want) in [
            ("east", east, p.b_east_nt),
            ("north", north, p.b_north_nt),
            ("up", up, p.b_up_nt),
        ] {
            // Scale the tolerance by |B| rather than by the component: a
            // component that is near zero at a given point would otherwise
            // demand absurd relative precision.
            let rel = (got - want).abs() / scale;
            if rel > worst.0 {
                worst = (rel, format!("{} {} @ {}", p.label, name, p.epoch));
            }
            assert!(
                rel < 0.01,
                "{} {} @ {}: got {got:.1} nT, ppigrf {want:.1} nT \
                 (|B| = {scale:.1} nT, relative {:.4})",
                p.label,
                name,
                p.epoch,
                rel
            );
        }
    }
    println!(
        "worst component disagreement: {:.5} of |B| at {}",
        worst.0, worst.1
    );
}

/// The eastward component carries its own sign convention, and a dedicated
/// check makes a future inversion fail here rather than only in a downstream
/// attitude-control test.
#[test]
fn igrf_eastward_component_sign_matches_ppigrf() {
    let fixture = load();
    let mut checked = 0;
    for p in &fixture.points {
        // Skip points where the reference eastward component is small compared
        // with the field: there the sign is not a meaningful assertion.
        let scale = (p.b_east_nt.powi(2) + p.b_north_nt.powi(2) + p.b_up_nt.powi(2)).sqrt();
        if p.b_east_nt.abs() < 0.02 * scale {
            continue;
        }
        let (east, _, _) = evaluate(p);
        assert!(
            east.signum() == p.b_east_nt.signum(),
            "{} @ {}: eastward sign differs — got {east:.1} nT, ppigrf {:.1} nT",
            p.label,
            p.epoch,
            p.b_east_nt
        );
        checked += 1;
    }
    assert!(
        checked >= 10,
        "expected a meaningful number of points with a significant eastward \
         component, got {checked}"
    );
}
