//! Cross-validation of IAU rotation model against Orekit reference data.
//!
//! Fixtures generated by: `uv run tools/generate_iau_rotation_fixtures.py`
//! Reference: Orekit's IAUPole / body-oriented frame (body-fixed → EME2000).

use kaname::epoch::Epoch;
use kaname::rotation;
use nalgebra::{Quaternion, UnitQuaternion, Vector3};

/// Load and parse the Orekit fixture file.
fn load_fixtures() -> Vec<Fixture> {
    let json_str = include_str!("fixtures/iau_rotation_orekit_reference.json");
    let data: serde_json::Value = serde_json::from_str(json_str).unwrap();
    data["fixtures"]
        .as_array()
        .unwrap()
        .iter()
        .map(|f| Fixture {
            body: f["body"].as_str().unwrap().to_string(),
            label: f["label"].as_str().unwrap().to_string(),
            jd: f["jd"].as_f64().unwrap(),
            q: {
                let arr = f["quaternion_wxyz"].as_array().unwrap();
                [
                    arr[0].as_f64().unwrap(),
                    arr[1].as_f64().unwrap(),
                    arr[2].as_f64().unwrap(),
                    arr[3].as_f64().unwrap(),
                ]
            },
        })
        .collect()
}

struct Fixture {
    body: String,
    label: String,
    jd: f64,
    q: [f64; 4], // [w, x, y, z]
}

/// Compute the angular distance between two unit quaternions [degrees].
/// Handles sign ambiguity (q and -q represent the same rotation).
fn quaternion_angle_deg(a: &UnitQuaternion<f64>, b: &UnitQuaternion<f64>) -> f64 {
    let dot = a.as_ref().coords.dot(&b.as_ref().coords).abs();
    let clamped = dot.min(1.0);
    2.0 * clamped.acos().to_degrees()
}

#[test]
fn orekit_cross_validation() {
    let fixtures = load_fixtures();

    // Tolerance: rotation angle difference in degrees.
    // Earth uses a different rotation model (GMST vs IAU), so wider tolerance.
    let tolerance_deg = |body: &str| -> f64 {
        match body {
            // Our Earth IAU model includes precession terms; Orekit uses
            // a more precise IERS-based model. The W rate also differs slightly.
            "earth" => 2.0,
            // Moon, Mars, Sun should match closely (same IAU 2009 source).
            // Orekit may include additional periodic terms we don't have.
            _ => 0.5,
        }
    };

    let mut pass_count = 0;
    let mut fail_count = 0;

    for f in &fixtures {
        let epoch = Epoch::from_jd(f.jd);
        let our_q = match rotation::body_orientation(&f.body, &epoch) {
            Some(q) => q,
            None => {
                eprintln!("  SKIP {}: {} (no model)", f.body, f.label);
                continue;
            }
        };

        // Orekit returns ECI→body transform; conjugate to get body→ECI
        // (Orekit's getTransformTo(eci) gives the passive rotation from
        // body-fixed frame to ECI, which is the inverse of our convention.)
        let orekit_q = UnitQuaternion::from_quaternion(Quaternion::new(
            f.q[0], f.q[1], f.q[2], f.q[3],
        ))
        .conjugate();

        let angle = quaternion_angle_deg(&our_q, &orekit_q);
        let tol = tolerance_deg(&f.body);

        if angle > tol {
            eprintln!(
                "  FAIL {}: {} — angle={:.4}° (tolerance={tol}°)",
                f.body, f.label, angle
            );
            eprintln!(
                "    ours:   [{:.8}, {:.8}, {:.8}, {:.8}]",
                our_q.w, our_q.i, our_q.j, our_q.k
            );
            eprintln!(
                "    orekit: [{:.8}, {:.8}, {:.8}, {:.8}]",
                f.q[0], f.q[1], f.q[2], f.q[3]
            );
            fail_count += 1;
        } else {
            eprintln!(
                "  PASS {}: {} — angle={:.4}°",
                f.body, f.label, angle
            );
            pass_count += 1;
        }
    }

    eprintln!("\n{pass_count} passed, {fail_count} failed");
    assert_eq!(fail_count, 0, "{fail_count} fixtures exceeded tolerance");
    // Ensure we tested a meaningful number of fixtures.
    // If the fixture file shrinks (e.g., generator silently drops epochs),
    // this catches the regression.
    assert!(
        pass_count >= 19,
        "expected at least 19 fixtures, only {pass_count} passed"
    );
}

/// Verify that our pole direction matches Orekit's pole.
#[test]
fn orekit_pole_direction() {
    let json_str = include_str!("fixtures/iau_rotation_orekit_reference.json");
    let data: serde_json::Value = serde_json::from_str(json_str).unwrap();

    for f in data["fixtures"].as_array().unwrap() {
        let body = f["body"].as_str().unwrap();
        let label = f["label"].as_str().unwrap();
        let jd = f["jd"].as_f64().unwrap();

        // Skip Earth (different model) and bodies without pole data
        if body == "earth" {
            continue;
        }

        let orekit_pole: Vec<f64> = f["pole_eci"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();
        let orekit_pole = Vector3::new(orekit_pole[0], orekit_pole[1], orekit_pole[2]);

        let epoch = Epoch::from_jd(jd);
        let our_q = match rotation::body_orientation(body, &epoch) {
            Some(q) => q,
            None => continue,
        };
        let our_pole = our_q * Vector3::z();

        let angle = our_pole.angle(&orekit_pole).to_degrees();
        assert!(
            angle < 0.5,
            "{body} @ {label}: pole direction differs by {angle:.4}° (expected < 0.5°)"
        );
    }
}
