//! IGRF-14 spherical harmonic magnetic field model.

use arika::earth::ellipsoid::{WGS84_A, WGS84_E2};
use arika::epoch::Epoch;

mod coeff;

use super::{MagneticFieldInput, MagneticFieldModel};
#[allow(unused_imports)]
use crate::math::F64Ext;
use coeff::*;

/// Fixed-size array type for IGRF Gauss coefficients.
///
/// Size = `N_COEFFS` = Σ_{n=1}^{IGRF_MAX_DEGREE} (n + 1), currently 104
/// for degree 13. This is determined by the IGRF standard; if a future
/// IGRF generation changes the maximum degree, `N_COEFFS` (generated by
/// build.rs) will update and this alias will follow.
pub type IgrfCoeffArray = [f64; N_COEFFS];

/// Gauss coefficient set for a single epoch.
#[derive(Clone)]
pub struct GaussCoefficients {
    /// g coefficients \[nT\], flat-indexed by `coeff_index(n, m)`.
    pub g: IgrfCoeffArray,
    /// h coefficients \[nT\], flat-indexed by `coeff_index(n, m)`.
    pub h: IgrfCoeffArray,
    /// Epoch year for this coefficient set.
    pub year: f64,
}

/// IGRF (International Geomagnetic Reference Field) model.
///
/// Evaluates the geomagnetic field using spherical harmonic expansion.
///
/// By default uses built-in IGRF-14 Gauss coefficients (2020 DGRF + 2025 IGRF + SV).
/// Custom coefficients can be injected at runtime via [`Igrf::from_coefficients`].
pub struct Igrf {
    max_degree: usize,
    /// Custom coefficient overrides. When `None`, uses built-in IGRF-14.
    custom_coeffs: Option<CustomCoeffs>,
}

struct CustomCoeffs {
    epoch_a: GaussCoefficients,
    epoch_b: GaussCoefficients,
    /// Secular variation \[nT/yr\] for extrapolation beyond epoch_b.
    sv_g: IgrfCoeffArray,
    sv_h: IgrfCoeffArray,
}

impl Igrf {
    /// Create an IGRF model with built-in IGRF-14 coefficients (degree 13).
    pub fn earth() -> Self {
        Self {
            max_degree: IGRF_MAX_DEGREE,
            custom_coeffs: None,
        }
    }

    /// Create an IGRF model truncated to the given maximum degree.
    ///
    /// Lower degrees are faster but less accurate. Degree 1 gives a dipole.
    ///
    /// # Panics
    /// Panics if `max_degree` is 0 or exceeds [`IGRF_MAX_DEGREE`].
    pub fn with_max_degree(max_degree: usize) -> Self {
        assert!(
            (1..=IGRF_MAX_DEGREE).contains(&max_degree),
            "max_degree must be in 1..={IGRF_MAX_DEGREE}, got {max_degree}"
        );
        Self {
            max_degree,
            custom_coeffs: None,
        }
    }

    /// Create an IGRF model with custom coefficient data injected at runtime.
    ///
    /// This allows using coefficient sets from different IGRF generations,
    /// or coefficients downloaded/parsed externally.
    ///
    /// `epoch_a` and `epoch_b` define the two bracketing epochs for interpolation.
    /// `sv` contains the secular variation for extrapolation beyond `epoch_b`.
    pub fn from_coefficients(
        epoch_a: GaussCoefficients,
        epoch_b: GaussCoefficients,
        sv: GaussCoefficients,
        max_degree: usize,
    ) -> Self {
        assert!(
            (1..=IGRF_MAX_DEGREE).contains(&max_degree),
            "max_degree must be in 1..={IGRF_MAX_DEGREE}, got {max_degree}"
        );
        Self {
            max_degree,
            custom_coeffs: Some(CustomCoeffs {
                epoch_a,
                epoch_b,
                sv_g: sv.g,
                sv_h: sv.h,
            }),
        }
    }
}

impl MagneticFieldModel for Igrf {
    fn field_ecef(&self, input: &MagneticFieldInput<'_>) -> [f64; 3] {
        // Geodetic → ECEF Cartesian position
        let lat = input.geodetic.latitude;
        let lon = input.geodetic.longitude;
        let h = input.geodetic.altitude;
        let sin_lat = lat.sin();
        let cos_lat = lat.cos();
        let n = WGS84_A / (1.0 - WGS84_E2 * sin_lat * sin_lat).sqrt();
        let x = (n + h) * cos_lat * lon.cos();
        let y = (n + h) * cos_lat * lon.sin();
        let z = (n * (1.0 - WGS84_E2) + h) * sin_lat;

        // ECEF Cartesian → geocentric spherical
        let r_km = (x * x + y * y + z * z).sqrt();
        if r_km < 1.0 {
            return [0.0, 0.0, 0.0];
        }
        let p = (x * x + y * y).sqrt();
        let cos_theta = z / r_km;
        let sin_theta = p / r_km;
        let phi = y.atan2(x);

        // Interpolate Gauss coefficients to epoch
        let year = decimal_year(input.utc);
        let (g, h_coeff) = match &self.custom_coeffs {
            Some(c) => interpolate_custom(year, c, self.max_degree),
            None => interpolate_builtin(year, self.max_degree),
        };

        // Evaluate spherical harmonic expansion
        let (b_r, b_theta, b_phi) = evaluate_sh(
            &g,
            &h_coeff,
            r_km,
            cos_theta,
            sin_theta,
            phi,
            self.max_degree,
        );

        // Convert nT → T
        let b_r_t = b_r * 1e-9;
        let b_theta_t = b_theta * 1e-9;
        let b_phi_t = b_phi * 1e-9;

        // Spherical (B_r, B_theta, B_phi) → ECEF Cartesian
        let cos_phi = phi.cos();
        let sin_phi = phi.sin();

        [
            sin_theta * cos_phi * b_r_t + cos_theta * cos_phi * b_theta_t - sin_phi * b_phi_t,
            sin_theta * sin_phi * b_r_t + cos_theta * sin_phi * b_theta_t + cos_phi * b_phi_t,
            cos_theta * b_r_t - sin_theta * b_theta_t,
        ]
    }
}

// Time utilities

fn decimal_year(epoch: &Epoch) -> f64 {
    let dt = epoch.to_datetime();
    let jan1 = Epoch::from_gregorian(dt.year, 1, 1, 0, 0, 0.0);
    let jan1_next = Epoch::from_gregorian(dt.year + 1, 1, 1, 0, 0, 0.0);
    let denom = jan1_next.jd() - jan1.jd();
    if denom.abs() < 1e-10 {
        return dt.year as f64;
    }
    dt.year as f64 + (epoch.jd() - jan1.jd()) / denom
}

// Coefficient interpolation

fn interpolate_builtin(year: f64, max_degree: usize) -> (IgrfCoeffArray, IgrfCoeffArray) {
    let n = N_COEFFS;
    let mut g = [0.0; N_COEFFS];
    let mut h = [0.0; N_COEFFS];
    let years = &EPOCH_YEARS;
    let last_year = years[NUM_EPOCHS - 1];

    if year >= last_year {
        // At or beyond the last main-field epoch: extrapolate using SV (dt=0 at exact epoch)
        let dt = year - last_year;
        for i in 0..n {
            g[i] = G_EPOCHS[NUM_EPOCHS - 1][i] + DG_SV[i] * dt;
            h[i] = H_EPOCHS[NUM_EPOCHS - 1][i] + DH_SV[i] * dt;
        }
    } else if year <= years[0] {
        // Before the first epoch: extrapolate backward from first interval
        let span = years[1] - years[0];
        let dt = year - years[0];
        for i in 0..n {
            let sv_g = (G_EPOCHS[1][i] - G_EPOCHS[0][i]) / span;
            let sv_h = (H_EPOCHS[1][i] - H_EPOCHS[0][i]) / span;
            g[i] = G_EPOCHS[0][i] + sv_g * dt;
            h[i] = H_EPOCHS[0][i] + sv_h * dt;
        }
    } else {
        // Find bracketing epochs and interpolate
        let mut idx_a = 0;
        for j in 0..(NUM_EPOCHS - 1) {
            if year >= years[j] && year < years[j + 1] {
                idx_a = j;
                break;
            }
        }
        let idx_b = idx_a + 1;
        let ya = years[idx_a];
        let span = years[idx_b] - ya;
        let dt = year - ya;

        for i in 0..n {
            let sv_g = (G_EPOCHS[idx_b][i] - G_EPOCHS[idx_a][i]) / span;
            let sv_h = (H_EPOCHS[idx_b][i] - H_EPOCHS[idx_a][i]) / span;
            g[i] = G_EPOCHS[idx_a][i] + sv_g * dt;
            h[i] = H_EPOCHS[idx_a][i] + sv_h * dt;
        }
    }

    // Zero out coefficients beyond max_degree
    zero_above_degree(&mut g, &mut h, max_degree);

    (g, h)
}

fn zero_above_degree(g: &mut [f64], h: &mut [f64], max_degree: usize) {
    let n = g.len();
    for nn in (max_degree + 1)..=IGRF_MAX_DEGREE {
        for mm in 0..=nn {
            let idx = coeff_index(nn, mm);
            if idx < n {
                g[idx] = 0.0;
                h[idx] = 0.0;
            }
        }
    }
}

fn interpolate_custom(
    year: f64,
    c: &CustomCoeffs,
    max_degree: usize,
) -> (IgrfCoeffArray, IgrfCoeffArray) {
    let mut g = [0.0; N_COEFFS];
    let mut h = [0.0; N_COEFFS];

    let ya = c.epoch_a.year;
    let yb = c.epoch_b.year;
    let span = yb - ya;

    if year <= yb && span.abs() > 1e-10 {
        // Interpolate between epoch_a and epoch_b
        let dt = year - ya;
        for i in 0..N_COEFFS {
            let sv_g = (c.epoch_b.g[i] - c.epoch_a.g[i]) / span;
            let sv_h = (c.epoch_b.h[i] - c.epoch_a.h[i]) / span;
            g[i] = c.epoch_a.g[i] + sv_g * dt;
            h[i] = c.epoch_a.h[i] + sv_h * dt;
        }
    } else {
        // Extrapolate from epoch_b using SV
        let dt = year - yb;
        for i in 0..N_COEFFS {
            g[i] = c.epoch_b.g[i] + c.sv_g[i] * dt;
            h[i] = c.epoch_b.h[i] + c.sv_h[i] * dt;
        }
    }

    zero_above_degree(&mut g, &mut h, max_degree);

    (g, h)
}

// Spherical harmonic evaluation

/// Number of rows/columns in the fixed-size Legendre tables.
const ND: usize = IGRF_MAX_DEGREE + 1;

/// Schmidt semi-normalized associated Legendre functions `P[n][m]` and their
/// colatitude derivatives `dP/dtheta`, for `n, m <= max_degree`.
///
/// Fixed-size `[IGRF_MAX_DEGREE+1][IGRF_MAX_DEGREE+1]` = `[14][14]`; only
/// indices `0..=max_degree` are populated. ~3 KiB on the stack.
///
/// Schmidt semi-normalization means
/// `P^m_n = sqrt(2 (n-m)! / (n+m)!) * P_{n,m}` for `m > 0` (and the plain
/// Legendre function for `m = 0`), which is the convention the IGRF Gauss
/// coefficients are defined in. It is characterised by
/// `∫_{-1}^{1} [P^m_n(x)]^2 dx = 2/(2n+1)` for `m = 0` and `4/(2n+1)` for
/// `m >= 1` — see `schmidt_normalization_holds`, which pins every recursion
/// branch below without needing external reference values.
fn schmidt_legendre(
    cos_theta: f64,
    sin_theta: f64,
    max_degree: usize,
) -> ([[f64; ND]; ND], [[f64; ND]; ND]) {
    let nd = max_degree + 1;
    let mut p = [[0.0; ND]; ND];
    let mut dp = [[0.0; ND]; ND];

    // Initialize P[0][0] = 1
    p[0][0] = 1.0;
    dp[0][0] = 0.0;

    // Diagonal: P[n][n]
    for n in 1..nd {
        let factor = if n == 1 {
            1.0
        } else {
            ((2 * n - 1) as f64 / (2 * n) as f64).sqrt()
        };
        p[n][n] = factor * sin_theta * p[n - 1][n - 1];
        dp[n][n] = factor * (sin_theta * dp[n - 1][n - 1] + cos_theta * p[n - 1][n - 1]);
    }

    // Sub-diagonal: P[n][n-1]
    //
    // The coefficient is `sqrt(2n-1)`, not `2n-1`: substituting `m = n-1` into
    // the general recursion below gives `denom = sqrt(n^2 - (n-1)^2) =
    // sqrt(2n-1)` and `k = 0`, so
    //   P[n][n-1] = (2n-1) cos(theta) P[n-1][n-1] / sqrt(2n-1)
    //             = sqrt(2n-1) cos(theta) P[n-1][n-1].
    // Using `2n-1` broke Schmidt semi-normalization for every intermediate
    // order (0 < m < n), since these values also seed the general recursion.
    for n in 1..nd {
        let c = ((2 * n - 1) as f64).sqrt();
        p[n][n - 1] = cos_theta * c * p[n - 1][n - 1];
        dp[n][n - 1] = c * (cos_theta * dp[n - 1][n - 1] - sin_theta * p[n - 1][n - 1]);
    }

    // General recursion: P[n][m] for m < n-1
    for n in 2..nd {
        for m in 0..=(n.saturating_sub(2)) {
            let n_f = n as f64;
            let m_f = m as f64;
            let k = ((n_f - 1.0) * (n_f - 1.0) - m_f * m_f).sqrt();
            let denom = (n_f * n_f - m_f * m_f).sqrt();
            p[n][m] = ((2.0 * n_f - 1.0) * cos_theta * p[n - 1][m] - k * p[n - 2][m]) / denom;
            dp[n][m] = ((2.0 * n_f - 1.0) * (cos_theta * dp[n - 1][m] - sin_theta * p[n - 1][m])
                - k * dp[n - 2][m])
                / denom;
        }
    }

    (p, dp)
}

/// Evaluate the IGRF spherical harmonic expansion.
///
/// Returns (B_r, B_theta, B_phi) in nT, where:
/// - B_r: radial (outward)
/// - B_theta: southward (colatitude direction)
/// - B_phi: eastward (longitude direction)
fn evaluate_sh(
    g: &[f64],
    h: &[f64],
    r_km: f64,
    cos_theta: f64,
    sin_theta: f64,
    phi: f64,
    max_degree: usize,
) -> (f64, f64, f64) {
    let a = IGRF_REFERENCE_RADIUS;
    let ratio = a / r_km;

    let (p, dp) = schmidt_legendre(cos_theta, sin_theta, max_degree);
    let nd = max_degree + 1;

    // Accumulate field components
    let mut b_r = 0.0;
    let mut b_theta = 0.0;
    let mut b_phi = 0.0;

    let mut r_power = ratio * ratio; // (a/r)^2 for n=1

    for n in 1..nd {
        r_power *= ratio; // (a/r)^(n+2)
        let n_plus_1 = (n + 1) as f64;

        for m in 0..=n {
            let idx = coeff_index(n, m);
            let g_nm = g[idx];
            let h_nm = h[idx];
            let m_f = m as f64;

            let cos_m_phi = (m_f * phi).cos();
            let sin_m_phi = (m_f * phi).sin();

            let gh_cos_sin = g_nm * cos_m_phi + h_nm * sin_m_phi;

            // B_r = -dV/dr = sum (n+1)(a/r)^(n+2) * (g cos + h sin) * P
            b_r += n_plus_1 * r_power * gh_cos_sin * p[n][m];

            // B_theta = -(1/r) dV/dtheta = -sum (a/r)^(n+2) * (g cos + h sin) * dP/dtheta
            b_theta -= r_power * gh_cos_sin * dp[n][m];

            // B_phi = -(1/(r sin theta)) dV/dphi
            //       = sum (a/r)^(n+2) * m * (g sin - h cos) * P / sin(theta)
            //
            // Note the outer minus sign: d/dphi (g cos m.phi + h sin m.phi) is
            // m(-g sin + h cos), and B_phi negates it. Dropping that negation
            // inverts the whole eastward component. This is the standard
            // `Y = m (g sin m.phi - h cos m.phi) P / sin(theta)`.
            if m > 0 {
                let gh_sin_cos = g_nm * sin_m_phi - h_nm * cos_m_phi;
                if sin_theta.abs() > 1e-10 {
                    b_phi += r_power * m_f * gh_sin_cos * p[n][m] / sin_theta;
                } else if m == 1 {
                    // At poles (sin_theta ≈ 0), only m=1 contributes a finite limit.
                    // For Schmidt semi-normalized:
                    //   lim_{θ→0,π} P_n^1(cos θ) / sin θ = sqrt(n*(n+1)/2)
                    // Sign: at θ=0 (north pole) the limit is positive,
                    //        at θ=π (south pole) it's (-1)^(n+1) * sqrt(n*(n+1)/2).
                    let n_f = n as f64;
                    let limit = (n_f * (n_f + 1.0) / 2.0).sqrt();
                    // At south pole (cos_theta < 0), odd-(n+1) terms flip sign.
                    let sign = if cos_theta < 0.0 && (n + 1) % 2 != 0 {
                        -1.0
                    } else {
                        1.0
                    };
                    b_phi += r_power * gh_sin_cos * sign * limit;
                }
                // For m > 1: P_n^m / sin(theta) → 0 at the poles.
            }
        }
    }

    (b_r, b_theta, b_phi)
}

#[cfg(test)]
mod tests {
    use super::*;
    use arika::earth::ellipsoid::WGS84_B;
    use arika::earth::geodetic::Geodetic;

    fn epoch_2025() -> Epoch {
        Epoch::from_gregorian(2025, 1, 1, 0, 0, 0.0)
    }

    fn make_input(geodetic: Geodetic, epoch: &Epoch) -> MagneticFieldInput<'_> {
        MagneticFieldInput {
            geodetic,
            utc: epoch,
        }
    }

    fn b_magnitude(b: &[f64; 3]) -> f64 {
        (b[0] * b[0] + b[1] * b[1] + b[2] * b[2]).sqrt()
    }

    #[test]
    fn decimal_year_j2000() {
        let dy = decimal_year(&Epoch::j2000());
        assert!(
            (dy - 2000.0).abs() < 0.01,
            "J2000 should be ~2000.0, got {dy}"
        );
    }

    #[test]
    fn decimal_year_2025_jan1() {
        let dy = decimal_year(&epoch_2025());
        assert!(
            (dy - 2025.0).abs() < 0.01,
            "2025 Jan 1 should be ~2025.0, got {dy}"
        );
    }

    #[test]
    fn igrf_field_magnitude_at_equatorial_leo() {
        // At equatorial LEO (7000 km from centre), expect |B| ~ 20-50 uT
        let igrf = Igrf::earth();
        let epoch = epoch_2025();
        let input = make_input(
            Geodetic {
                latitude: 0.0,
                longitude: 0.0,
                altitude: 7000.0 - WGS84_A,
            },
            &epoch,
        );
        let b = igrf.field_ecef(&input);
        let b_micro_t = b_magnitude(&b) * 1e6;

        assert!(
            b_micro_t > 15.0 && b_micro_t < 60.0,
            "Equatorial LEO field should be ~20-50 uT, got {b_micro_t:.2} uT"
        );
    }

    #[test]
    fn igrf_field_magnitude_at_north_pole() {
        // Near north pole, expect stronger field ~50-60 uT
        let igrf = Igrf::earth();
        let r = 6771.0; // ~400km altitude at pole
        let epoch = epoch_2025();
        let input = make_input(
            Geodetic {
                latitude: std::f64::consts::FRAC_PI_2,
                longitude: 0.0,
                altitude: r - WGS84_B,
            },
            &epoch,
        );
        let b = igrf.field_ecef(&input);
        let b_micro_t = b_magnitude(&b) * 1e6;

        assert!(
            b_micro_t > 40.0 && b_micro_t < 80.0,
            "Polar field should be ~50-65 uT, got {b_micro_t:.2} uT"
        );
    }

    #[test]
    fn igrf_inverse_cube_at_high_altitude() {
        // At large distances, field should approximately follow 1/r^3
        let igrf = Igrf::earth();
        let epoch = epoch_2025();
        let b1 = b_magnitude(&igrf.field_ecef(&make_input(
            Geodetic {
                latitude: 0.0,
                longitude: 0.0,
                altitude: 20000.0 - WGS84_A,
            },
            &epoch,
        )));
        let b2 = b_magnitude(&igrf.field_ecef(&make_input(
            Geodetic {
                latitude: 0.0,
                longitude: 0.0,
                altitude: 40000.0 - WGS84_A,
            },
            &epoch,
        )));

        let ratio = b1 / b2;
        // Should be close to 8.0 (exact for pure dipole)
        assert!(
            (ratio - 8.0).abs() < 0.5,
            "Expected ~8.0 ratio at high altitude, got {ratio:.2}"
        );
    }

    #[test]
    fn igrf_differs_from_dipole_at_leo() {
        // At LEO, IGRF should differ meaningfully from a simple dipole
        use super::super::TiltedDipole;

        let igrf = Igrf::earth();
        let dipole = TiltedDipole::earth();
        let epoch = epoch_2025();

        // South Atlantic Anomaly region (~-30° lat, -50° lon)
        let geo = Geodetic {
            latitude: -30.0_f64.to_radians(),
            longitude: -50.0_f64.to_radians(),
            altitude: 400.0,
        };
        let input = make_input(geo, &epoch);

        let b_igrf = b_magnitude(&igrf.field_ecef(&input));
        let b_dipole = b_magnitude(&dipole.field_ecef(&input));

        let diff_pct = ((b_igrf - b_dipole) / b_dipole).abs() * 100.0;
        assert!(
            diff_pct > 0.5,
            "IGRF and dipole should differ by >0.5% at LEO, got {diff_pct:.1}%"
        );
    }

    #[test]
    fn igrf_converges_to_dipole_at_geo() {
        // At GEO altitude, higher harmonics are negligible
        use super::super::TiltedDipole;

        let igrf = Igrf::earth();
        let dipole = TiltedDipole::earth();
        let epoch = epoch_2025();

        let geo_r = 42164.0; // GEO radius in km
        let geo = Geodetic {
            latitude: 0.0,
            longitude: 0.0,
            altitude: geo_r - WGS84_A,
        };
        let input = make_input(geo, &epoch);

        let v_igrf = igrf.field_ecef(&input);
        let v_dipole = dipole.field_ecef(&input);

        // Compare the *vector direction*, not just the magnitude: a
        // magnitude-only check is invariant under a full sign inversion of
        // either model, which is exactly the kind of bug that hid here before.
        //
        // The tolerance is loose on purpose. `TiltedDipole` places its 11.5°
        // tilt at longitude 0, while the real geomagnetic pole sits near
        // 80.6°N 72.6°W — the two axes are 12.4° apart, which shows up here as
        // roughly 21° between the field vectors (measured cos ≈ 0.933). So this
        // guards against inversion, not against that tilt-longitude
        // simplification. An inverted model gives cos ≈ -0.93.
        let dot: f64 = (0..3).map(|i| v_igrf[i] * v_dipole[i]).sum();
        let cos_angle = dot / (b_magnitude(&v_igrf) * b_magnitude(&v_dipole));
        assert!(
            cos_angle > 0.85,
            "IGRF and dipole should point the same way at GEO, \
             got cos(angle) = {cos_angle:.4} (IGRF {v_igrf:?}, dipole {v_dipole:?})"
        );

        // At GEO the dipole dominates; expect <15% difference
        // (TiltedDipole uses approximate parameters, so some difference is expected)
        let b_igrf = b_magnitude(&v_igrf);
        let b_dipole = b_magnitude(&v_dipole);
        let diff_pct = ((b_igrf - b_dipole) / b_dipole).abs() * 100.0;
        assert!(
            diff_pct < 15.0,
            "IGRF and dipole should converge at GEO (<15%), got {diff_pct:.1}%"
        );
    }

    #[test]
    fn igrf_zero_inside_earth() {
        // Altitude deep below surface → geocentric r < 1 km → guard returns zero
        let igrf = Igrf::earth();
        let epoch = epoch_2025();
        let input = make_input(
            Geodetic {
                latitude: 0.0,
                longitude: 0.0,
                altitude: -WGS84_A, // centre of the Earth
            },
            &epoch,
        );
        let b = igrf.field_ecef(&input);
        assert_eq!(b, [0.0, 0.0, 0.0]);
    }

    #[test]
    fn igrf_field_is_finite() {
        let igrf = Igrf::earth();
        let epoch = epoch_2025();
        let input = make_input(
            Geodetic {
                latitude: 0.0,
                longitude: 0.0,
                altitude: 6778.0 - WGS84_A,
            },
            &epoch,
        );
        let b = igrf.field_ecef(&input);
        assert!(
            b[0].is_finite() && b[1].is_finite() && b[2].is_finite(),
            "Field must be finite: {b:?}"
        );
    }

    #[test]
    fn igrf_secular_variation() {
        // Field should change between 2020 and 2025
        let igrf = Igrf::earth();
        let geo = Geodetic {
            latitude: 0.0,
            longitude: 0.0,
            altitude: 7000.0 - WGS84_A,
        };

        let e2020 = Epoch::from_gregorian(2020, 1, 1, 0, 0, 0.0);
        let e2025 = epoch_2025();

        let b2020 = igrf.field_ecef(&make_input(geo, &e2020));
        let b2025 = igrf.field_ecef(&make_input(geo, &e2025));

        let diff = ((b2020[0] - b2025[0]).powi(2)
            + (b2020[1] - b2025[1]).powi(2)
            + (b2020[2] - b2025[2]).powi(2))
        .sqrt();
        assert!(
            diff > 1e-10,
            "Field should change between 2020 and 2025, diff={diff:.3e}"
        );
    }

    #[test]
    fn igrf_truncation_degree1_is_dipole_like() {
        let igrf1 = Igrf::with_max_degree(1);
        let igrf13 = Igrf::earth();
        let epoch = epoch_2025();

        let geo = Geodetic {
            latitude: 0.0,
            longitude: 0.0,
            altitude: 7000.0 - WGS84_A,
        };
        let input = make_input(geo, &epoch);
        let b1 = b_magnitude(&igrf1.field_ecef(&input));
        let b13 = b_magnitude(&igrf13.field_ecef(&input));

        // Degree-1 should be within ~20% of full model at LEO
        let diff_pct = ((b1 - b13) / b13).abs() * 100.0;
        assert!(
            diff_pct < 25.0,
            "Degree-1 truncation should be within 25% of full model, got {diff_pct:.1}%"
        );
    }

    /// Pin every branch of [`schmidt_legendre`] without external reference
    /// values, via the orthogonality relation that *defines* Schmidt
    /// semi-normalization:
    ///
    /// ```text
    /// ∫_{-1}^{1} [P^m_n(x)]^2 dx = 2/(2n+1)   (m = 0)
    ///                            = 4/(2n+1)   (m >= 1)
    /// ```
    ///
    /// This is what catches a wrong recursion coefficient: using `2n-1`
    /// instead of `sqrt(2n-1)` on the sub-diagonal leaves `m = 0` and `m = n`
    /// correct but breaks every intermediate order, because those values also
    /// seed the general recursion. So the test must cover `0 < m < n`, not just
    /// the extremes.
    #[test]
    fn schmidt_normalization_holds() {
        // Midpoint rule over x = cos(theta). Smooth integrand, so this is
        // plenty for the 1e-3 relative tolerance below.
        const STEPS: usize = 20_000;
        const MAX_N: usize = 6;

        let mut integrals = [[0.0_f64; ND]; ND];
        for i in 0..STEPS {
            let x = -1.0 + (i as f64 + 0.5) * 2.0 / STEPS as f64;
            let sin_theta = (1.0 - x * x).max(0.0).sqrt();
            let (p, _) = schmidt_legendre(x, sin_theta, MAX_N);
            for n in 0..=MAX_N {
                for m in 0..=n {
                    integrals[n][m] += p[n][m] * p[n][m];
                }
            }
        }

        for n in 1..=MAX_N {
            for m in 0..=n {
                let got = integrals[n][m] * 2.0 / STEPS as f64;
                let expected = if m == 0 { 2.0 } else { 4.0 } / (2 * n + 1) as f64;
                let rel = (got - expected).abs() / expected;
                assert!(
                    rel < 1e-3,
                    "P^{m}_{n} is not Schmidt semi-normalized: \
                     ∫P² = {got:.6}, expected {expected:.6} (relative error {rel:.3e})"
                );
            }
        }
    }

    /// The pole branch of `B_phi` uses the closed form
    /// `lim_{θ→0} P^1_n(cos θ)/sin θ = sqrt(n(n+1)/2)`, derived straight from
    /// the Schmidt definition. Check the recursion agrees with it, so the two
    /// code paths cannot drift apart again.
    #[test]
    fn near_pole_p_n1_matches_closed_form_limit() {
        let theta = 1e-7_f64;
        let (p, _) = schmidt_legendre(theta.cos(), theta.sin(), 6);
        for n in 1..=6 {
            let n_f = n as f64;
            let expected = (n_f * (n_f + 1.0) / 2.0).sqrt();
            let got = p[n][1] / theta.sin();
            assert!(
                (got - expected).abs() < 1e-6 * expected,
                "P^1_{n}/sin(theta) near the pole = {got:.9}, \
                 closed form sqrt(n(n+1)/2) = {expected:.9}"
            );
        }
    }

    /// `dP/dtheta` must be the analytic derivative of `P`, for every recursion
    /// branch. Compared against a central difference rather than a table, so
    /// this needs no external reference values either.
    #[test]
    fn schmidt_legendre_derivative_matches_central_difference() {
        const EPS: f64 = 1e-6;
        for theta_deg in [7.0_f64, 31.0, 45.0, 88.0, 124.0, 170.0] {
            let theta = theta_deg.to_radians();
            let (_, dp) = schmidt_legendre(theta.cos(), theta.sin(), IGRF_MAX_DEGREE);
            let (p_plus, _) =
                schmidt_legendre((theta + EPS).cos(), (theta + EPS).sin(), IGRF_MAX_DEGREE);
            let (p_minus, _) =
                schmidt_legendre((theta - EPS).cos(), (theta - EPS).sin(), IGRF_MAX_DEGREE);
            for n in 0..=IGRF_MAX_DEGREE {
                for m in 0..=n {
                    let numeric = (p_plus[n][m] - p_minus[n][m]) / (2.0 * EPS);
                    // Scale the tolerance by the local magnitude; these grow
                    // with degree.
                    let scale = dp[n][m].abs().max(1.0);
                    assert!(
                        (dp[n][m] - numeric).abs() < 1e-5 * scale,
                        "dP^{m}_{n}/dtheta at {theta_deg} deg: analytic {:.9}, \
                         central difference {numeric:.9}",
                        dp[n][m]
                    );
                }
            }
        }
    }

    /// Exercise the real `evaluate_sh` path with a single non-zero coefficient,
    /// so the *eastward* sign convention is pinned end to end rather than only
    /// the Legendre recursion.
    ///
    /// With only `h_1^1 > 0` the potential is `V ~ h sin(phi) sin(theta)`, so
    /// `B_phi = -(1/(r sin theta)) dV/dphi < 0` at `phi = 0` on the equator.
    /// The standard form is `Y = m (g sin m.phi - h cos m.phi) P / sin(theta)`;
    /// dropping its outer minus sign inverts the whole component.
    #[test]
    fn b_phi_sign_matches_potential_derivative() {
        let mut g = [0.0; N_COEFFS];
        let mut h = [0.0; N_COEFFS];
        h[coeff_index(1, 1)] = 1000.0;

        // Equator, phi = 0.
        let (_, _, b_phi) = evaluate_sh(&g, &h, IGRF_REFERENCE_RADIUS, 0.0, 1.0, 0.0, 1);
        assert!(
            b_phi < 0.0,
            "with h_1^1 > 0 at phi = 0 on the equator, B_phi must be negative, got {b_phi}"
        );

        // A quarter turn east puts h_1^1 into the radial/southward terms
        // instead, so B_phi passes through zero.
        let (_, _, b_phi_quarter) = evaluate_sh(
            &g,
            &h,
            IGRF_REFERENCE_RADIUS,
            0.0,
            1.0,
            core::f64::consts::FRAC_PI_2,
            1,
        );
        assert!(
            b_phi_quarter.abs() < 1e-9,
            "B_phi should vanish at phi = 90 deg for a pure h_1^1, got {b_phi_quarter}"
        );

        // Same check for a pure g_1^1: V ~ g cos(phi) sin(theta), so
        // dV/dphi = -g sin(phi) sin(theta), which is zero at phi = 0 and
        // positive-B_phi at phi = 90 deg.
        g[coeff_index(1, 1)] = 1000.0;
        h[coeff_index(1, 1)] = 0.0;
        let (_, _, b_phi_g) = evaluate_sh(
            &g,
            &h,
            IGRF_REFERENCE_RADIUS,
            0.0,
            1.0,
            core::f64::consts::FRAC_PI_2,
            1,
        );
        assert!(
            b_phi_g > 0.0,
            "with g_1^1 > 0 at phi = 90 deg, B_phi must be positive, got {b_phi_g}"
        );
    }

    /// The `sin_theta <= 1e-10` pole branch must agree with the ordinary path
    /// just off the pole — otherwise `B_phi` jumps discontinuously there. This
    /// covers the closed-form limit, its south-pole parity, and the eastward
    /// sign all at once, which the recursion-only test cannot.
    #[test]
    fn b_phi_pole_branch_is_continuous() {
        let mut g = [0.0; N_COEFFS];
        let mut h = [0.0; N_COEFFS];
        // Both m=1 coefficients, so neither term is accidentally cancelled.
        g[coeff_index(1, 1)] = 1000.0;
        h[coeff_index(1, 1)] = -2000.0;
        g[coeff_index(2, 1)] = 500.0;
        h[coeff_index(2, 1)] = 300.0;
        let phi = 0.7_f64;

        for (name, cos_theta) in [("north", 1.0_f64), ("south", -1.0_f64)] {
            // Exactly on the axis: takes the limit branch.
            let (_, _, at_pole) =
                evaluate_sh(&g, &h, IGRF_REFERENCE_RADIUS, cos_theta, 0.0, phi, 2);
            // A hair off the axis: takes the ordinary `P / sin(theta)` path.
            let theta = if cos_theta > 0.0 {
                1e-8
            } else {
                core::f64::consts::PI - 1e-8
            };
            let (_, _, near_pole) = evaluate_sh(
                &g,
                &h,
                IGRF_REFERENCE_RADIUS,
                theta.cos(),
                theta.sin(),
                phi,
                2,
            );
            assert!(
                (at_pole - near_pole).abs() < 1e-6 * at_pole.abs().max(1.0),
                "B_phi is discontinuous at the {name} pole: limit branch {at_pole:.9}, \
                 ordinary path just off-axis {near_pole:.9}"
            );
        }
    }
}
