//! Oracle tests: validate OrbitalSystem<Gcrs> against Orekit GCRF reference.
//!
//! Fixtures generated by `tools/generate_gcrf_propagation_fixtures.py` using
//! Orekit's NumericalPropagator in GCRF frame with IERS 2010 conventions.
//!
//! Key differences from the EME2000 fixtures (oracle_orekit.rs):
//! - **Frame**: GCRF (includes IAU frame bias) vs EME2000 (J2000 mean equator)
//! - **Drag geodetic**: Orekit uses ITRF via full IAU 2006 chain with real EOP;
//!   our Gcrs path uses EarthFrameBridge<Gcrs> with ZeroEop (no dUT1, xp=yp=0)
//! - **Known EOP gap**: ZeroEop vs real EOP introduces ~arcsec-level rotation
//!   difference (~meter-level position error per orbit)

use arika::earth::eop::{NutationCorrections, PolarMotion, Ut1Offset};
use arika::earth::{J2 as J2_EARTH, J3 as J3_EARTH, J4 as J4_EARTH};
use arika::earth::{MU as MU_EARTH, R as R_EARTH};
use arika::epoch::Epoch;
use arika::frame;
use nalgebra::Vector3;
use orts::environment::GcrsEopStorage;
use orts::orbital::OrbitalState;
use orts::orbital::OrbitalSystem;
use orts::orbital::gravity::ZonalHarmonics;
use orts::perturbations::{AtmosphericDrag, ThirdBodyGravity};
use serde::Deserialize;
use tobari::{ConstantWeather, CssiData, CssiSpaceWeather, Nrlmsise00};
use utsuroi::{DormandPrince, Integrator};

// --- Fixture data structures ---

#[derive(Deserialize)]
struct FixtureFile {
    #[allow(dead_code)]
    constants: Constants,
    scenarios: Vec<Scenario>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct Constants {
    mu_earth_km3_s2: f64,
    r_earth_km: f64,
    j2: f64,
    j3: f64,
    j4: f64,
    mu_sun_km3_s2: f64,
    mu_moon_km3_s2: f64,
}

#[derive(Deserialize)]
struct Scenario {
    name: String,
    #[allow(dead_code)]
    description: String,
    epoch_utc: String,
    initial_cartesian: InitialCartesian,
    force_model: ForceModelConfig,
    satellite: SatelliteConfig,
    #[allow(dead_code)]
    duration_s: f64,
    trajectory: Vec<TrajectoryPoint>,
}

#[derive(Deserialize)]
struct InitialCartesian {
    position_km: [f64; 3],
    velocity_km_s: [f64; 3],
}

#[derive(Deserialize)]
struct ForceModelConfig {
    gravity: GravityConfig,
    drag: Option<DragConfig>,
    third_body_sun: bool,
    third_body_moon: bool,
}

#[derive(Deserialize)]
struct GravityConfig {
    degree: u32,
}

#[derive(Deserialize)]
struct DragConfig {
    model: String,
    weather: Option<WeatherConfig>,
}

#[derive(Deserialize)]
struct WeatherConfig {
    f107: f64,
    ap: f64,
}

#[derive(Deserialize)]
struct SatelliteConfig {
    ballistic_coeff_m2_kg: Option<f64>,
}

#[derive(Deserialize)]
struct TrajectoryPoint {
    t_seconds: f64,
    position_km: [f64; 3],
    #[allow(dead_code)]
    velocity_km_s: [f64; 3],
}

// --- ZeroEop provider ---

struct ZeroEop;

impl Ut1Offset for ZeroEop {
    fn dut1(&self, _: f64) -> f64 {
        0.0
    }
}
impl PolarMotion for ZeroEop {
    fn x_pole(&self, _: f64) -> f64 {
        0.0
    }
    fn y_pole(&self, _: f64) -> f64 {
        0.0
    }
}
impl NutationCorrections for ZeroEop {
    fn dx(&self, _: f64) -> f64 {
        0.0
    }
    fn dy(&self, _: f64) -> f64 {
        0.0
    }
}

// --- Helpers ---

fn load_fixtures() -> FixtureFile {
    let json = include_str!("fixtures/orekit_gcrf_propagation_reference.json");
    serde_json::from_str(json).expect("Failed to parse GCRF fixture JSON")
}

fn find_scenario<'a>(fixtures: &'a FixtureFile, name: &str) -> &'a Scenario {
    fixtures
        .scenarios
        .iter()
        .find(|s| s.name == name)
        .unwrap_or_else(|| panic!("Scenario '{name}' not found in fixtures"))
}

fn parse_epoch(s: &str) -> Epoch {
    let s = s.trim_end_matches('Z');
    let parts: Vec<&str> = s.split('T').collect();
    let date: Vec<u32> = parts[0].split('-').map(|p| p.parse().unwrap()).collect();
    let time: Vec<&str> = parts[1].split(':').collect();
    let hour: u32 = time[0].parse().unwrap();
    let min: u32 = time[1].parse().unwrap();
    let sec: f64 = time[2].parse().unwrap();
    Epoch::from_gregorian(date[0] as i32, date[1], date[2], hour, min, sec)
}

fn build_gcrs_system(scenario: &Scenario) -> OrbitalSystem<frame::Gcrs> {
    let fm = &scenario.force_model;
    let epoch = parse_epoch(&scenario.epoch_utc);

    let gravity: Box<dyn orts::orbital::gravity::GravityField> = match fm.gravity.degree {
        0 => Box::new(orts::orbital::gravity::PointMass),
        2 => Box::new(ZonalHarmonics {
            r_body: R_EARTH,
            j2: J2_EARTH,
            j3: None,
            j4: None,
        }),
        d if d >= 4 => Box::new(ZonalHarmonics {
            r_body: R_EARTH,
            j2: J2_EARTH,
            j3: Some(J3_EARTH),
            j4: Some(J4_EARTH),
        }),
        d => panic!("Unsupported gravity degree: {d}"),
    };

    let mut system = OrbitalSystem::<frame::Gcrs>::new(MU_EARTH, gravity)
        .with_epoch(epoch)
        .with_body_radius(R_EARTH);

    if fm.third_body_sun {
        system = system.with_model(ThirdBodyGravity::sun());
    }
    if fm.third_body_moon {
        system = system.with_model(ThirdBodyGravity::moon());
    }

    if let Some(drag_cfg) = &fm.drag {
        let sat = &scenario.satellite;
        let b = sat.ballistic_coeff_m2_kg.unwrap_or(0.01);
        let eop = GcrsEopStorage::new(ZeroEop);
        let mut drag = AtmosphericDrag::<frame::Gcrs>::for_earth_in_frame(Some(b), eop);
        match drag_cfg.model.as_str() {
            "nrlmsise00" => {
                if let Some(weather) = &drag_cfg.weather {
                    let provider = Box::new(ConstantWeather::new(weather.f107, weather.ap));
                    drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(provider)));
                }
            }
            "nrlmsise00_cssi" => {
                let cssi_text = include_str!("fixtures/cssi_test_weather.txt");
                let cssi_data = CssiData::parse(cssi_text).expect("Failed to parse CSSI fixture");
                let provider = Box::new(CssiSpaceWeather::new(cssi_data));
                drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(provider)));
            }
            other => panic!("Unknown drag model: {other}"),
        }
        system = system.with_model(drag);
    }

    system
}

/// Propagate with Gcrs path and return final position error vs Orekit.
fn final_pos_err_gcrs(scenario: &Scenario, system: &OrbitalSystem<frame::Gcrs>) -> f64 {
    let ic = &scenario.initial_cartesian;
    let initial = OrbitalState::<frame::Gcrs>::new_in_frame(
        Vector3::new(ic.position_km[0], ic.position_km[1], ic.position_km[2]),
        Vector3::new(
            ic.velocity_km_s[0],
            ic.velocity_km_s[1],
            ic.velocity_km_s[2],
        ),
    );

    let dp = DormandPrince;
    let duration = scenario.trajectory.last().unwrap().t_seconds;
    let final_state = dp.integrate(system, initial, 0.0, duration, 30.0, |_, _| {});

    let final_orekit = scenario.trajectory.last().unwrap();
    (Vector3::new(
        final_orekit.position_km[0],
        final_orekit.position_km[1],
        final_orekit.position_km[2],
    ) - *final_state.position())
    .magnitude()
}

/// Propagate with SimpleEci path (same initial conditions) and return
/// final position error vs the GCRF Orekit fixture.
///
/// The GCRF fixture and EME2000 differ by ~23 mas (frame bias), which
/// is sub-meter at LEO. So comparing SimpleEci against the GCRF fixture
/// gives a meaningful (if slightly pessimistic) error measure.
fn final_pos_err_simple(scenario: &Scenario) -> f64 {
    let ic = &scenario.initial_cartesian;
    let initial = OrbitalState::new(
        Vector3::new(ic.position_km[0], ic.position_km[1], ic.position_km[2]),
        Vector3::new(
            ic.velocity_km_s[0],
            ic.velocity_km_s[1],
            ic.velocity_km_s[2],
        ),
    );

    let fm = &scenario.force_model;
    let epoch = parse_epoch(&scenario.epoch_utc);

    let gravity: Box<dyn orts::orbital::gravity::GravityField> = match fm.gravity.degree {
        2 => Box::new(ZonalHarmonics {
            r_body: R_EARTH,
            j2: J2_EARTH,
            j3: None,
            j4: None,
        }),
        _ => Box::new(orts::orbital::gravity::PointMass),
    };

    let mut system = OrbitalSystem::new(MU_EARTH, gravity)
        .with_epoch(epoch)
        .with_body_radius(R_EARTH);

    if fm.third_body_sun {
        system = system.with_model(ThirdBodyGravity::sun());
    }
    if fm.third_body_moon {
        system = system.with_model(ThirdBodyGravity::moon());
    }

    if let Some(drag_cfg) = &fm.drag {
        let b = scenario.satellite.ballistic_coeff_m2_kg.unwrap_or(0.01);
        let mut drag = AtmosphericDrag::for_earth(Some(b));
        match drag_cfg.model.as_str() {
            "nrlmsise00" => {
                if let Some(w) = &drag_cfg.weather {
                    drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(Box::new(
                        ConstantWeather::new(w.f107, w.ap),
                    ))));
                }
            }
            "nrlmsise00_cssi" => {
                let cssi_text = include_str!("fixtures/cssi_test_weather.txt");
                let cssi_data = CssiData::parse(cssi_text).unwrap();
                drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(Box::new(
                    CssiSpaceWeather::new(cssi_data),
                ))));
            }
            _ => {}
        }
        system = system.with_model(drag);
    }

    let dp = DormandPrince;
    let duration = scenario.trajectory.last().unwrap().t_seconds;
    let final_state = dp.integrate(&system, initial, 0.0, duration, 30.0, |_, _| {});

    let final_orekit = scenario.trajectory.last().unwrap();
    (Vector3::new(
        final_orekit.position_km[0],
        final_orekit.position_km[1],
        final_orekit.position_km[2],
    ) - *final_state.position())
    .magnitude()
}

// --- Tests ---

#[test]
fn gcrf_j2_thirdbody_iss_10orbits() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_thirdbody_iss_10orbits");

    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + third-body ISS 10 orbits:");
    println!(
        "  Gcrs  error: {:.6} km ({:.1} m)",
        gcrs_err,
        gcrs_err * 1000.0
    );
    println!(
        "  Simple error: {:.6} km ({:.1} m)",
        simple_err,
        simple_err * 1000.0
    );
    println!("  Improvement:  {:.1}x", simple_err / gcrs_err);

    assert!(
        gcrs_err < 0.5,
        "Gcrs final pos error {:.3} km exceeds 500 m",
        gcrs_err
    );
}

#[test]
fn gcrf_j2_msise_thirdbody_iss_10orbits() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_thirdbody_iss_10orbits");

    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + NRLMSISE-00 + third-body ISS 10 orbits:");
    println!(
        "  Gcrs  error: {:.6} km ({:.1} m)",
        gcrs_err,
        gcrs_err * 1000.0
    );
    println!(
        "  Simple error: {:.6} km ({:.1} m)",
        simple_err,
        simple_err * 1000.0
    );
    println!("  Improvement:  {:.1}x", simple_err / gcrs_err);

    // Measured: Gcrs ~9.8 m, SimpleEci ~12.4 m. Tolerance with ~20% buffer.
    assert!(
        gcrs_err < 0.015,
        "Gcrs final pos error {:.6} km exceeds 15 m",
        gcrs_err
    );
    // Gcrs path must be strictly better than SimpleEci for drag scenarios
    assert!(
        gcrs_err < simple_err,
        "Gcrs ({gcrs_err:.6} km) should be better than SimpleEci ({simple_err:.6} km)"
    );
}

#[test]
fn gcrf_j2_msise_cssi_thirdbody_iss_30day() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_cssi_thirdbody_iss_30day");

    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + NRLMSISE-00 CSSI + third-body ISS 30 days:");
    println!("  Gcrs  error: {:.3} km", gcrs_err);
    println!("  Simple error: {:.3} km", simple_err);
    println!("  Improvement:  {:.1}x", simple_err / gcrs_err);

    // Measured: Gcrs ~8.9 km, SimpleEci ~22.6 km. Tolerance with ~20% buffer.
    assert!(
        gcrs_err < 12.0,
        "Gcrs final pos error {:.3} km exceeds 12 km",
        gcrs_err
    );
    // Gcrs path must be strictly better than SimpleEci for drag scenarios
    assert!(
        gcrs_err < simple_err,
        "Gcrs ({gcrs_err:.3} km) should be better than SimpleEci ({simple_err:.3} km) for 30-day drag"
    );
}
