//! Oracle tests: validate OrbitalSystem<Gcrs> against Orekit GCRF reference.
//!
//! Fixtures generated by `tools/generate_gcrf_propagation_fixtures.py` using
//! Orekit's NumericalPropagator in GCRF frame with IERS 2010 conventions.
//!
//! Key differences from the EME2000 fixtures (oracle_orekit.rs):
//! - **Frame**: GCRF (includes IAU frame bias) vs EME2000 (J2000 mean equator)
//! - **Drag geodetic**: Orekit uses ITRF via full IAU 2006 chain with real EOP;
//!   our Gcrs path uses EarthFixedTransform<Gcrs> with ZeroEop (no dUT1, xp=yp=0)
//! - **Known EOP gap**: ZeroEop vs real EOP introduces ~arcsec-level rotation
//!   difference (~meter-level position error per orbit)

use arika::earth::GcrsEopStorage;
use arika::earth::eop::{NutationCorrections, PolarMotion, Ut1Offset};
use arika::earth::{J2 as J2_EARTH, J3 as J3_EARTH, J4 as J4_EARTH};
use arika::earth::{MU as MU_EARTH, R as R_EARTH};
use arika::epoch::Epoch;
use arika::frame;
use nalgebra::Vector3;
use orts::orbital::OrbitalState;
use orts::orbital::OrbitalSystem;
use orts::orbital::gravity::PointMass;
use orts::perturbations::{AtmosphericDrag, ThirdBodyGravity, ZonalGravity};
use serde::Deserialize;
use tobari::{ConstantWeather, CssiData, CssiSpaceWeather, Nrlmsise00};
use utsuroi::{DormandPrince, Integrator};

// Fixture data structures

#[derive(Deserialize)]
struct FixtureFile {
    #[allow(dead_code)]
    constants: Constants,
    scenarios: Vec<Scenario>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct Constants {
    mu_earth_km3_s2: f64,
    r_earth_km: f64,
    j2: f64,
    j3: f64,
    j4: f64,
    mu_sun_km3_s2: f64,
    mu_moon_km3_s2: f64,
}

#[derive(Deserialize)]
struct Scenario {
    name: String,
    #[allow(dead_code)]
    description: String,
    epoch_utc: String,
    initial_cartesian: InitialCartesian,
    force_model: ForceModelConfig,
    satellite: SatelliteConfig,
    #[allow(dead_code)]
    duration_s: f64,
    trajectory: Vec<TrajectoryPoint>,
}

#[derive(Deserialize)]
struct InitialCartesian {
    position_km: [f64; 3],
    velocity_km_s: [f64; 3],
}

#[derive(Deserialize)]
struct ForceModelConfig {
    gravity: GravityConfig,
    drag: Option<DragConfig>,
    third_body_sun: bool,
    third_body_moon: bool,
}

#[derive(Deserialize)]
struct GravityConfig {
    degree: u32,
}

#[derive(Deserialize)]
struct DragConfig {
    model: String,
    weather: Option<WeatherConfig>,
}

#[derive(Deserialize)]
struct WeatherConfig {
    f107: f64,
    ap: f64,
}

#[derive(Deserialize)]
struct SatelliteConfig {
    ballistic_coeff_m2_kg: Option<f64>,
}

#[derive(Deserialize)]
struct TrajectoryPoint {
    t_seconds: f64,
    position_km: [f64; 3],
    #[allow(dead_code)]
    velocity_km_s: [f64; 3],
}

// ZeroEop provider

struct ZeroEop;

impl Ut1Offset for ZeroEop {
    fn dut1(&self, _: f64) -> f64 {
        0.0
    }
}
impl PolarMotion for ZeroEop {
    fn x_pole(&self, _: f64) -> f64 {
        0.0
    }
    fn y_pole(&self, _: f64) -> f64 {
        0.0
    }
}
impl NutationCorrections for ZeroEop {
    fn dx(&self, _: f64) -> f64 {
        0.0
    }
    fn dy(&self, _: f64) -> f64 {
        0.0
    }
}

fn load_fixtures() -> FixtureFile {
    let json = include_str!("fixtures/orekit_gcrf_propagation_reference.json");
    serde_json::from_str(json).expect("Failed to parse GCRF fixture JSON")
}

fn find_scenario<'a>(fixtures: &'a FixtureFile, name: &str) -> &'a Scenario {
    fixtures
        .scenarios
        .iter()
        .find(|s| s.name == name)
        .unwrap_or_else(|| panic!("Scenario '{name}' not found in fixtures"))
}

fn parse_epoch(s: &str) -> Epoch {
    let s = s.trim_end_matches('Z');
    let parts: Vec<&str> = s.split('T').collect();
    let date: Vec<u32> = parts[0].split('-').map(|p| p.parse().unwrap()).collect();
    let time: Vec<&str> = parts[1].split(':').collect();
    let hour: u32 = time[0].parse().unwrap();
    let min: u32 = time[1].parse().unwrap();
    let sec: f64 = time[2].parse().unwrap();
    Epoch::from_gregorian(date[0] as i32, date[1], date[2], hour, min, sec)
}

fn build_gcrs_system_with_eop(
    scenario: &Scenario,
    eop: GcrsEopStorage,
) -> OrbitalSystem<frame::Gcrs> {
    let fm = &scenario.force_model;
    let epoch = parse_epoch(&scenario.epoch_utc);

    let mut system = OrbitalSystem::<frame::Gcrs>::new(MU_EARTH, Box::new(PointMass))
        .with_epoch(epoch)
        .with_body_radius(R_EARTH);

    // Zonal gravity about the CIP (the Gcrs true pole) — the accuracy gain over
    // the SimpleEci +Z path. The Orekit fixtures use a CIRF body frame to match.
    match fm.gravity.degree {
        0 => {}
        2 => {
            system = system.with_model(ZonalGravity::<frame::Gcrs>::new(
                MU_EARTH, R_EARTH, J2_EARTH, None, None,
            ));
        }
        d if d >= 4 => {
            system = system.with_model(ZonalGravity::<frame::Gcrs>::new(
                MU_EARTH,
                R_EARTH,
                J2_EARTH,
                Some(J3_EARTH),
                Some(J4_EARTH),
            ));
        }
        d => panic!("Unsupported gravity degree: {d}"),
    }

    if fm.third_body_sun {
        system = system.with_model(ThirdBodyGravity::sun());
    }
    if fm.third_body_moon {
        system = system.with_model(ThirdBodyGravity::moon());
    }

    if let Some(drag_cfg) = &fm.drag {
        let sat = &scenario.satellite;
        let b = sat.ballistic_coeff_m2_kg.unwrap_or(0.01);
        let mut drag = AtmosphericDrag::<frame::Gcrs>::for_earth_in_frame(Some(b), eop);
        match drag_cfg.model.as_str() {
            "nrlmsise00" => {
                if let Some(weather) = &drag_cfg.weather {
                    let provider = Box::new(ConstantWeather::new(weather.f107, weather.ap));
                    drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(provider)));
                }
            }
            "nrlmsise00_cssi" => {
                let cssi_text = include_str!("fixtures/cssi_test_weather.txt");
                let cssi_data = CssiData::parse(cssi_text).expect("Failed to parse CSSI fixture");
                let provider = Box::new(CssiSpaceWeather::new(cssi_data));
                drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(provider)));
            }
            other => panic!("Unknown drag model: {other}"),
        }
        system = system.with_model(drag);
    }

    system
}

fn build_gcrs_system(scenario: &Scenario) -> OrbitalSystem<frame::Gcrs> {
    build_gcrs_system_with_eop(scenario, GcrsEopStorage::new(ZeroEop))
}

fn load_eop_table() -> arika::earth::eop::EopTable {
    let text = include_str!("fixtures/finals2000A.sample");
    arika::earth::eop::EopTable::from_finals2000a(text).expect("Failed to parse EOP fixture")
}

fn build_gcrs_system_real_eop(scenario: &Scenario) -> OrbitalSystem<frame::Gcrs> {
    // The EOP capability traits are infallible, so a finite-range table only
    // implements them through an adapter that names its out-of-range policy.
    // The fixture spans MJD 60370..60430 (2024-03-01..04-30) and the longest
    // scenario here is 30 days from 2024-03-01, so the clamp never engages.
    build_gcrs_system_with_eop(
        scenario,
        GcrsEopStorage::new(load_eop_table().into_clamped()),
    )
}

/// Propagate the Gcrs path and return the final position [km].
fn final_pos_gcrs(scenario: &Scenario, system: &OrbitalSystem<frame::Gcrs>) -> Vector3<f64> {
    let ic = &scenario.initial_cartesian;
    let initial = OrbitalState::<frame::Gcrs>::new_in_frame(
        Vector3::new(ic.position_km[0], ic.position_km[1], ic.position_km[2]),
        Vector3::new(
            ic.velocity_km_s[0],
            ic.velocity_km_s[1],
            ic.velocity_km_s[2],
        ),
    );

    let dp = DormandPrince;
    let duration = scenario.trajectory.last().unwrap().t_seconds;
    *dp.integrate(system, initial, 0.0, duration, 30.0, |_, _| {})
        .position()
}

/// Final position error of the Gcrs propagation vs the Orekit GCRF fixture.
fn final_pos_err_gcrs(scenario: &Scenario, system: &OrbitalSystem<frame::Gcrs>) -> f64 {
    let final_orekit = scenario.trajectory.last().unwrap();
    (Vector3::new(
        final_orekit.position_km[0],
        final_orekit.position_km[1],
        final_orekit.position_km[2],
    ) - final_pos_gcrs(scenario, system))
    .magnitude()
}

/// Propagate the SimpleEci (default) path and return the final position [km].
fn final_pos_simple(scenario: &Scenario) -> Vector3<f64> {
    let ic = &scenario.initial_cartesian;
    let initial = OrbitalState::new(
        Vector3::new(ic.position_km[0], ic.position_km[1], ic.position_km[2]),
        Vector3::new(
            ic.velocity_km_s[0],
            ic.velocity_km_s[1],
            ic.velocity_km_s[2],
        ),
    );

    let fm = &scenario.force_model;
    let epoch = parse_epoch(&scenario.epoch_utc);

    let mut system = OrbitalSystem::new(MU_EARTH, Box::new(PointMass))
        .with_epoch(epoch)
        .with_body_radius(R_EARTH);

    if fm.gravity.degree == 2 {
        system = system.with_model(ZonalGravity::new(MU_EARTH, R_EARTH, J2_EARTH, None, None));
    }

    if fm.third_body_sun {
        system = system.with_model(ThirdBodyGravity::sun());
    }
    if fm.third_body_moon {
        system = system.with_model(ThirdBodyGravity::moon());
    }

    if let Some(drag_cfg) = &fm.drag {
        let b = scenario.satellite.ballistic_coeff_m2_kg.unwrap_or(0.01);
        let mut drag = AtmosphericDrag::for_earth(Some(b));
        match drag_cfg.model.as_str() {
            "nrlmsise00" => {
                if let Some(w) = &drag_cfg.weather {
                    drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(Box::new(
                        ConstantWeather::new(w.f107, w.ap),
                    ))));
                }
            }
            "nrlmsise00_cssi" => {
                let cssi_text = include_str!("fixtures/cssi_test_weather.txt");
                let cssi_data = CssiData::parse(cssi_text).unwrap();
                drag = drag.with_atmosphere(Box::new(Nrlmsise00::new(Box::new(
                    CssiSpaceWeather::new(cssi_data),
                ))));
            }
            _ => {}
        }
        system = system.with_model(drag);
    }

    let dp = DormandPrince;
    let duration = scenario.trajectory.last().unwrap().t_seconds;
    *dp.integrate(&system, initial, 0.0, duration, 30.0, |_, _| {})
        .position()
}

/// Final position error of the SimpleEci propagation vs the GCRF Orekit fixture.
///
/// The GCRF fixture and EME2000 differ by ~23 mas (frame bias), which is
/// sub-meter at LEO, so comparing SimpleEci against the GCRF fixture gives a
/// meaningful (if slightly pessimistic) error measure.
fn final_pos_err_simple(scenario: &Scenario) -> f64 {
    let final_orekit = scenario.trajectory.last().unwrap();
    (Vector3::new(
        final_orekit.position_km[0],
        final_orekit.position_km[1],
        final_orekit.position_km[2],
    ) - final_pos_simple(scenario))
    .magnitude()
}

/// The `Gcrs` path now evaluates J2 about the true IAU 2006 CIP, while the
/// `SimpleEci` path uses the frame +Z axis (the legacy approximation). On this
/// drag-free J2 + third-body scenario the two propagations therefore *differ* —
/// by the ~0.1° precession offset of the pole, tens of metres over 10 orbits —
/// and the `Gcrs` result is markedly closer to the Orekit reference (whose
/// gravity body frame is CIRF = the CIP).
///
/// This replaces the earlier "frame-agnostic" pin from before J2 became
/// pole-aware: that test guarded the old `Gcrs ≡ SimpleEci` behaviour and was
/// designed to fail once a force became frame-aware, forcing this deliberate
/// update (#191 step②). Drag is excluded so the J2-axis effect is isolated.
#[test]
fn gcrs_true_pole_beats_simpleeci_for_j2() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_thirdbody_iss_10orbits");
    assert!(
        scenario.force_model.drag.is_none(),
        "isolate the J2-pole effect: scenario must stay drag-free"
    );

    // The CIP-vs-+Z pole difference makes the two paths diverge by a
    // precession-scale amount (not ~0 as in the pre-pole-aware design).
    let pos_simple = final_pos_simple(scenario);
    let pos_gcrs = final_pos_gcrs(scenario, &build_gcrs_system(scenario));
    let spread = (pos_simple - pos_gcrs).magnitude();
    assert!(
        spread > 0.01,
        "Gcrs (CIP) and SimpleEci (+Z) J2 should differ by the precession offset, \
         got {spread:.3e} km"
    );

    // And the true-pole Gcrs path is closer to the Orekit (CIRF) reference.
    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);
    assert!(
        gcrs_err < simple_err,
        "true-pole Gcrs J2 should beat SimpleEci: gcrs={gcrs_err:.6} km, simple={simple_err:.6} km"
    );
}

#[test]
fn gcrf_j2_thirdbody_iss_10orbits() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_thirdbody_iss_10orbits");

    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + third-body ISS 10 orbits:");
    println!(
        "  Gcrs  error: {:.6} km ({:.1} m)",
        gcrs_err,
        gcrs_err * 1000.0
    );
    println!(
        "  Simple error: {:.6} km ({:.1} m)",
        simple_err,
        simple_err * 1000.0
    );
    println!("  Improvement:  {:.1}x", simple_err / gcrs_err);

    assert!(
        gcrs_err < 0.5,
        "Gcrs final pos error {:.3} km exceeds 500 m",
        gcrs_err
    );
}

#[test]
fn gcrf_j2_msise_thirdbody_iss_10orbits() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_thirdbody_iss_10orbits");

    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + NRLMSISE-00 + third-body ISS 10 orbits:");
    println!(
        "  Gcrs  error: {:.6} km ({:.1} m)",
        gcrs_err,
        gcrs_err * 1000.0
    );
    println!(
        "  Simple error: {:.6} km ({:.1} m)",
        simple_err,
        simple_err * 1000.0
    );
    println!("  Improvement:  {:.1}x", simple_err / gcrs_err);

    // Measured: Gcrs ~9.8 m, SimpleEci ~12.4 m. Tolerance with ~20% buffer.
    assert!(
        gcrs_err < 0.015,
        "Gcrs final pos error {:.6} km exceeds 15 m",
        gcrs_err
    );
    // Gcrs path must be strictly better than SimpleEci for drag scenarios
    assert!(
        gcrs_err < simple_err,
        "Gcrs ({gcrs_err:.6} km) should be better than SimpleEci ({simple_err:.6} km)"
    );
}

#[test]
fn gcrf_j2_msise_cssi_thirdbody_iss_30day() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_cssi_thirdbody_iss_30day");

    let gcrs_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + NRLMSISE-00 CSSI + third-body ISS 30 days:");
    println!("  Gcrs  error: {:.3} km", gcrs_err);
    println!("  Simple error: {:.3} km", simple_err);
    println!("  Improvement:  {:.1}x", simple_err / gcrs_err);

    // Measured: Gcrs ~14.3 km, SimpleEci ~18.4 km.
    //
    // The bound reflects an inherent 30-day cross-validation floor, not a frame
    // error. Decomposing the Gcrs error (correct CIP co-rotation) shows drag
    // moves the trajectory ~8400 km over 30 days, so the ~0.05-0.3% density
    // difference between our NRLMSISE-00 and Orekit's independent implementation
    // amplifies to ~10 km along-track; the third-body Meeus-vs-DE ephemeris adds
    // ~3.7 km. Both are frame-independent (SimpleEci carries the same gap) — the
    // Gcrs frame handling itself (geodetic, J2 pole, co-rotation axis) matches
    // Orekit to sub-km. (An earlier 12 km bound only held because a +Z
    // co-rotation error happened to cancel part of this floor; the corrected
    // co-rotation removes that coincidence. Third-body ephemeris fidelity is
    // tracked separately as the one reducible piece.)
    assert!(
        gcrs_err < 15.0,
        "Gcrs final pos error {:.3} km exceeds 15 km",
        gcrs_err
    );
    // The frame-validation check: Gcrs must still beat SimpleEci for drag.
    assert!(
        gcrs_err < simple_err,
        "Gcrs ({gcrs_err:.3} km) should be better than SimpleEci ({simple_err:.3} km) for 30-day drag"
    );
}

// Real EOP data tests — validate improvement from finals2000A EOP

#[test]
fn gcrf_real_eop_improves_drag_10orbits() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_thirdbody_iss_10orbits");

    let zero_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let real_err = final_pos_err_gcrs(scenario, &build_gcrs_system_real_eop(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + NRLMSISE-00 + third-body ISS 10 orbits (EOP comparison):");
    println!(
        "  SimpleEci:   {:.6} km ({:.1} m)",
        simple_err,
        simple_err * 1000.0
    );
    println!(
        "  Gcrs ZeroEop: {:.6} km ({:.1} m)",
        zero_err,
        zero_err * 1000.0
    );
    println!(
        "  Gcrs RealEop: {:.6} km ({:.1} m)",
        real_err,
        real_err * 1000.0
    );
    println!("  Improvement (real vs zero): {:.1}x", zero_err / real_err);

    // Real EOP should be at least as good as ZeroEop
    assert!(
        real_err <= zero_err * 1.05,
        "Real EOP ({real_err:.6} km) should not be worse than ZeroEop ({zero_err:.6} km)"
    );
}

#[test]
fn gcrf_real_eop_improves_drag_30day() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_cssi_thirdbody_iss_30day");

    let zero_err = final_pos_err_gcrs(scenario, &build_gcrs_system(scenario));
    let real_err = final_pos_err_gcrs(scenario, &build_gcrs_system_real_eop(scenario));
    let simple_err = final_pos_err_simple(scenario);

    println!("GCRF J2 + NRLMSISE-00 CSSI + third-body ISS 30 days (EOP comparison):");
    println!("  SimpleEci:    {:.6} km", simple_err);
    println!("  Gcrs ZeroEop: {:.6} km", zero_err);
    println!("  Gcrs RealEop: {:.6} km", real_err);
    println!(
        "  Diff (real vs zero): {:.6} km ({:.1} m)",
        (zero_err - real_err),
        (zero_err - real_err) * 1000.0,
    );

    // Real EOP should not be significantly worse than ZeroEop.
    // The effect of EOP on drag geodetic conversion is small compared to
    // LST and ephemeris differences, so improvement may be negligible.
    assert!(
        real_err < zero_err * 1.01,
        "Real EOP ({real_err:.6} km) should not be significantly worse than ZeroEop ({zero_err:.6} km)"
    );
    // Both Gcrs paths should be strictly better than SimpleEci
    assert!(
        real_err < simple_err,
        "Real EOP ({real_err:.6} km) should be better than SimpleEci ({simple_err:.6} km)"
    );
}

/// Decomposes the 30-day Gcrs error into its physical contributors, so the
/// `gcrf_j2_msise_cssi_thirdbody_iss_30day` floor doesn't have to be
/// re-investigated by hand. It propagates the scenario three ways (full, no
/// third-body, no drag) and pins the *structure* of the error budget:
///
/// - Drag dominates the 30-day trajectory by orders of magnitude (~8400 km of
///   along-track motion), so the residual vs Orekit is mostly the inherent
///   ~0.05-0.3% density difference between our NRLMSISE-00 and Orekit's,
///   amplified over that arc.
/// - Third-body (Meeus vs Orekit DE) is a minor contributor (~a few km).
/// - The Gcrs frame handling itself is not the error source (the full error
///   stays in the floor band; removing third-body does not blow it up).
///
/// `#[ignore]`d: three 30-day propagations take many minutes — too slow for the
/// default suite. Run on demand to re-verify the floor:
///   `cargo test -p orts --test oracle_gcrf -- --ignored gcrf_30day_error_floor`
#[test]
#[ignore = "three 30-day propagations (~tens of minutes); on-demand floor diagnostic"]
fn gcrf_30day_error_floor_is_drag_dominated() {
    let fixtures = load_fixtures();
    let scenario = find_scenario(&fixtures, "gcrf_j2_msise_cssi_thirdbody_iss_30day");
    let ic = &scenario.initial_cartesian;
    let duration = scenario.trajectory.last().unwrap().t_seconds;

    // Build the scenario's force model with individual terms toggled off.
    let build = |with_third_body: bool, with_drag: bool| -> OrbitalSystem<frame::Gcrs> {
        let epoch = parse_epoch(&scenario.epoch_utc);
        let mut system = OrbitalSystem::<frame::Gcrs>::new(MU_EARTH, Box::new(PointMass))
            .with_epoch(epoch)
            .with_body_radius(R_EARTH)
            .with_model(ZonalGravity::<frame::Gcrs>::new(
                MU_EARTH, R_EARTH, J2_EARTH, None, None,
            ));
        if with_third_body {
            system = system
                .with_model(ThirdBodyGravity::sun())
                .with_model(ThirdBodyGravity::moon());
        }
        if with_drag {
            let b = scenario.satellite.ballistic_coeff_m2_kg.unwrap_or(0.01);
            let cssi_text = include_str!("fixtures/cssi_test_weather.txt");
            let cssi_data = CssiData::parse(cssi_text).expect("Failed to parse CSSI fixture");
            let provider = Box::new(CssiSpaceWeather::new(cssi_data));
            let drag = AtmosphericDrag::<frame::Gcrs>::for_earth_in_frame(
                Some(b),
                GcrsEopStorage::new(ZeroEop),
            )
            .with_atmosphere(Box::new(Nrlmsise00::new(provider)));
            system = system.with_model(drag);
        }
        system
    };

    let propagate = |system: &OrbitalSystem<frame::Gcrs>| -> Vector3<f64> {
        let initial = OrbitalState::<frame::Gcrs>::new_in_frame(
            Vector3::new(ic.position_km[0], ic.position_km[1], ic.position_km[2]),
            Vector3::new(
                ic.velocity_km_s[0],
                ic.velocity_km_s[1],
                ic.velocity_km_s[2],
            ),
        );
        *DormandPrince
            .integrate(system, initial, 0.0, duration, 30.0, |_, _| {})
            .position()
    };

    let fx = scenario.trajectory.last().unwrap();
    let fixture_final = Vector3::new(fx.position_km[0], fx.position_km[1], fx.position_km[2]);

    let p_full = propagate(&build(true, true));
    let p_no_third_body = propagate(&build(false, true));
    let p_no_drag = propagate(&build(true, false));

    let err_full = (p_full - fixture_final).norm();
    let err_no_third_body = (p_no_third_body - fixture_final).norm();
    let third_body_contrib = (p_full - p_no_third_body).norm();
    let drag_contrib = (p_full - p_no_drag).norm();

    println!("30-day error-floor decomposition (Gcrs, correct CIP co-rotation, ZeroEop):");
    println!("  err vs Orekit (full):           {err_full:.3} km");
    println!("  err vs Orekit (no third-body):  {err_no_third_body:.3} km");
    println!("  drag trajectory contribution:   {drag_contrib:.1} km");
    println!("  third-body trajectory contrib:  {third_body_contrib:.3} km");

    // Drag dominates the trajectory by orders of magnitude over 30 days.
    assert!(
        drag_contrib > 1000.0,
        "drag should move the 30-day trajectory by >1000 km, got {drag_contrib:.1} km"
    );
    assert!(
        drag_contrib > 100.0 * third_body_contrib,
        "drag ({drag_contrib:.1} km) should dominate third-body ({third_body_contrib:.3} km) by >100x"
    );
    // Third-body (Meeus vs DE) is a minor, bounded contributor.
    assert!(
        third_body_contrib < 20.0,
        "third-body contribution should be a few km, got {third_body_contrib:.3} km"
    );
    // The Gcrs frame handling is not the error source: the error stays in the
    // floor band and third-body is not what dominates it.
    assert!(
        err_full < 20.0,
        "full Gcrs error should sit in the model-fidelity floor band, got {err_full:.3} km"
    );
    assert!(
        (err_full - err_no_third_body).abs() < 10.0,
        "third-body should not be the dominant error term (Δerr={:.3} km)",
        (err_full - err_no_third_body).abs()
    );
}
