//! Oracle tests: `OrbitalSystem<Gcrs>` with `SphericalHarmonicGravity<Gcrs>`
//! against Orekit's `NumericalPropagator` + `HolmesFeatherstoneAttractionModel`
//! with ITRF as the gravity body frame.
//!
//! Fixtures generated by `tools/generate_orekit_geopotential_fixtures.py`.
//! Both sides use the coefficients in
//! `tobari/tests/fixtures/orekit_geopotential_70x70.gfc` (written from Orekit's
//! provider), the provider's GM for the point mass, no drag / third body / SRP,
//! and real EOP for the epoch: Orekit from orekit-data, this side from
//! `finals2000A.sample` (the same IERS finals series).
//!
//! What this pins that the pointwise oracle in tobari cannot: the GCRS↔ITRS
//! rotation applied to the field over a full day of Earth rotation, i.e. that
//! the longitude-dependent terms are evaluated at the right longitude as the
//! Earth turns under the orbit.
//!
//! Known difference sources:
//! - **EOP series**: orekit-data's finals vs `finals2000A.sample` may differ
//!   at the sub-mas level for the same dates; Orekit's `simpleEOP = true`
//!   matches our table (no tidal EOP corrections on either side).
//! - **Integrator**: Orekit DOP853 at 1e-14/1e-12 tolerances vs our
//!   Dormand–Prince at a 30 s step.

use arika::earth::GcrsEopStorage;
use arika::earth::eop::EopTable;
use arika::epoch::Epoch;
use arika::frame;
use nalgebra::Vector3;
use orts::orbital::gravity::PointMass;
use orts::orbital::{OrbitalState, OrbitalSystem};
use orts::perturbations::SphericalHarmonicGravity;
use serde::Deserialize;
use std::sync::Arc;
use tobari::gravity::SphericalHarmonicField;
use utsuroi::{DormandPrince, Integrator};

#[derive(Deserialize)]
struct FixtureFile {
    mu_km3_s2: f64,
    scenarios: Vec<Scenario>,
}

#[derive(Deserialize)]
struct Scenario {
    name: String,
    epoch_utc: String,
    initial_cartesian: InitialCartesian,
    force_model: ForceModel,
    trajectory: Vec<TrajectoryPoint>,
}

#[derive(Deserialize)]
struct InitialCartesian {
    position_km: [f64; 3],
    velocity_km_s: [f64; 3],
}

#[derive(Deserialize)]
struct ForceModel {
    gravity: GravityConfig,
}

#[derive(Deserialize)]
struct GravityConfig {
    degree: usize,
    order: usize,
}

#[derive(Deserialize)]
struct TrajectoryPoint {
    t_seconds: f64,
    position_km: [f64; 3],
}

fn load_fixtures() -> FixtureFile {
    serde_json::from_str(include_str!(
        "fixtures/orekit_geopotential_propagation_reference.json"
    ))
    .expect("fixture json must parse")
}

fn load_field() -> SphericalHarmonicField {
    SphericalHarmonicField::from_icgem(include_str!(
        "../../tobari/tests/fixtures/orekit_geopotential_70x70.gfc"
    ))
    .expect("fixture gfc must parse")
}

fn parse_epoch(s: &str) -> Epoch {
    let s = s.trim_end_matches('Z');
    let (date, time) = s.split_once('T').unwrap();
    let d: Vec<u32> = date.split('-').map(|x| x.parse().unwrap()).collect();
    let t: Vec<f64> = time.split(':').map(|x| x.parse().unwrap()).collect();
    Epoch::from_gregorian(d[0] as i32, d[1], d[2], t[0] as u32, t[1] as u32, t[2])
}

fn scenario<'a>(fixtures: &'a FixtureFile, name: &str) -> &'a Scenario {
    fixtures
        .scenarios
        .iter()
        .find(|s| s.name == name)
        .unwrap_or_else(|| panic!("scenario {name} not in fixture"))
}

/// Real EOP for the fixture epoch (MJD 60370..60430 covers 2024-03-20 + 24 h).
fn eop() -> GcrsEopStorage {
    let table = EopTable::from_finals2000a(include_str!("fixtures/finals2000A.sample"))
        .expect("EOP fixture must parse");
    GcrsEopStorage::new(table.into_clamped())
}

fn build_system(fixtures: &FixtureFile, sc: &Scenario) -> OrbitalSystem<frame::Gcrs> {
    let g = &sc.force_model.gravity;
    let field = Arc::new(load_field().truncated(g.degree, g.order));
    assert_eq!(
        field.gm(),
        fixtures.mu_km3_s2,
        "point-mass mu must be the field's GM"
    );
    OrbitalSystem::<frame::Gcrs>::new(field.gm(), Box::new(PointMass))
        .with_epoch(parse_epoch(&sc.epoch_utc))
        .with_model(SphericalHarmonicGravity::<frame::Gcrs>::new(field, eop()))
}

/// Propagate and return the largest position error [km] over the fixture's
/// output points, plus the final one.
fn position_errors(fixtures: &FixtureFile, sc: &Scenario) -> (f64, f64) {
    let system = build_system(fixtures, sc);
    let ic = &sc.initial_cartesian;
    let mut state = OrbitalState::<frame::Gcrs>::new_in_frame(
        Vector3::from(ic.position_km),
        Vector3::from(ic.velocity_km_s),
    );
    let dp = DormandPrince;
    let mut t = 0.0;
    let mut max_err = 0.0f64;
    let mut final_err = 0.0;
    for point in &sc.trajectory {
        if point.t_seconds > t {
            state = dp.integrate(&system, state, t, point.t_seconds, 30.0, |_, _| {});
            t = point.t_seconds;
        }
        let err = (state.position() - Vector3::from(point.position_km)).norm();
        max_err = max_err.max(err);
        final_err = err;
    }
    (max_err, final_err)
}

/// 570 km LEO, 24 h, 70×70: metre-level agreement with Orekit. Measured
/// 0.93 m max (the zonal-only case below measures 0.90 m, so ~0.9 m is the
/// EOP-series / integrator floor and the field itself contributes a few cm);
/// the bound is 2 m. A wrong rotation sense or a dropped tesseral term shows
/// up as tens to hundreds of metres (70×70 vs 20×20 alone is 46 m here).
#[test]
fn leo_24h_70x70_matches_orekit_within_metres() {
    let fixtures = load_fixtures();
    let sc = scenario(&fixtures, "leo_570km_70x70");
    let (max_err, final_err) = position_errors(&fixtures, sc);
    println!(
        "70x70: max {:.3} m, final {:.3} m",
        max_err * 1e3,
        final_err * 1e3
    );
    assert!(max_err < 2e-3, "max position error {:.3} m", max_err * 1e3);
}

#[test]
fn leo_24h_20x20_matches_orekit_within_metres() {
    let fixtures = load_fixtures();
    let sc = scenario(&fixtures, "leo_570km_20x20");
    let (max_err, final_err) = position_errors(&fixtures, sc);
    println!(
        "20x20: max {:.3} m, final {:.3} m",
        max_err * 1e3,
        final_err * 1e3
    );
    assert!(max_err < 2e-3, "max position error {:.3} m", max_err * 1e3);
}

#[test]
fn leo_24h_zonal_4x0_matches_orekit_within_metres() {
    let fixtures = load_fixtures();
    let sc = scenario(&fixtures, "leo_570km_4x0");
    let (max_err, final_err) = position_errors(&fixtures, sc);
    println!(
        "4x0: max {:.3} m, final {:.3} m",
        max_err * 1e3,
        final_err * 1e3
    );
    assert!(max_err < 2e-3, "max position error {:.3} m", max_err * 1e3);
}

/// The fixture itself resolves the high-degree field: 70×70 and 20×20 end
/// tens of metres apart after 24 h (the #411 measurement), so the oracle
/// above cannot pass with the tesserals silently truncated.
#[test]
fn fixture_separates_70x70_from_20x20() {
    let fixtures = load_fixtures();
    let a = scenario(&fixtures, "leo_570km_70x70")
        .trajectory
        .last()
        .unwrap();
    let b = scenario(&fixtures, "leo_570km_20x20")
        .trajectory
        .last()
        .unwrap();
    let sep = (Vector3::from(a.position_km) - Vector3::from(b.position_km)).norm();
    assert!(
        (0.01..1.0).contains(&sep),
        "70x70 vs 20x20 after 24 h: {sep:.4} km"
    );
}
