# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Extract NRLMSISE-00 coefficients from the official C data file.

The coefficient values originate from the NRL official Fortran distribution
(NRLMSISE-00.FOR / DIST12.TXT). The C transcription by Dominik Brodowski
preserves the same numerical values.

This script mechanically parses the C array initializers and generates
a Rust source file with static arrays.

Input:  /tmp/nrlmsise00_data.c (downloaded from magnific0/nrlmsise-00)
Output: tobari/src/nrlmsise00/coefficients.rs

Run: curl -sL https://raw.githubusercontent.com/magnific0/nrlmsise-00/master/nrlmsise-00_data.c -o /tmp/nrlmsise00_data.c
     uv run tools/extract_nrlmsise00_coefficients.py
"""

import re
import sys
from pathlib import Path


def find_matching_brace(text: str, start: int) -> int:
    """Find the position of the closing brace matching the opening brace at `start`."""
    assert text[start] == '{', f"Expected '{{' at position {start}, got '{text[start]}'"
    depth = 0
    i = start
    while i < len(text):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError(f"No matching '}}' found for '{{' at position {start}")


def extract_numbers(text: str) -> list[float]:
    """Extract all floating-point numbers from text, ignoring C comments."""
    # Remove C comments
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    # Extract numbers
    values = []
    for m in re.finditer(r'[+-]?\d+\.?\d*[eE][+-]?\d+|[+-]?\d+\.\d*', text):
        values.append(float(m.group()))
    return values


def parse_c_arrays(text: str) -> list[tuple[str, list[int], list[float]]]:
    """Parse C array declarations with initializers.

    Returns list of (name, dimensions, values).
    Handles nested braces and C comments correctly.
    For arrays declared larger than initialized, zero-pads to declared size.
    """
    arrays = []

    # Find all array declarations
    decl_pattern = re.compile(
        r'double\s+(\w+)\s*((?:\[\d+\])+)\s*=\s*\{',
        re.DOTALL
    )

    for m in decl_pattern.finditer(text):
        name = m.group(1)
        dim_str = m.group(2)
        brace_start = m.end() - 1  # position of '{'

        # Find matching closing brace
        brace_end = find_matching_brace(text, brace_start)
        init_body = text[brace_start + 1:brace_end]

        # Parse dimensions
        dims = [int(d) for d in re.findall(r'\[(\d+)\]', dim_str)]

        # Extract all numbers from the initializer body
        values = extract_numbers(init_body)

        # Zero-pad if fewer values than declared
        expected_count = 1
        for d in dims:
            expected_count *= d

        if len(values) < expected_count:
            values.extend([0.0] * (expected_count - len(values)))
        elif len(values) > expected_count:
            print(f"WARNING: {name} has {len(values)} values, expected {expected_count}")

        arrays.append((name, dims, values))
        print(f"  {name}{dim_str}: {len(values)} values (parsed {len(extract_numbers(init_body))} + {len(values) - len(extract_numbers(init_body))} zero-padded)")

    return arrays


def generate_rust(arrays: list[tuple[str, list[int], list[float]]]) -> str:
    """Generate Rust source file with static coefficient arrays."""
    lines = []
    lines.append('//! NRLMSISE-00 model coefficients.')
    lines.append('//!')
    lines.append('//! Source: NRLMSISE-00 official distribution, U.S. Naval Research Laboratory.')
    lines.append('//! Reference: Picone, J.M. et al. (2002), "NRLMSISE-00 empirical model of the')
    lines.append('//!   atmosphere: Statistical comparisons and scientific issues",')
    lines.append('//!   J. Geophys. Res., 107(A12), 1468, doi:10.1029/2002JA009430')
    lines.append('//! Mathematical framework: Hedin, A.E. (1991), J. Geophys. Res., 96(A2), 1159-1172.')
    lines.append('//!')
    lines.append('//! Values extracted from the NRL official distribution as published data.')
    lines.append('//! NRLMSISE-00 is believed to be in the public domain as a U.S. Government work')
    lines.append('//! (17 U.S.C. § 105), though no explicit license was provided by NRL.')
    lines.append('//!')
    lines.append('//! Generated by: tools/extract_nrlmsise00_coefficients.py')
    lines.append('//! Source file: nrlmsise-00_data.c (C transcription by Dominik Brodowski,')
    lines.append('//!   based on official NRL Fortran distribution DIST12.TXT)')
    lines.append('')

    # Array descriptions
    descriptions = {
        'pt': 'Temperature coefficients (150 terms).',
        'pd': 'Density coefficients for each species (9 species x 150 terms).\n///\n/// Species order: He, O, N2, TLB, O2, Ar, H, N, anomalous O.',
        'ps': 'S-parameter coefficients (150 terms).',
        'pdl': 'Turbo coefficients (2 x 25 terms).',
        'ptm': 'Lower boundary temperature parameters (50 terms).\n///\n/// Only first 10 values are explicitly set; remaining 40 are zero.',
        'pdm': 'Lower boundary density parameters (8 species x 10 terms).',
        'ptl': 'Temperature correction coefficients (4 corrections x 100 terms).\n///\n/// Correction order: TN1(2), TN1(3), TN1(4), TN1(5).',
        'pma': 'Additional temperature/gradient coefficients (10 x 100 terms).\n///\n/// Index order: TN2(2), TN2(3), TN2(4), TN3(2), TN3(3), middle atmo avg,\n///   TN2(1), TN1(1), TGN3(2), TGN2(2).',
        'sam': 'Semiannual multiplier (100 terms).',
        'pavgm': 'Middle atmosphere average values (10 terms).',
    }

    for name, dims, values in arrays:
        lines.append(f'/// {descriptions.get(name, f"Coefficient array `{name}`.")}')

        if len(dims) == 1:
            rust_name = name.upper()
            lines.append(f'pub const {rust_name}: [f64; {dims[0]}] = [')
            for i in range(0, len(values), 5):
                chunk = values[i:i + 5]
                formatted = ', '.join(f'{v:14.5E}' for v in chunk)
                lines.append(f'    {formatted},')
            lines.append('];')
        elif len(dims) == 2:
            rust_name = name.upper()
            lines.append(f'pub const {rust_name}: [[f64; {dims[1]}]; {dims[0]}] = [')
            stride = dims[1]
            for row in range(dims[0]):
                start = row * stride
                row_vals = values[start:start + stride]
                lines.append(f'    // [{row}]')
                lines.append('    [')
                for i in range(0, len(row_vals), 5):
                    chunk = row_vals[i:i + 5]
                    formatted = ', '.join(f'{v:14.5E}' for v in chunk)
                    lines.append(f'        {formatted},')
                lines.append('    ],')
            lines.append('];')

        lines.append('')

    return '\n'.join(lines)


def main():
    input_path = Path('/tmp/nrlmsise00_data.c')
    if not input_path.exists():
        print(f"Error: {input_path} not found.")
        print("Run: curl -sL https://raw.githubusercontent.com/magnific0/nrlmsise-00/master/nrlmsise-00_data.c -o /tmp/nrlmsise00_data.c")
        sys.exit(1)

    text = input_path.read_text()
    print("Parsing C arrays...")
    arrays = parse_c_arrays(text)

    total_values = sum(len(v) for _, _, v in arrays)
    print(f"\nFound {len(arrays)} arrays, {total_values} total values")

    rust_code = generate_rust(arrays)

    output_path = Path('tobari/src/nrlmsise00/coefficients.rs')
    output_path.write_text(rust_code)
    print(f"\nWrote {output_path} ({output_path.stat().st_size / 1024:.1f} KB)")


if __name__ == '__main__':
    main()
