# /// script
# requires-python = ">=3.10"
# dependencies = ["ppigrf==2.0.0"]
# ///
"""Generate IGRF reference fixtures using ppigrf, IAGA-VMOD's own implementation.

ppigrf is published by the same body (IAGA Working Group V-MOD) that produces
the IGRF coefficients, so it is an independent implementation of the model our
Rust code in `tobari::magnetic::Igrf` implements — not a reimplementation of our
own logic. That makes it usable as an oracle for the spherical-harmonic
evaluation: the Schmidt semi-normalized Legendre recursion, the outer sign of
the eastward component, and the radial/southward components.

Both implementations share:
  - The IGRF-14 Gauss coefficients (same published tables)
  - Schmidt semi-normalization
  - Linear interpolation between the 5-year main-field epochs

Known difference sources:
  - **Coordinate reference**: ppigrf takes geodetic latitude and height above
    the WGS-84 ellipsoid, and returns east/north/up components. `tobari` takes
    the same geodetic input, converts to geocentric spherical internally, and
    returns ECEF Cartesian. The fixture therefore stores both the geodetic
    query point and the expected east/north/up triple, and the Rust test does
    the ECEF -> ENU rotation. Any residual is a real disagreement, not a
    convention mismatch.
  - **Coefficient generation**: ppigrf ships its own copy of the IGRF
    coefficient file; ours is generated by `tobari/build.rs`. A future IGRF
    generation could land in one before the other. Changed Gauss coefficients
    alter the expansion differently per latitude, longitude, altitude and
    component, so that shows up as a systematic but spatially varying
    disagreement — not as a single offset.

Not covered here: the exact geographic poles. ppigrf divides by `sin(theta)`
with no limit branch, so it returns NaN there (and an asymmetric finite value at
the south pole), which makes it unusable as a reference at those points.
`tobari` does implement the closed-form limit
`lim P^1_n(cos theta)/sin theta = sqrt(n(n+1)/2)`, and that branch is pinned by
`b_phi_pole_branch_is_continuous` in `tobari/src/magnetic/igrf/mod.rs`, which
checks the limit branch against the ordinary path just off-axis. The fixture
therefore stops at high colatitude, where both implementations use the ordinary
path.

Output: tobari/tests/fixtures/igrf_ppigrf_reference.json
Run:   uv run tools/generate_igrf_fixtures.py
"""

import datetime as dt
import importlib.metadata
import json
import pathlib

import ppigrf

# Query points chosen to exercise every branch of the Legendre recursion and
# the eastward-component sign:
#   - the equator, where the sub-diagonal P[n][n-1] vanishes (cos(theta) = 0)
#     so only dP/dtheta carries the sub-diagonal coefficient;
#   - mid-latitudes in all four longitude quadrants, where the intermediate
#     orders (0 < m < n) and the eastward component both matter most;
#   - high colatitudes, where `P^m_n / sin(theta)` is largest on the ordinary
#     B_phi path;
#   - several altitudes, so the (a/r)^(n+2) weighting shifts between degrees.
POINTS = [
    # (label, longitude_deg, geodetic_latitude_deg, height_km)
    ("equator_prime_meridian", 0.0, 0.0, 0.0),
    ("equator_east", 90.0, 0.0, 0.0),
    ("equator_dateline", 180.0, 0.0, 0.0),
    ("equator_west", -90.0, 0.0, 0.0),
    ("leo_equator", 0.0, 0.0, 500.0),
    ("leo_mid_north_east", 135.0, 45.0, 500.0),
    ("leo_mid_north_west", -45.0, 45.0, 500.0),
    ("leo_mid_south_east", 70.0, -35.0, 500.0),
    ("leo_mid_south_west", -70.0, -35.0, 500.0),
    ("leo_high_north", 10.0, 80.0, 500.0),
    ("leo_high_south", 10.0, -80.0, 500.0),
    # High colatitude, where P^m_n / sin(theta) is large and the ordinary
    # (non-limit) B_phi path is most sensitive. See the note below on why the
    # exact poles are absent.
    ("near_north_pole", 0.0, 89.5, 500.0),
    ("near_south_pole", 0.0, -89.5, 500.0),
    ("very_near_north_pole", 40.0, 89.99, 500.0),
    ("very_near_south_pole", 40.0, -89.99, 500.0),
    ("sso_altitude_mid", 25.0, 60.0, 800.0),
    ("geo_equator", 0.0, 0.0, 35786.0),
]

# Epochs: an exact main-field epoch, a point inside an interpolation interval,
# and one in the secular-variation extrapolation range beyond the last epoch.
EPOCHS = [
    ("2025-01-01T00:00:00Z", dt.datetime(2025, 1, 1)),
    ("2022-07-01T00:00:00Z", dt.datetime(2022, 7, 1)),
    ("2027-04-15T00:00:00Z", dt.datetime(2027, 4, 15)),
]


def main() -> None:
    records = []
    for epoch_iso, date in EPOCHS:
        for label, lon, lat, height in POINTS:
            be, bn, bu = ppigrf.igrf(lon, lat, height, date)
            records.append(
                {
                    "label": label,
                    "epoch": epoch_iso,
                    "longitude_deg": lon,
                    "latitude_deg": lat,
                    "height_km": height,
                    # nT, geodetic east / north / up
                    "b_east_nt": float(be.item()),
                    "b_north_nt": float(bn.item()),
                    "b_up_nt": float(bu.item()),
                }
            )

    out = {
        "source": "ppigrf (IAGA Working Group V-MOD)",
        # Recorded so a regenerated fixture that disagrees with the committed
        # one can be traced to a reference change rather than to our code.
        "ppigrf_version": importlib.metadata.version("ppigrf"),
        "generator": "tools/generate_igrf_fixtures.py",
        "components": "geodetic east / north / up, nT",
        "points": records,
    }

    dest = (
        pathlib.Path(__file__).resolve().parent.parent
        / "tobari/tests/fixtures/igrf_ppigrf_reference.json"
    )
    dest.write_text(json.dumps(out, indent=2) + "\n")
    print(f"wrote {len(records)} points to {dest}")


if __name__ == "__main__":
    main()
