# /// script
# requires-python = ">=3.10"
# dependencies = ["orekit-jpype", "jdk4py"]
# ///
"""Generate Orekit reference vectors for the Sun as seen from each central body.

Cross-validates `arika::sun::sun_position_from_body` against Orekit's DE
ephemeris. The vector this pins is what turns SRP and the third-body term when
the central body is not Earth, and arika builds it from three different
sources: the Meeus geocentric series for Earth, that series minus the lunar
one for the Moon, and the Standish heliocentric elements (negated, rotated from
the J2000 ecliptic to the equator) for the planets. Every other test on this
path compares arika against another part of arika, so a sign, phase or
ecliptic-to-equatorial error could hold across all of them.

Orekit's `CelestialBody.getPosition` is barycentric-corrected DE data read from
orekit-data, which shares no code and no series with either of arika's models.

The frame is EME2000 (J2000 mean equator and equinox), matching what arika
returns; dates are given in UTC, matching `Epoch::from_gregorian`. Positions
are converted from metres to kilometres, arika's unit.

Run with:  uv run tools/generate_body_sun_fixtures.py

which rewrites arika/tests/fixtures/body_sun_orekit_reference.json. Pass a path
to write somewhere else.
"""

import json
import os
import pathlib
import sys

import orekit_jpype as orekit

orekit.initVM()
from orekit_jpype.pyhelpers import (  # noqa: E402
    download_orekit_data_curdir,
    setup_orekit_curdir,
)

# Both of these must be captured before the chdir below. Orekit wants its data
# directory as the working directory, so afterwards a relative path from the
# command line would resolve inside that cache instead of where it was typed.
REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
ORIG_CWD = pathlib.Path.cwd()
DEFAULT_OUT = (
    REPO_ROOT / "arika" / "tests" / "fixtures" / "body_sun_orekit_reference.json"
)

# Orekit needs its data directory; keep the download out of the repo tree.
CACHE = pathlib.Path(os.environ.get("XDG_CACHE_HOME", pathlib.Path.home() / ".cache"))
WORK = CACHE / "orts-orekit-data"
WORK.mkdir(parents=True, exist_ok=True)
os.chdir(WORK)
if not (WORK / "orekit-data.zip").exists():
    download_orekit_data_curdir()
setup_orekit_curdir()

from org.orekit.bodies import CelestialBodyFactory  # noqa: E402
from org.orekit.frames import FramesFactory  # noqa: E402
from org.orekit.time import AbsoluteDate, TimeScalesFactory  # noqa: E402

# Every body `sun_position_from_body` answers for. Uranus and Neptune are
# outside the Standish element table and are refused, so there is nothing to
# compare; the Sun is refused as its own central body.
BODIES = {
    "earth": CelestialBodyFactory.getEarth,
    "moon": CelestialBodyFactory.getMoon,
    "mercury": CelestialBodyFactory.getMercury,
    "venus": CelestialBodyFactory.getVenus,
    "mars": CelestialBodyFactory.getMars,
    "jupiter": CelestialBodyFactory.getJupiter,
    "saturn": CelestialBodyFactory.getSaturn,
}

# Spread over 75 years and around the calendar, so a frame error that grows
# with time from J2000 and a phase error within the year both show up.
EPOCHS = [
    (2000, 1, 1, 12, 0, 0.0),
    (2024, 3, 20, 12, 0, 0.0),
    (2026, 3, 20, 12, 0, 0.0),
    (2026, 9, 22, 0, 0, 0.0),
    (2050, 1, 1, 0, 0, 0.0),
    (2075, 7, 4, 6, 0, 0.0),
]

M_PER_KM = 1000.0


def main() -> None:
    out_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT
    if not out_path.is_absolute():
        out_path = ORIG_CWD / out_path

    utc = TimeScalesFactory.getUTC()
    frame = FramesFactory.getEME2000()
    sun = CelestialBodyFactory.getSun()

    cases = []
    for year, month, day, hour, minute, second in EPOCHS:
        date = AbsoluteDate(year, month, day, hour, minute, second, utc)
        sun_pos = sun.getPosition(date, frame)
        for name, getter in BODIES.items():
            body_pos = getter().getPosition(date, frame)
            v = sun_pos.subtract(body_pos)
            cases.append(
                {
                    "body": name,
                    "epoch_utc": [year, month, day, hour, minute, second],
                    "sun_from_body_km": [
                        v.getX() / M_PER_KM,
                        v.getY() / M_PER_KM,
                        v.getZ() / M_PER_KM,
                    ],
                }
            )

    out_path.write_text(
        json.dumps(
            {
                "description": (
                    "Sun position relative to each central body, EME2000, km. "
                    "Generated by tools/generate_body_sun_fixtures.py from "
                    "Orekit's DE ephemeris."
                ),
                "frame": "EME2000",
                "time_scale": "UTC",
                "unit": "km",
                "cases": cases,
            },
            indent=2,
        )
        + "\n"
    )
    print(f"wrote {len(cases)} cases to {out_path}")


if __name__ == "__main__":
    main()
