//! Third-party license notice surface for the orts-cli binary.
//!
//! The orts-cli binary redistributes three distinct dependency graphs and
//! this module stitches the per-graph NOTICE files together at runtime:
//!
//! 1. **Native Rust deps** of the cli itself — generated by `cli/build.rs`
//!    via `notalawyer-build` (which shells out to `cargo about generate`)
//!    into `$OUT_DIR/notalawyer` and pulled in with
//!    [`notalawyer::include_notice!`].
//! 2. **Rust deps of the wasm-pack'd workspace crates** (`kaname`,
//!    `rrd-wasm`) that are compiled with their `wasm` feature and bundled
//!    into the viewer. The native cli graph does not reach the wasm-only
//!    optional deps (`wasm-bindgen`, `serde-wasm-bindgen`, ...), so
//!    `cli/build.rs` runs an extra `cargo about` pass per crate and writes
//!    the result to `$OUT_DIR/notalawyer_wasm_<crate>`.
//! 3. **npm deps bundled into the viewer** — generated during the Vite
//!    build ([`viewer/vite.config.ts`]) by `rollup-plugin-license` into
//!    `viewer/dist/third-party-licenses.txt`, which is then copied into
//!    `cli/viewer-dist/` by `cli/build.rs` and embedded via `rust-embed`
//!    through [`crate::commands::serve::spa`].

/// NOTICE for the statically-linked Rust dependencies of orts-cli.
///
/// In docs.rs builds or local builds without `cargo-about` installed, the
/// build script writes a placeholder into `$OUT_DIR/notalawyer` instead of
/// the real notice.
pub fn rust_notice() -> &'static str {
    notalawyer::include_notice!()
}

/// NOTICE for the `kaname` Rust crate's dependencies as compiled with its
/// `wasm` feature (as packed into the viewer bundle by wasm-pack).
pub fn wasm_kaname_notice() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/notalawyer_wasm_kaname"))
}

/// NOTICE for the `rrd-wasm` Rust crate's dependencies as compiled with its
/// `wasm` feature (as packed into the viewer bundle by wasm-pack).
pub fn wasm_rrd_notice() -> &'static str {
    include_str!(concat!(env!("OUT_DIR"), "/notalawyer_wasm_rrd-wasm"))
}

/// NOTICE for the viewer's npm-side dependencies, if the viewer feature is
/// enabled and the viewer bundle includes the `third-party-licenses.txt`
/// file produced by `rollup-plugin-license`.
#[cfg(feature = "viewer")]
pub fn viewer_notice() -> Option<String> {
    let file = crate::commands::serve::spa::get_asset("third-party-licenses.txt")?;
    Some(String::from_utf8_lossy(&file.data).into_owned())
}

#[cfg(not(feature = "viewer"))]
pub fn viewer_notice() -> Option<String> {
    None
}

/// Combined NOTICE string suitable for passing to
/// [`notalawyer_clap::ParseExt::parse_with_license_notice`].
///
/// Concatenates the cli-native Rust notice, the per-wasm-crate Rust notices,
/// and (optionally) the viewer's npm notice, separated by section headers.
pub fn combined_notice() -> String {
    let mut out = String::new();
    out.push_str("=== Rust dependencies (native CLI) ===\n\n");
    out.push_str(rust_notice());

    let wasm_kaname = wasm_kaname_notice();
    if !wasm_kaname.is_empty() {
        out.push_str("\n=== Rust dependencies (viewer WASM — kaname) ===\n\n");
        out.push_str(wasm_kaname);
    }

    let wasm_rrd = wasm_rrd_notice();
    if !wasm_rrd.is_empty() {
        out.push_str("\n=== Rust dependencies (viewer WASM — rrd-wasm) ===\n\n");
        out.push_str(wasm_rrd);
    }

    if let Some(viewer) = viewer_notice() {
        out.push_str("\n=== Viewer (npm) dependencies ===\n\n");
        out.push_str(&viewer);
    }

    out
}
